-- Karpus Kids - Esquema de Base de Datos para Supabase (Postgres)
-- ARQUITECTURA FINAL KARPUS KIDS (Supabase Auth + RLS)
-- Ejecutar en SQL Editor de Supabase

-- ⚠️ REINICIO DE ESQUEMA (Necesario para corregir el error integer = uuid)
-- COMENTADO PARA NO BORRAR DATOS EXISTENTES:
-- drop table if exists public.attendance cascade;
-- drop table if exists public.students cascade;
-- drop table if exists public.classrooms cascade;
-- drop table if exists public.profiles cascade;

-- 1. TABLA DE PERFILES (Usuarios del sistema)
create table if not exists public.profiles (
  id uuid not null references auth.users(id) on delete cascade primary key,
  email text unique,
  name text,
  role text check (role in ('directora', 'maestra', 'padre')),
  avatar_url text,
  phone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. TABLA DE AULAS
create table if not exists public.classrooms (
  id bigint generated by default as identity primary key,
  name text not null,
  level text,
  capacity integer default 20,
  teacher_id uuid references public.profiles(id) on delete set null, -- Maestra asignada
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. TABLA DE ESTUDIANTES
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  classroom_id bigint references public.classrooms(id) on delete set null,
  parent_id uuid references public.profiles(id),
  is_active boolean default true,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. TABLA DE ASISTENCIA
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  classroom_id bigint references public.classrooms(id),
  date date default current_date,
  status text check (status in ('present', 'absent', 'late')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(student_id, date)
);

-- 5. SEGURIDAD (Row Level Security)
alter table public.profiles enable row level security;
alter table public.classrooms enable row level security;
alter table public.students enable row level security;
alter table public.attendance enable row level security;

-- 6. POLÍTICAS DE ACCESO (Policies)

-- Helper function to avoid RLS recursion
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS text
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$;

-- Limpiar políticas previas para evitar errores de duplicados
drop policy if exists "Ver perfiles" on public.profiles;
drop policy if exists "Editar propio perfil" on public.profiles;
drop policy if exists "Directora gestiona aulas" on public.classrooms;
drop policy if exists "Maestra ve sus aulas" on public.classrooms;
drop policy if exists "Directora gestiona estudiantes" on public.students;
drop policy if exists "Maestra ve estudiantes de sus aulas" on public.students;
drop policy if exists "Padres ven sus hijos" on public.students;
drop policy if exists "Directora ve asistencia" on public.attendance;
drop policy if exists "Maestra registra asistencia" on public.attendance;
drop policy if exists "Directora ve todos los perfiles" on public.profiles;
drop policy if exists "Usuarios ven su propio perfil" on public.profiles;

-- PROFILES: Ver todos (Directora), ver el suyo (todos)
create policy "Directora ve todos los perfiles" on public.profiles for select using (
  get_my_role() = 'directora'
);

create policy "Usuarios ven su propio perfil" on public.profiles for select using (
  auth.uid() = id
);

create policy "Editar propio perfil" on public.profiles for update using (auth.uid() = id);

-- CLASSROOMS: Directora ve todo, Maestra ve las suyas
create policy "Directora gestiona aulas" on public.classrooms for all using (
  get_my_role() = 'directora'
);
create policy "Maestra ve sus aulas" on public.classrooms for select using (
  teacher_id = auth.uid() or 
  get_my_role() = 'directora'
);

-- STUDENTS: Directora ve todo, Maestra ve los de sus aulas, Padres ven sus hijos
create policy "Directora gestiona estudiantes" on public.students for all using (
  get_my_role() = 'directora'
);
create policy "Maestra ve estudiantes de sus aulas" on public.students for select using (
  exists (select 1 from public.classrooms c where c.id = students.classroom_id and c.teacher_id = auth.uid())
);
create policy "Padres ven sus hijos" on public.students for select using (parent_id = auth.uid());

-- ATTENDANCE: Directora ve todo, Maestra gestiona su aula
create policy "Directora ve asistencia" on public.attendance for select using (
  get_my_role() = 'directora'
);
create policy "Maestra registra asistencia" on public.attendance for all using (
  exists (select 1 from public.classrooms c where c.id = attendance.classroom_id and c.teacher_id = auth.uid())
);

-- TRIGGER PARA CREAR PERFIL AUTOMÁTICO AL REGISTRARSE
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'name',
    coalesce(new.raw_user_meta_data->>'role', 'padre') -- Default to 'padre' if not specified
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

  ALTER TABLE public.students 
ADD COLUMN IF NOT EXISTS p1_name text,
ADD COLUMN IF NOT EXISTS p1_phone text,
ADD COLUMN IF NOT EXISTS p1_email text,
ADD COLUMN IF NOT EXISTS p1_job text,
ADD COLUMN IF NOT EXISTS p1_address text,
ADD COLUMN IF NOT EXISTS p1_emergency_contact text,
ADD COLUMN IF NOT EXISTS p2_name text,
ADD COLUMN IF NOT EXISTS p2_phone text,
ADD COLUMN IF NOT EXISTS p2_email text,
ADD COLUMN IF NOT EXISTS p2_job text,
ADD COLUMN IF NOT EXISTS p2_address text,
ADD COLUMN IF NOT EXISTS p2_emergency_contact text,
ADD COLUMN IF NOT EXISTS start_date date,
ADD COLUMN IF NOT EXISTS allergies text,
ADD COLUMN IF NOT EXISTS blood_type text,
ADD COLUMN IF NOT EXISTS authorized_pickup text;


-- SQL para corregir el perfil de la Directora
-- Ejecuta esto en el Editor SQL de Supabase para vincular tu usuario de Auth con la tabla de perfiles.

INSERT INTO public.profiles (id, email, name, role)
VALUES (
  '08fd7933-4027-48b4-87e5-d81144e134cd', -- ID proporcionado por ti
  'directora@karpus.local',
  'Directora Principal',
  'directora'
)
ON CONFLICT (id) DO UPDATE
SET 
  role = 'directora',
  email = EXCLUDED.email,
  name = EXCLUDED.name;

-- Verificación opcional
SELECT * FROM public.profiles WHERE id = '08fd7933-4027-48b4-87e5-d81144e134cd';


-- FIX: Corregir error de "infinite recursion" en políticas RLS y agregar columnas faltantes
-- Este script crea una función segura para verificar roles, actualiza las políticas y asegura que la tabla students tenga todas las columnas.

-- 1. Función para obtener el rol del usuario actual (bypass RLS)
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS text
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$;

-- 2. Corregir política recursiva en PROFILES
DROP POLICY IF EXISTS "Directora ve todos los perfiles" ON public.profiles;

CREATE POLICY "Directora ve todos los perfiles" ON public.profiles FOR SELECT USING (
  get_my_role() = 'directora'
);

-- 3. Optimizar otras políticas para usar la nueva función (evita subconsultas repetitivas)

-- Classrooms
DROP POLICY IF EXISTS "Directora gestiona aulas" ON public.classrooms;
CREATE POLICY "Directora gestiona aulas" ON public.classrooms FOR ALL USING (
  get_my_role() = 'directora'
);

DROP POLICY IF EXISTS "Maestra ve sus aulas" ON public.classrooms;
CREATE POLICY "Maestra ve sus aulas" ON public.classrooms FOR SELECT USING (
  teacher_id = auth.uid() OR get_my_role() = 'directora'
);

-- Students
DROP POLICY IF EXISTS "Directora gestiona estudiantes" ON public.students;
CREATE POLICY "Directora gestiona estudiantes" ON public.students FOR ALL USING (
  get_my_role() = 'directora'
);

-- Attendance
DROP POLICY IF EXISTS "Directora ve asistencia" ON public.attendance;
CREATE POLICY "Directora ve asistencia" ON public.attendance FOR SELECT USING (
  get_my_role() = 'directora'
);

-- 4. Agregar columnas faltantes a la tabla students (para el modal de perfil)
ALTER TABLE public.students 
ADD COLUMN IF NOT EXISTS p1_name text,
ADD COLUMN IF NOT EXISTS p1_phone text,
ADD COLUMN IF NOT EXISTS p1_email text,
ADD COLUMN IF NOT EXISTS p1_job text,
ADD COLUMN IF NOT EXISTS p1_address text,
ADD COLUMN IF NOT EXISTS p1_emergency_contact text,
ADD COLUMN IF NOT EXISTS p2_name text,
ADD COLUMN IF NOT EXISTS p2_phone text,
ADD COLUMN IF NOT EXISTS p2_email text,
ADD COLUMN IF NOT EXISTS p2_job text,
ADD COLUMN IF NOT EXISTS p2_address text,
ADD COLUMN IF NOT EXISTS p2_emergency_contact text,
ADD COLUMN IF NOT EXISTS start_date date,
ADD COLUMN IF NOT EXISTS allergies text,
ADD COLUMN IF NOT EXISTS blood_type text,
ADD COLUMN IF NOT EXISTS authorized_pickup text;

-- 7. TABLAS PARA PUBLICACIONES Y MULTIMEDIA
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  teacher_id uuid references public.profiles(id),
  content text,
  media_url text,
  media_type text, -- 'image', 'video', 'document'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Políticas RLS para posts
alter table public.posts enable row level security;
create policy "Ver posts" on public.posts for select using (true);
create policy "Maestras crean posts" on public.posts for insert with check (auth.uid() = teacher_id);

-- 8. STORAGE (Ejecutar manualmente en Dashboard si falla por permisos)
-- Nota: La creación de buckets suele requerir hacerlo desde el panel de Supabase, 
-- pero intentamos insertar si la extensión lo permite.
insert into storage.buckets (id, name, public) values ('classroom_media', 'classroom_media', true) on conflict do nothing;

create policy "Public Access Media" on storage.objects for select using ( bucket_id = 'classroom_media' );
create policy "Teachers Upload Media" on storage.objects for insert with check ( bucket_id = 'classroom_media' and auth.role() = 'authenticated' );
