 ============================================================
-- SISTEMA DE PREINSCRIPCIÓN E INSCRIPCIÓN (Karpus Kids)
-- -----------------------------------------------
-- 1. payment_concepts: catálogo de conceptos facturables
-- 2. student_preregistrations: expediente público de preinscripción
-- 3. student_charges: libro de cargos (matrícula, mensualidades, kit...)
-- 4. students.payment_plan: plan financiero del alumno
-- 5. RPC generate_student_charges: generación automática al admitir
-- 6. RPC get_classrooms_capacity: aforo de aulas (ocupación)
-- 7. RPC review_preregistration: transiciones de estado auditadas
-- 8. RLS + grants + storage bucket para documentos públicos
-- ============================================================

-- ------------------------------------------------------------
-- 1. CATÁLOGO DE CONCEPTOS DE PAGO
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payment_concepts (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           text NOT NULL,
  type           text NOT NULL DEFAULT 'mensualidad'
                 CHECK (type IN ('inscripcion','mensualidad','prolongado','materiales','kit','servicio','otro')),
  default_amount numeric(10,2) DEFAULT 0,
  is_active      boolean DEFAULT true,
  sort_order     int DEFAULT 0,
  created_at     timestamp with time zone DEFAULT now() NOT NULL
);

INSERT INTO public.payment_concepts (name, type, default_amount, sort_order) VALUES
  ('Inscripción',          'inscripcion',   2000,  1),
  ('Mensualidad',          'mensualidad',   4500,  2),
  ('Día Prolongado',       'prolongado',    1500,  3),
  ('Kit de Libros',        'kit',           1500,  4),
  ('Uniformes',            'servicio',       800,  5),
  ('Cuota Única Anual',    'mensualidad',   45000, 6),
  ('Semestre I',           'mensualidad',   22500, 7),
  ('Semestre II',          'mensualidad',   22500, 8)
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------
-- 2. PREINSCRIPCIONES (formulario público por wizard)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_preregistrations (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status                text NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','reviewing','admitted','converted','rejected','expired')),
  -- Paso 1: Datos del niño(a)
  student_name          text NOT NULL,
  student_last_name     text,
  birth_date            date,
  gender                text CHECK (gender IN ('Masculino','Femenino')),
  nationality           text DEFAULT 'Dominicana',
  school_year_requested text,
  level_requested       text,
  schedule              text,
  estimated_entry_date  date,
  has_siblings          boolean DEFAULT false,
  sibling_name          text,
  -- Paso 2: Padres / Tutores (estructura multitutor)
  parent_1              jsonb DEFAULT '{}',
  parent_2              jsonb DEFAULT '{}',
  -- Paso 3: Emergencia y personas autorizadas
  emergency_contact     jsonb DEFAULT '{}',
  authorized_people     jsonb DEFAULT '[]',
  -- Paso 4: Ficha médica
  medical               jsonb DEFAULT '{}',
  -- Paso 5: Documentos subidos (urls por concepto)
  documents             jsonb DEFAULT '{}',
  -- Paso 6: Autorizaciones y firma
  consents              jsonb DEFAULT '{}',
  signature_data        text,
  -- Contacto rápido para listado administrativo
  contact_email         text,
  contact_phone         text,
  -- Auditoría de revisión
  review_notes          text,
  reviewed_by           uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at           timestamp with time zone,
  converted_student_id  bigint REFERENCES public.students(id) ON DELETE SET NULL,
  -- Metadatos de origen
  ip_address            text,
  user_agent            text,
  created_at            timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_prereg_status        ON public.student_preregistrations (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_prereg_email         ON public.student_preregistrations (contact_email) WHERE contact_email IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_prereg_converted     ON public.student_preregistrations (converted_student_id) WHERE converted_student_id IS NOT NULL;

-- ------------------------------------------------------------
-- 3. LIBRO DE CARGOS DEL ESTUDIANTE (student_charges)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_charges (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  concept_id   bigint REFERENCES public.payment_concepts(id) ON DELETE SET NULL,
  concept      text NOT NULL,
  type         text NOT NULL DEFAULT 'mensualidad'
               CHECK (type IN ('inscripcion','mensualidad','prolongado','materiales','kit','servicio','otro')),
  amount       numeric(10,2) NOT NULL DEFAULT 0,
  discount_pct numeric(5,2)  NOT NULL DEFAULT 0,
  amount_net   numeric(10,2) NOT NULL DEFAULT 0,
  month_paid   text,
  due_date     date,
  status       text NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','review','paid','waived')),
  method       text,
  reference    text,
  proof_url    text,
  paid_date    timestamp with time zone,
  notes        text,
  created_by   uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(student_id, concept, month_paid)
);

CREATE INDEX IF NOT EXISTS idx_student_charges_student ON public.student_charges (student_id, due_date DESC);
CREATE INDEX IF NOT EXISTS idx_student_charges_status  ON public.student_charges (status) WHERE status = 'pending';

-- Plan financiero del alumno (único / doble / mensual)
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS payment_plan text
  CHECK (payment_plan IN ('unico','doble','mensual'));
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS discount_pct numeric(5,2) DEFAULT 0;

-- Columnas del expediente digital (Pestaña Información)
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS last_name text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS birth_date date;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS gender text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS nationality text DEFAULT 'Dominicana';
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS birthplace text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS province text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS municipality text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS sector text;

-- Columnas del expediente digital (Pestaña Salud)
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS insurance text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS pediatrician text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS pediatrician_phone text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS medical_conditions text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS medications text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS food_restrictions text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS disabilities text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS vaccinations_complete boolean DEFAULT false;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emergency_protocol text;

-- Columnas del expediente digital (Pestaña Familia + Docs)
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS authorized_people jsonb DEFAULT '[]';
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS documents jsonb DEFAULT '{}';
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS inscription_fee numeric(10,2) DEFAULT 0;

-- Columnas espejo del wizard (pasos 1-2): inscripción y tutores
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS school_year_requested text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS level_requested text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS estimated_entry_date date;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS has_siblings boolean DEFAULT false;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS sibling_name text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p1_relationship text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p1_cedula text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p1_whatsapp text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p1_occupation text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p1_workplace text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p2_relationship text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p2_cedula text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p2_whatsapp text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p2_occupation text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p2_workplace text;

-- Columnas espejo del wizard (pasos 3-4): emergencia y salud
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emg_name text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emg_relationship text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emg_cedula text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emg_phone text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS medical_notes text;

-- Columnas espejo del wizard (paso 6): autorizaciones y firma
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS consents jsonb DEFAULT '{}';
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS signature_data text;

-- ------------------------------------------------------------
-- 4. RPC: GENERAR CARGOS AL ADMITIR
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.generate_student_charges(
  p_student_id          bigint,
  p_plan                text DEFAULT 'mensual',
  p_inscription_amount  numeric DEFAULT 0,
  p_monthly_amount      numeric DEFAULT 0,
  p_prolongado_fee      numeric DEFAULT 0,
  p_discount_pct        numeric DEFAULT 0,
  p_due_day             int     DEFAULT 5,
  p_months              int     DEFAULT 10,
  p_start_month         text    DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_role         text;
  v_start_month  text;
  v_discount     numeric;
  v_month_net    numeric;
  v_prolong_net  numeric;
  v_tot_net      numeric;
  v_charges      int := 0;
  v_payments     int := 0;
  v_i            int;
  v_month        text;
  v_due          date;
  v_half         int;
  v_sem_mes      text;
  v_insc_net     numeric;
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role NOT IN ('directora','asistente','admin') THEN
    RAISE EXCEPTION 'Acceso denegado: solo directora/asistente/admin pueden generar cargos';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.students WHERE id = p_student_id) THEN
    RAISE EXCEPTION 'El estudiante no existe';
  END IF;

  v_start_month := COALESCE(p_start_month, to_char(current_date, 'YYYY-MM'));
  v_discount    := GREATEST(0, LEAST(COALESCE(p_discount_pct,0), 100));
  v_month_net   := round(COALESCE(p_monthly_amount,0) * (1 - v_discount/100), 2);
  v_prolong_net := round(COALESCE(p_prolongado_fee,0) * (1 - v_discount/100), 2);

  -- Inscripción (cargo único)
  IF COALESCE(p_inscription_amount,0) > 0 THEN
    v_insc_net := round(p_inscription_amount * (1 - v_discount/100), 2);
    v_due := (date_trunc('month', current_date) + (p_due_day - 1) * interval '1 day')::date;
    INSERT INTO public.student_charges
      (student_id, concept, type, amount, discount_pct, amount_net, due_date, status, created_by)
    VALUES (p_student_id, 'Inscripción', 'inscripcion', p_inscription_amount, v_discount, v_insc_net, v_due, 'pending', auth.uid())
    ON CONFLICT DO NOTHING;
    INSERT INTO public.payments (student_id, amount, concept, status, due_date, created_at)
    VALUES (p_student_id, v_insc_net, 'Inscripción', 'pending', v_due, now())
    ON CONFLICT DO NOTHING;
    v_charges := v_charges + 1;
    v_payments := v_payments + 1;
  END IF;

  -- Mensualidades según plan
  IF p_plan = 'unico' THEN
    v_tot_net := v_month_net * GREATEST(p_months,1);
    v_due := (to_date(v_start_month || '-01','YYYY-MM-DD') + (p_due_day - 1) * interval '1 day')::date;
    INSERT INTO public.student_charges
      (student_id, concept, type, amount, discount_pct, amount_net, month_paid, due_date, status, created_by)
    VALUES (p_student_id, 'Cuota Única Anual', 'mensualidad',
            round(COALESCE(p_monthly_amount,0) * GREATEST(p_months,1),2), v_discount, v_tot_net,
            v_start_month, v_due, 'pending', auth.uid())
    ON CONFLICT DO NOTHING;
    INSERT INTO public.payments (student_id, amount, concept, status, due_date, created_at)
    VALUES (p_student_id, v_tot_net, 'Cuota Única Anual', 'pending', v_due, now())
    ON CONFLICT DO NOTHING;
    v_charges := v_charges + 1;
    v_payments := v_payments + 1;
  ELSIF p_plan = 'doble' THEN
    v_half := floor(GREATEST(p_months,1) / 2.0)::int;
    FOR v_i IN 0..1 LOOP
      v_sem_mes := to_char(date_trunc('month', to_date(v_start_month,'YYYY-MM')) + (v_i * v_half) * interval '1 month', 'YYYY-MM');
      v_tot_net := v_month_net * (GREATEST(p_months,1) - v_i * v_half);
      v_due := (to_date(v_sem_mes || '-01','YYYY-MM-DD') + (p_due_day - 1) * interval '1 day')::date;
      INSERT INTO public.student_charges
        (student_id, concept, type, amount, discount_pct, amount_net, month_paid, due_date, status, created_by)
      VALUES (p_student_id, CASE WHEN v_i = 0 THEN 'Semestre I' ELSE 'Semestre II' END, 'mensualidad',
              round(COALESCE(p_monthly_amount,0) * (GREATEST(p_months,1) - v_i * v_half),2), v_discount, v_tot_net,
              v_sem_mes, v_due, 'pending', auth.uid())
      ON CONFLICT DO NOTHING;
      INSERT INTO public.payments (student_id, amount, concept, status, due_date, created_at)
      VALUES (p_student_id, v_tot_net, CASE WHEN v_i = 0 THEN 'Semestre I' ELSE 'Semestre II' END, 'pending', v_due, now())
      ON CONFLICT DO NOTHING;
      v_charges := v_charges + 1;
      v_payments := v_payments + 1;
    END LOOP;
  ELSE
    FOR v_i IN 0 .. GREATEST(p_months,1)-1 LOOP
      v_month := to_char(date_trunc('month', to_date(v_start_month,'YYYY-MM')) + v_i * interval '1 month', 'YYYY-MM');
      v_due := (to_date(v_month || '-01','YYYY-MM-DD') + (p_due_day - 1) * interval '1 day')::date;
      INSERT INTO public.student_charges
        (student_id, concept, type, amount, discount_pct, amount_net, month_paid, due_date, status, created_by)
      VALUES (p_student_id, 'Mensualidad', 'mensualidad', COALESCE(p_monthly_amount,0), v_discount, v_month_net,
              v_month, v_due, 'pending', auth.uid())
      ON CONFLICT DO NOTHING;
      INSERT INTO public.payments (student_id, amount, concept, status, due_date, month_paid, created_at)
      VALUES (p_student_id, v_month_net, 'Mensualidad', 'pending', v_due, v_month, now())
      ON CONFLICT DO NOTHING;
      v_charges := v_charges + 1;
      v_payments := v_payments + 1;
    END LOOP;
  END IF;

  -- Día Prolongado (mensual, si aplica)
  IF v_prolong_net > 0 THEN
    FOR v_i IN 0 .. GREATEST(p_months,1)-1 LOOP
      v_month := to_char(date_trunc('month', to_date(v_start_month,'YYYY-MM')) + v_i * interval '1 month', 'YYYY-MM');
      v_due := (to_date(v_month || '-01','YYYY-MM-DD') + (p_due_day - 1) * interval '1 day')::date;
      INSERT INTO public.student_charges
        (student_id, concept, type, amount, discount_pct, amount_net, month_paid, due_date, status, created_by)
      VALUES (p_student_id, 'Día Prolongado', 'prolongado', COALESCE(p_prolongado_fee,0), v_discount, v_prolong_net,
              v_month, v_due, 'pending', auth.uid())
      ON CONFLICT DO NOTHING;
      INSERT INTO public.payments (student_id, amount, concept, status, due_date, month_paid, created_at)
      VALUES (p_student_id, v_prolong_net, 'Día Prolongado', 'pending', v_due, v_month, now())
      ON CONFLICT DO NOTHING;
      v_charges := v_charges + 1;
      v_payments := v_payments + 1;
    END LOOP;
  END IF;

  -- Mantener el motor de ciclo de pagos alineado con el plan del alumno
  UPDATE public.students
     SET monthly_fee   = COALESCE(p_monthly_amount, monthly_fee),
         prolongado_fee = COALESCE(p_prolongado_fee, prolongado_fee),
         due_day        = COALESCE(p_due_day, due_day),
         discount_pct   = v_discount,
         payment_plan   = p_plan
   WHERE id = p_student_id;

  RETURN jsonb_build_object('charges', v_charges, 'payments', v_payments,
    'plan', p_plan, 'start_month', v_start_month);
END;
$$;
GRANT EXECUTE ON FUNCTION public.generate_student_charges(bigint,text,numeric,numeric,numeric,numeric,int,int,text) TO authenticated;

-- ------------------------------------------------------------
-- 5. RPC: AFORO DE AULAS (ocupación vs capacidad)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_classrooms_capacity()
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
      'id', c.id, 'name', c.name, 'level', c.level, 'capacity', c.capacity,
      'occupied', (SELECT count(*)::int FROM public.students s
                   WHERE s.classroom_id = c.id AND s.is_active = true AND s.deleted_at IS NULL),
      'available', GREATEST(c.capacity - (SELECT count(*)::int FROM public.students s
                   WHERE s.classroom_id = c.id AND s.is_active = true AND s.deleted_at IS NULL), 0)
    ) ORDER BY c.name), '[]')
  FROM public.classrooms c;
$$;
GRANT EXECUTE ON FUNCTION public.get_classrooms_capacity() TO authenticated;

-- ------------------------------------------------------------
-- 6. RPC: TRANSICIONES DE ESTADO AUDITADAS
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.review_preregistration(
  p_id     bigint,
  p_status text,
  p_notes  text DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_role text;
  v_row  record;
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role NOT IN ('directora','asistente','admin') THEN
    RAISE EXCEPTION 'Acceso denegado: solo directora/asistente/admin pueden revisar preinscripciones';
  END IF;

  IF p_status NOT IN ('pending','reviewing','admitted','converted','rejected','expired') THEN
    RAISE EXCEPTION 'Estado inválido: %', p_status;
  END IF;

  UPDATE public.student_preregistrations
     SET status        = p_status,
         review_notes  = COALESCE(p_notes, review_notes),
         reviewed_by   = auth.uid(),
         reviewed_at   = now()
   WHERE id = p_id
   RETURNING * INTO v_row;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Preinscripción no encontrada';
  END IF;

  INSERT INTO public.audit_logs (user_id, action, payload, created_at)
  VALUES (auth.uid(), 'preregistration.' || p_status,
    jsonb_build_object('prereg_id', p_id, 'student_name', v_row.student_name, 'status', p_status),
    now());

  RETURN jsonb_build_object('id', p_id, 'status', p_status);
END;
$$;
GRANT EXECUTE ON FUNCTION public.review_preregistration(bigint,text,text) TO authenticated;

-- ------------------------------------------------------------
-- 7. ROW LEVEL SECURITY
-- ------------------------------------------------------------
ALTER TABLE public.payment_concepts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_preregistrations  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_charges           ENABLE ROW LEVEL SECURITY;

-- payment_concepts: público de lectura (precios dinámicos en el wizard), staff escribe
DROP POLICY IF EXISTS "payment_concepts_read" ON public.payment_concepts;
CREATE POLICY "payment_concepts_read" ON public.payment_concepts FOR SELECT
  USING (true);
DROP POLICY IF EXISTS "payment_concepts_staff" ON public.payment_concepts;
CREATE POLICY "payment_concepts_staff" ON public.payment_concepts FOR ALL
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('directora','asistente','admin')))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('directora','asistente','admin')));

-- student_preregistrations: anon inserta (formulario público), staff revisa
DROP POLICY IF EXISTS "prereg_insert_public" ON public.student_preregistrations;
CREATE POLICY "prereg_insert_public" ON public.student_preregistrations FOR INSERT TO anon
  WITH CHECK (true);
DROP POLICY IF EXISTS "prereg_insert_auth" ON public.student_preregistrations;
CREATE POLICY "prereg_insert_auth" ON public.student_preregistrations FOR INSERT TO authenticated
  WITH CHECK (true);
DROP POLICY IF EXISTS "prereg_staff" ON public.student_preregistrations;
CREATE POLICY "prereg_staff" ON public.student_preregistrations FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('directora','asistente','admin')));
DROP POLICY IF EXISTS "prereg_staff_update" ON public.student_preregistrations;
CREATE POLICY "prereg_staff_update" ON public.student_preregistrations FOR UPDATE
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('directora','asistente','admin')))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('directora','asistente','admin')));

-- student_charges: staff gestiona, padre lee los cargos de sus hijos
DROP POLICY IF EXISTS "charges_staff" ON public.student_charges;
CREATE POLICY "charges_staff" ON public.student_charges FOR ALL
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('directora','asistente','admin')))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('directora','asistente','admin')));
DROP POLICY IF EXISTS "charges_parent" ON public.student_charges;
CREATE POLICY "charges_parent" ON public.student_charges FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.students s WHERE s.id = student_charges.student_id AND s.parent_id = auth.uid()));

-- ------------------------------------------------------------
-- 8. GRANTS
-- ------------------------------------------------------------
GRANT SELECT ON public.payment_concepts TO anon, authenticated;
GRANT INSERT ON public.student_preregistrations TO anon, authenticated;
GRANT SELECT, UPDATE ON public.student_preregistrations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.student_charges TO authenticated;

GRANT USAGE, SELECT ON SEQUENCE public.student_preregistrations_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.student_charges_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.payment_concepts_id_seq TO authenticated;

-- ------------------------------------------------------------
-- 9. STORAGE: bucket público para documentos de preinscripción
-- ------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM storage.buckets WHERE id = 'preinscripcion-docs') THEN
    INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    VALUES ('preinscripcion-docs', 'preinscripcion-docs', true, 2097152,
            ARRAY['image/png','image/jpeg','image/webp','application/pdf']);
  END IF;
END $$;

DROP POLICY IF EXISTS "preinscripcion_docs_public_read" ON storage.objects;
CREATE POLICY "preinscripcion_docs_public_read" ON storage.objects FOR SELECT
  USING (bucket_id = 'preinscripcion-docs');
DROP POLICY IF EXISTS "preinscripcion_docs_public_insert" ON storage.objects;
CREATE POLICY "preinscripcion_docs_public_insert" ON storage.objects FOR INSERT TO anon, authenticated
  WITH CHECK (bucket_id = 'preinscripcion-docs');
DROP POLICY IF EXISTS "preinscripcion_docs_staff_delete" ON storage.objects;
CREATE POLICY "preinscripcion_docs_staff_delete" ON storage.objects FOR DELETE
  USING (bucket_id = 'preinscripcion-docs'
    AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('directora','asistente','admin')));
