-- Agrega soporte para respuestas a comentarios y notificaciones básicas
-- Ejecutar en Supabase SQL Editor

-- 1. parent_comment_id en comments
ALTER TABLE public.comments
  ADD COLUMN IF NOT EXISTS parent_comment_id bigint REFERENCES public.comments(id) ON DELETE CASCADE;

-- 2. Tabla de notificaciones del muro
CREATE TABLE IF NOT EXISTS public.wall_notifications (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  actor_id     uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_name   text,
  type         text NOT NULL CHECK (type IN ('reaction','comment','reply')),
  post_id      bigint REFERENCES public.posts(id) ON DELETE CASCADE,
  comment_id   bigint REFERENCES public.comments(id) ON DELETE CASCADE,
  message      text,
  read         boolean DEFAULT false,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

-- 3. Índices para performance
CREATE INDEX IF NOT EXISTS idx_wall_notif_user ON public.wall_notifications(user_id, read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_parent ON public.comments(parent_comment_id);

-- 4. RLS básico (ajustar según policies existentes)
ALTER TABLE public.wall_notifications ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'wall_notifications' AND policyname = 'Users see own notifications') THEN
    CREATE POLICY "Users see own notifications"
      ON public.wall_notifications FOR SELECT
      USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'wall_notifications' AND policyname = 'Authenticated insert notifications') THEN
    CREATE POLICY "Authenticated insert notifications"
      ON public.wall_notifications FOR INSERT
      WITH CHECK (auth.role() = 'authenticated');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'wall_notifications' AND policyname = 'Users mark own read') THEN
    CREATE POLICY "Users mark own read"
      ON public.wall_notifications FOR UPDATE
      USING (auth.uid() = user_id);
  END IF;
END $$;
