-- ============================================================
-- MIGRACIÓN: Configuración de Horarios de Eventos por Aula
-- Agrega tabla para guardar la configuración del timeline
-- y duración de cada evento del día escolar
-- ============================================================

-- 1. Tabla de configuración de horarios por aula
CREATE TABLE IF NOT EXISTS public.classroom_event_schedule (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id    bigint REFERENCES public.classrooms(id) ON DELETE CASCADE NOT NULL,
  event_type      text NOT NULL,
  event_label     text NOT NULL,
  event_icon      text DEFAULT '⏰',
  scheduled_hour   smallint NOT NULL CHECK (scheduled_hour >= 0 AND scheduled_hour <= 23),
  scheduled_minute smallint NOT NULL DEFAULT 0 CHECK (scheduled_minute >= 0 AND scheduled_minute <= 59),
  duration_minutes smallint DEFAULT 30 CHECK (duration_minutes > 0 AND duration_minutes <= 480),
  is_active       boolean DEFAULT true,
  auto_register   boolean DEFAULT false,
  applies_to      text DEFAULT 'all' CHECK (applies_to IN ('all', 'infant', 'standard')),
  sort_order      smallint DEFAULT 0,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  updated_at      timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(classroom_id, event_type)
);

-- 2. Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_event_schedule_classroom ON public.classroom_event_schedule(classroom_id);
CREATE INDEX IF NOT EXISTS idx_event_schedule_active ON public.classroom_event_schedule(is_active);

-- 3. Tabla de registros de eventos del timeline (quién registró qué, cuándo, a quiénes)
CREATE TABLE IF NOT EXISTS public.timeline_event_log (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id    bigint REFERENCES public.classrooms(id) ON DELETE CASCADE NOT NULL,
  event_type      text NOT NULL,
  registered_by   uuid REFERENCES public.profiles(id),
  target_students bigint[] DEFAULT '{}',
  student_count   smallint DEFAULT 0,
  scheduled_time  time,
  actual_time     time DEFAULT CURRENT_TIME,
  duration_minutes smallint,
  metadata        jsonb DEFAULT '{}'::jsonb,
  created_at      timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_timeline_log_classroom_date ON public.timeline_event_log(classroom_id, created_at);

-- 4. Columna events en daily_logs (si no existe)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'daily_logs' AND column_name = 'events'
  ) THEN
    ALTER TABLE public.daily_logs ADD COLUMN events jsonb DEFAULT '[]'::jsonb;
  END IF;
END $$;

-- 5. Datos iniciales por defecto (se ejecuta solo si la tabla está vacía para un aula)
-- La inserción se hace desde JS al crear un aula nueva

-- 6. Función para obtener el schedule del día de un aula
CREATE OR REPLACE FUNCTION get_classroom_schedule(p_classroom_id bigint)
RETURNS TABLE (
  event_type    text,
  event_label   text,
  event_icon    text,
  sched_hour    smallint,
  sched_minute  smallint,
  duration_min  smallint,
  auto_register boolean,
  applies_to    text
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    s.event_type, s.event_label, s.event_icon,
    s.scheduled_hour, s.scheduled_minute,
    s.duration_minutes, s.auto_register, s.applies_to
  FROM public.classroom_event_schedule s
  WHERE s.classroom_id = p_classroom_id AND s.is_active = true
  ORDER BY s.sort_order, s.scheduled_hour, s.scheduled_minute;
END;
$$ LANGUAGE plpgsql STABLE;

-- 7. Función para registrar evento en el timeline
CREATE OR REPLACE FUNCTION log_timeline_event(
  p_classroom_id bigint,
  p_event_type   text,
  p_registered_by uuid,
  p_target_students bigint[],
  p_scheduled_time time DEFAULT NULL,
  p_duration_minutes smallint DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
) RETURNS void AS $$
BEGIN
  INSERT INTO public.timeline_event_log (
    classroom_id, event_type, registered_by, target_students,
    student_count, scheduled_time, actual_time, duration_minutes, metadata
  ) VALUES (
    p_classroom_id, p_event_type, p_registered_by, p_target_students,
    array_length(p_target_students, 1), p_scheduled_time,
    CURRENT_TIME, p_duration_minutes, p_metadata
  );
END;
$$ LANGUAGE plpgsql;

-- 8. RLS para classroom_event_schedule
ALTER TABLE public.classroom_event_schedule ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Maestras ven schedule de su aula"
  ON public.classroom_event_schedule FOR SELECT
  USING (
    classroom_id IN (
      SELECT id FROM public.classrooms WHERE teacher_id = auth.uid()
    )
  );

CREATE POLICY "Maestras gestionan schedule de su aula"
  ON public.classroom_event_schedule FOR ALL
  USING (
    classroom_id IN (
      SELECT id FROM public.classrooms WHERE teacher_id = auth.uid()
    )
  );

-- 9. RLS para timeline_event_log
ALTER TABLE public.timeline_event_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Maestras ven logs de su aula"
  ON public.timeline_event_log FOR SELECT
  USING (
    classroom_id IN (
      SELECT id FROM public.classrooms WHERE teacher_id = auth.uid()
    )
  );

CREATE POLICY "Maestras insertan logs en su aula"
  ON public.timeline_event_log FOR INSERT
  WITH CHECK (
    classroom_id IN (
      SELECT id FROM public.classrooms WHERE teacher_id = auth.uid()
    )
  );

-- 10. Políticas para padres (solo lectura de logs de hijos)
CREATE POLICY "Padres ven logs de hijos"
  ON public.timeline_event_log FOR SELECT
  USING (
    classroom_id IN (
      SELECT classroom_id FROM public.students WHERE parent_id = auth.uid()
    )
  );
