-- Karpus Kids - Esquema de Base de Datos para Supabase (Postgres)
-- ARQUITECTURA FINAL KARPUS KIDS (Supabase Auth + RLS)
-- Versión Corregida y Optimizada con Sistema de Notificaciones

-- -----------------------------------------------------------------------------
-- 🚀 QUICK FIXES: Run these if you get 400 Bad Request errors (Missing columns)
-- -----------------------------------------------------------------------------
-- alter table public.daily_logs add column if not exists activities text;
-- alter table public.tasks add column if not exists teacher_id uuid references public.profiles(id);
-- alter table public.tasks add column if not exists grading_system text default 'letter_stars';
-- -----------------------------------------------------------------------------
-- 📦 STORAGE BUCKETS:
-- 1. Create a public bucket named 'task_files' in Supabase Storage.
-- -----------------------------------------------------------------------------

-- 1. TABLAS PRINCIPALES
-- -----------------------------------------------------------------------------

-- 1.1 Perfiles (Usuarios del sistema)
create table if not exists public.profiles (
  id uuid not null references auth.users(id) on delete cascade primary key,
  email text unique,
  name text,
  role text check (role in ('directora', 'maestra', 'padre', 'asistente')),
  avatar_url text,
  phone text,
  notes text,
  bio text, -- Nueva columna para biografía/presentación
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('directora','maestra','padre','asistente'));

-- 1.2 Aulas
create table if not exists public.classrooms (
  id bigint generated by default as identity primary key,
  name text not null,
  level text,
  capacity integer default 20,
  teacher_id uuid references public.profiles(id) on delete set null, -- Maestra asignada
  is_live boolean default false, -- Estado de videollamada activa
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- FIX: Asegurar que la columna is_live exista para evitar errores 400
alter table public.classrooms add column if not exists is_live boolean default false;

-- 1.3 Estudiantes
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  classroom_id bigint references public.classrooms(id) on delete set null,
  parent_id uuid references public.profiles(id),
  is_active boolean default true,
  avatar_url text,
  matricula text, -- Corrección para error de API: column students.matricula does not exist
  
  -- Información Adicional (Padres y Datos Médicos)
  p1_name text,
  p1_phone text,
  p1_email text,
  p1_job text,
  p1_address text,
  p1_emergency_contact text,
  p2_name text,
  p2_phone text,
  p2_email text,
  p2_job text,
  p2_address text,
  p2_emergency_contact text,
  start_date date,
  allergies text,
  blood_type text,
  authorized_pickup text,
  monthly_fee numeric default 0,
  due_day integer default 5,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.4 Asistencia
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  classroom_id bigint references public.classrooms(id),
  date date default current_date,
  status text check (status in ('present', 'absent', 'late')),
  check_in timestamp with time zone,
  check_out timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(student_id, date)
);

-- FIX: Asegurar que existan las columnas de tiempo para evitar error 400 en API
alter table public.attendance add column if not exists check_in timestamp with time zone;
alter table public.attendance add column if not exists check_out timestamp with time zone;

-- 1.4.1 Solicitudes de Ausencia (Padres)
create table if not exists public.attendance_requests (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  date date not null,
  reason text not null,
  note text,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.attendance_requests enable row level security;

-- 1.5 Tareas (Tasks)
-- Aseguramos que exista la tabla de tareas mencionada en el código JS
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  teacher_id uuid references public.profiles(id),
  title text not null,
  description text,
  due_date timestamp with time zone,
  file_url text,
  grading_system text default 'letter_stars',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.5.1 Evidencias de Tareas (Entregas de padres)
create table if not exists public.task_evidences (
  id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(id) on delete cascade,
  student_id bigint references public.students(id) on delete cascade,
  parent_id uuid references public.profiles(id),
  file_url text,
  comment text,
  status text default 'submitted', -- submitted, graded
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Ajuste: calificación por letra y estrellas
alter table public.task_evidences add column if not exists grade_letter text;
alter table public.task_evidences add column if not exists stars integer;

-- 1.6 Publicaciones (Muro)
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  teacher_id uuid references public.profiles(id),
  content text,
  media_url text,
  media_type text, -- 'image', 'video', 'document'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add missing columns for Wall/Forum functionality
alter table public.posts add column if not exists title text;
alter table public.posts add column if not exists image_url text;
alter table public.posts add column if not exists likes_count integer default 0;
alter table public.posts add column if not exists comments_count integer default 0;
alter table public.posts add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now());

-- Optimización: Guardar datos de la maestra en el post para evitar problemas de RLS y joins
alter table public.posts add column if not exists teacher_name text;
alter table public.posts add column if not exists teacher_avatar text;

-- Trigger para autocompletar datos de maestra en nuevos posts
create or replace function public.handle_new_post_teacher_info()
returns trigger
language plpgsql
security definer
as $$
begin
  if new.teacher_id is not null then
    select name, avatar_url
    into new.teacher_name, new.teacher_avatar
    from public.profiles
    where id = new.teacher_id;
  end if;

  return new;
end;
$$;

drop trigger if exists on_new_post_populate_teacher on public.posts;
create trigger on_new_post_populate_teacher
before insert on public.posts
for each row execute function public.handle_new_post_teacher_info();

-- Triggers para mantener contadores actualizados
create or replace function public.update_post_comments_count()
returns trigger
language plpgsql
security definer
as $$
begin
  if TG_OP = 'INSERT' then
    update public.posts set comments_count = comments_count + 1 where id = NEW.post_id;
    return NEW;
  elsif TG_OP = 'DELETE' then
    update public.posts set comments_count = greatest(0, comments_count - 1) where id = OLD.post_id;
    return OLD;
  end if;
  return null;
end;
$$;

drop trigger if exists on_comment_change_update_count on public.comments;
create trigger on_comment_change_update_count
after insert or delete on public.comments
for each row execute function public.update_post_comments_count();

create or replace function public.update_post_likes_count()
returns trigger
language plpgsql
security definer
as $$
begin
  if TG_OP = 'INSERT' then
    update public.posts set likes_count = likes_count + 1 where id = NEW.post_id;
    return NEW;
  elsif TG_OP = 'DELETE' then
    update public.posts set likes_count = greatest(0, likes_count - 1) where id = OLD.post_id;
    return OLD;
  end if;
  return null;
end;
$$;

drop trigger if exists on_like_change_update_count on public.likes;
create trigger on_like_change_update_count
after insert or delete on public.likes
for each row execute function public.update_post_likes_count();

-- 1.7 Comentarios
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Optimization for Wall: Store user name in comments to avoid extra joins/fetches
alter table public.comments add column if not exists user_name text;

-- 1.7.1 Mensajería Directa (Chat tipo Facebook)
-- 🔥 ARQUITECTURA CHAT PROFESIONAL (Conversaciones + Participantes + Mensajes)
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  type text default 'private', -- 'private' o 'group'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.conversation_participants (
  conversation_id bigint references public.conversations(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key(conversation_id, user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations(id) on delete cascade not null,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_read boolean default false
);

-- Ensure conversation_id column exists (for migration from old schema)
alter table public.messages add column if not exists conversation_id bigint references public.conversations(id) on delete cascade;

-- 1.8 Likes
create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  reaction_type text default 'like', -- 'like', 'love', 'haha', etc.
  unique(post_id, user_id)
);

-- 1.9 NOTIFICACIONES (NUEVO SISTEMA)
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  message text not null,
  type text default 'info', -- 'info', 'post', 'alert', 'grade'
  link text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.12 Chat de Aula (Videollamada)
create table if not exists public.classroom_chat (
  id bigint generated by default as identity primary key,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.10 Calificaciones (Grades)
create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  classroom_id bigint references public.classrooms(id),
  subject text not null, -- Matemáticas, Lenguaje, etc.
  score numeric(5,2),
  period text, -- Trimestre 1, etc.
  teacher_id uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create unique index if not exists grades_unique_student_subject_period
  on public.grades (student_id, subject, period);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  amount numeric(10,2) not null,
  concept text default 'Mensualidad',
  status text default 'pending' check (status in ('pending', 'paid', 'overdue', 'review')),
  due_date date,
  paid_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Fix old schema where concept may be missing
alter table public.payments add column if not exists concept text default 'Mensualidad';

-- Fix old constraint if it exists with wrong values
alter table public.payments drop constraint if exists payments_status_check;

-- Evitar duplicados de pagos mensuales (un pago por student_id/month_paid/due_date/concept)
create unique index if not exists idx_payments_unique_student_month_due on public.payments(student_id, month_paid, due_date, concept);

-- Fix 400 Error: Missing columns in payments
alter table public.payments add column if not exists month_paid text;
alter table public.payments add column if not exists method text;
alter table public.payments add column if not exists bank text;
alter table public.payments add column if not exists reference text;
alter table public.payments add column if not exists transfer_date date;
alter table public.payments add column if not exists proof_url text;
alter table public.payments add column if not exists evidence_url text; -- Alias for compatibility
alter table public.payments add column if not exists due_date date;

-- Ensure monthly_fee exists in students
alter table public.students add column if not exists monthly_fee numeric default 0;
alter table public.students add column if not exists due_day integer default 5;

-- 1.13 Incidentes (Reportes de conducta)
create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  teacher_id uuid references public.profiles(id),
  severity text check (severity in ('leve', 'media', 'alta')),
  status text default 'received' check (status in ('received', 'review', 'resolved', 'archived')),
  description text,
  reported_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.14 Rutina Diaria (Daily Logs) - Fix 404 daily_logs
create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  date date default current_date,
  mood text,
  food text,
  nap text,
  eating text,    -- Nueva columna (para compatibilidad)
  sleeping text,  -- Nueva columna (para compatibilidad)
  activities text, -- Nueva columna (para compatibilidad)
  notes text,     -- Nueva columna (para compatibilidad)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(student_id, date)
);

-- 1.15 Galería del Aula - Fix 404 classroom_gallery
create table if not exists public.classroom_gallery (
  id bigint generated by default as identity primary key,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  image_url text not null,
  caption text,
  date date default current_date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. SEGURIDAD (Row Level Security)
-- -----------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.classrooms enable row level security;
alter table public.students enable row level security;
alter table public.attendance enable row level security;
alter table public.tasks enable row level security;
alter table public.task_evidences enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.likes enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.classroom_chat enable row level security;
alter table public.grades enable row level security;
alter table public.payments enable row level security;
alter table public.incidents enable row level security;
alter table public.daily_logs enable row level security;
alter table public.classroom_gallery enable row level security;

-- 3. FUNCIONES AUXILIARES
-- -----------------------------------------------------------------------------

-- Función segura para obtener rol (evita recursión)
create or replace function public.get_my_role()
RETURNS text
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  select role from profiles where id = auth.uid() limit 1;
$$;

-- Funciones para romper recursión RLS
create or replace function public.is_teacher_of_classroom(p_classroom_id bigint)
returns boolean language sql security definer stable as $$
  select exists (select 1 from public.classrooms where id = p_classroom_id and teacher_id = auth.uid());
$$;

create or replace function public.is_parent_of_student(p_student_id bigint)
returns boolean language sql security definer stable as $$
  select exists (select 1 from public.students where id = p_student_id and parent_id = auth.uid());
$$;

create or replace function public.is_parent_of_classroom(p_classroom_id bigint)
returns boolean language sql security definer stable as $$
  select exists (select 1 from public.students where classroom_id = p_classroom_id and parent_id = auth.uid());
$$;

create or replace function public.is_teacher_of_student(p_student_id bigint)
returns boolean language sql security definer stable as $$
  select exists (
    select 1 from public.students s
    join public.classrooms c on c.id = s.classroom_id
    where s.id = p_student_id and c.teacher_id = auth.uid()
  );
$$;

-- Función para manejar nuevos usuarios (Trigger Auth)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'name',
    coalesce(new.raw_user_meta_data->>'role', 'padre')
  );
  return new;
end;
$$;

-- Función RPC para generar cuotas mensuales
-- Utiliza transacciones para asegurar integridad de datos
create or replace function public.generate_monthly_charges(p_month integer, p_year integer)
returns json language plpgsql security definer set search_path = public
as $$
declare
  v_student record;
  v_due_date date;
  v_created_count integer := 0;
  v_existing_count integer := 0;
  v_total_amount numeric := 0;
begin
  -- Validar parámetros
  if p_month < 1 or p_month > 12 then
    raise exception 'Mes inválido: debe estar entre 1 y 12';
  end if;

  if p_year < 2020 or p_year > 2050 then
    raise exception 'Año inválido: debe estar entre 2020 y 2050';
  end if;

  -- Calcular fecha de vencimiento (día del estudiante o día 5 por defecto)
  -- Para simplificar, usaremos el día 5 de cada mes
  v_due_date := make_date(p_year, p_month, 5);

  -- Iterar sobre todos los estudiantes activos con tarifa mensual
  for v_student in
    select id, name, monthly_fee, due_day
    from public.students
    where is_active = true
      and monthly_fee > 0
  loop
    -- Verificar si ya existe una cuota para este estudiante en este mes/año
    if not exists (
      select 1 from public.payments
      where student_id = v_student.id
        and extract(month from due_date) = p_month
        and extract(year from due_date) = p_year
    ) then
      -- Insertar nueva cuota
      insert into public.payments (
        student_id,
        amount,
        status,
        due_date,
        created_at
      ) values (
        v_student.id,
        v_student.monthly_fee,
        'pending',
        v_due_date,
        now()
      );

      v_created_count := v_created_count + 1;
      v_total_amount := v_total_amount + v_student.monthly_fee;
    else
      v_existing_count := v_existing_count + 1;
    end if;
  end loop;

  -- Retornar resultado
  return json_build_object(
    'success', true,
    'created_count', v_created_count,
    'existing_count', v_existing_count,
    'total_amount', v_total_amount,
    'month', p_month,
    'year', p_year,
    'due_date', v_due_date
  );

exception
  when others then
    -- En caso de error, hacer rollback automático
    return json_build_object(
      'success', false,
      'error', SQLERRM,
      'created_count', 0,
      'existing_count', 0,
      'total_amount', 0
    );
end;
$$;

-- Trigger para la función anterior
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4. POLÍTICAS DE ACCESO (RLS)
-- -----------------------------------------------------------------------------

-- PROFILES
drop policy if exists "Directora y Asistente ven todos los perfiles" on public.profiles;
create policy "Directora y Asistente ven todos los perfiles" on public.profiles for select using (
  get_my_role() in ('directora', 'asistente')
);

-- Allow authenticated users to view basic profile info (needed for social feed avatars/names)
drop policy if exists "Ver perfiles basicos" on public.profiles;
create policy "Ver perfiles basicos" on public.profiles for select using (
  auth.role() = 'authenticated'
);

-- Permitir que cualquiera (padres) vea los perfiles del staff (para saber quién publica)
drop policy if exists "Ver perfiles de staff" on public.profiles;
create policy "Ver perfiles de staff" on public.profiles for select using (
  role in ('maestra', 'directora', 'asistente')
);

drop policy if exists "Usuarios ven su propio perfil" on public.profiles;
create policy "Usuarios ven su propio perfil" on public.profiles for select using (
  auth.uid() = id
);

drop policy if exists "Editar propio perfil" on public.profiles;
create policy "Editar propio perfil" on public.profiles for update using (auth.uid() = id);

drop policy if exists "Insertar propio perfil" on public.profiles;
create policy "Insertar propio perfil" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Directora y Asistente insertan perfiles" on public.profiles;
create policy "Directora y Asistente insertan perfiles" on public.profiles for insert with check (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Directora y Asistente editan perfiles" on public.profiles;
create policy "Directora y Asistente editan perfiles" on public.profiles for update using (
  get_my_role() in ('directora', 'asistente')
);

-- DATA FIX: corregir rol de asistente creado como padre
update public.profiles set role = 'asistente' where id = 'b9eaa8f4-5e53-4079-b01d-92a4c1707553';

-- CLASSROOMS
drop policy if exists "Directora y Asistente gestionan aulas" on public.classrooms;
create policy "Directora y Asistente gestionan aulas" on public.classrooms for all using (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Maestra ve sus aulas" on public.classrooms;
create policy "Maestra ve sus aulas" on public.classrooms for select using (
  teacher_id = auth.uid()
);

-- ✅ NUEVA POLÍTICA: Permitir a los padres ver el aula de sus hijos
drop policy if exists "Padres ven aula de sus hijos" on public.classrooms;
create policy "Padres ven aula de sus hijos" on public.classrooms for select using (
  is_parent_of_classroom(id)
);

-- STUDENTS
-- Función auxiliar SECURITY DEFINER para evitar recursión infinita en RLS
create or replace function public.get_my_classroom_ids()
returns setof bigint
language sql
security definer
stable
set search_path = public
as $$
  select classroom_id from public.students where parent_id = auth.uid() and classroom_id is not null;
$$;

drop policy if exists "Directora y Asistente gestionan estudiantes" on public.students;
create policy "Directora y Asistente gestionan estudiantes" on public.students for all using (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Maestra ve estudiantes de sus aulas" on public.students;
create policy "Maestra ve estudiantes de sus aulas" on public.students for select using (
  is_teacher_of_student(id)
);

drop policy if exists "Padres ven sus hijos" on public.students;
create policy "Padres ven sus hijos" on public.students for select using (parent_id = auth.uid());

drop policy if exists "Padres actualizan datos hijo" on public.students;
create policy "Padres actualizan datos hijo" on public.students for update
  using (parent_id = auth.uid())
  with check (parent_id = auth.uid());

drop policy if exists "Padres ven compañeros de aula" on public.students;
create policy "Padres ven compañeros de aula"
on public.students for select
using (
  classroom_id in (select public.get_my_classroom_ids())
);

-- ATTENDANCE
drop policy if exists "Directora y Asistente ven asistencia" on public.attendance;
create policy "Directora y Asistente ven asistencia" on public.attendance for select using (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Maestra registra asistencia" on public.attendance;
create policy "Maestra registra asistencia" on public.attendance for all using (
  is_teacher_of_classroom(classroom_id)
);

-- ATTENDANCE REQUESTS
drop policy if exists "Padres envian solicitudes de ausencia" on public.attendance_requests;
create policy "Padres envian solicitudes de ausencia" on public.attendance_requests for insert with check (
  is_parent_of_student(student_id)
);

drop policy if exists "Padres ven sus solicitudes de ausencia" on public.attendance_requests;
create policy "Padres ven sus solicitudes de ausencia" on public.attendance_requests for select using (
  is_parent_of_student(student_id)
);

drop policy if exists "Staff ve todas las solicitudes de ausencia" on public.attendance_requests;
create policy "Staff ve todas las solicitudes de ausencia" on public.attendance_requests for all using (
  get_my_role() in ('directora', 'asistente', 'maestra')
);

-- TASKS
drop policy if exists "Maestras ven tareas de sus aulas" on public.tasks;
create policy "Maestras ven tareas de sus aulas" on public.tasks for select using (
  is_teacher_of_classroom(classroom_id)
);

drop policy if exists "Maestras crean tareas" on public.tasks;
create policy "Maestras crean tareas" on public.tasks for insert with check (
  is_teacher_of_classroom(classroom_id)
);

drop policy if exists "Maestras actualizan tareas" on public.tasks;
create policy "Maestras actualizan tareas" on public.tasks for update using (
  is_teacher_of_classroom(classroom_id)
);

drop policy if exists "Padres ven tareas del aula de su hijo" on public.tasks;
create policy "Padres ven tareas del aula de su hijo" on public.tasks for select using (
  is_parent_of_classroom(classroom_id)
);

-- TASK EVIDENCES
drop policy if exists "Padres suben evidencias" on public.task_evidences;
create policy "Padres suben evidencias" on public.task_evidences for insert with check (auth.uid() = parent_id);
drop policy if exists "Padres ven sus evidencias" on public.task_evidences;
create policy "Padres ven sus evidencias" on public.task_evidences for select using (auth.uid() = parent_id);
drop policy if exists "Maestras ven evidencias de sus aulas" on public.task_evidences;
create policy "Maestras ven evidencias de sus aulas" on public.task_evidences for select using (
  exists (
    select 1
    from public.tasks t
    where t.id = public.task_evidences.task_id
      and is_teacher_of_classroom(t.classroom_id)
  )
);
drop policy if exists "Maestras califican evidencias" on public.task_evidences;
create policy "Maestras califican evidencias" on public.task_evidences for update using (
  exists (
    select 1
    from public.tasks t
    where t.id = public.task_evidences.task_id
      and is_teacher_of_classroom(t.classroom_id)
  )
);

-- POSTS & COMMENTS
drop policy if exists "Ver posts" on public.posts;
create policy "Ver posts" on public.posts
for select using (
  get_my_role() in ('directora','asistente')
  or is_teacher_of_classroom(classroom_id)
  or is_parent_of_classroom(classroom_id)
);

drop policy if exists "Maestras crean posts" on public.posts;
create policy "Maestras crean posts" on public.posts for insert with check (
  get_my_role() in ('directora', 'asistente', 'maestra')
);

-- COMMENTS
drop policy if exists "Usuarios ven comentarios de posts visibles" on public.comments;
create policy "Usuarios ven comentarios de posts visibles"
on public.comments
for select
using (
  exists (
    select 1 from posts p
    where p.id = comments.post_id
    and (
      get_my_role() in ('directora','asistente')
      or is_teacher_of_classroom(p.classroom_id) 
      or is_parent_of_classroom(p.classroom_id)
    )
  )
);

drop policy if exists "Usuarios comentan en publicaciones visibles" on public.comments;
create policy "Usuarios comentan en publicaciones visibles"
on public.comments
for insert
with check (
  exists (
    select 1 from posts p
    where p.id = comments.post_id
    and (is_teacher_of_classroom(p.classroom_id) or is_parent_of_classroom(p.classroom_id))
  )
);

drop policy if exists "Usuarios eliminan sus comentarios" on public.comments;
create policy "Usuarios eliminan sus comentarios" on public.comments for delete using (auth.uid() = user_id);

-- POSTS (UPDATE/DELETE)
drop policy if exists "Maestras actualizan sus posts" on public.posts;
create policy "Maestras actualizan sus posts" on public.posts
for update using (
  get_my_role() in ('directora', 'asistente') or auth.uid() = teacher_id
);

drop policy if exists "Maestras eliminan sus posts" on public.posts;
create policy "Maestras eliminan sus posts" on public.posts
for delete using (
  get_my_role() in ('directora', 'asistente') or auth.uid() = teacher_id
);


-- LIKES
drop policy if exists "Ver likes" on public.likes;
create policy "Ver likes"
on public.likes
for select
using (
  exists (
    select 1
    from posts p
    where p.id = likes.post_id
    and (
      get_my_role() in ('directora','asistente')
      or is_teacher_of_classroom(p.classroom_id)
      or is_parent_of_classroom(p.classroom_id)
    )
  )
);

drop policy if exists "Usuarios reaccionan a posts visibles" on public.likes;
create policy "Usuarios reaccionan a posts visibles"
on public.likes
for insert
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from posts p
    where p.id = likes.post_id
    and (is_teacher_of_classroom(p.classroom_id) or is_parent_of_classroom(p.classroom_id))
  )
);

drop policy if exists "Padres pueden quitar like" on public.likes;
create policy "Padres pueden quitar like" on public.likes for delete using (auth.uid() = user_id);

-- MESSAGES
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  type text default 'private', -- private, group
  name text,
  created_at timestamp with time zone default now()
);

create table if not exists public.conversation_participants (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  joined_at timestamp with time zone default now(),
  unique(conversation_id, user_id)
);

-- Asegurar que la tabla messages tenga conversation_id
alter table public.messages add column if not exists conversation_id bigint references public.conversations(id) on delete cascade;
alter table public.messages add column if not exists sender_id uuid references public.profiles(id);
alter table public.messages add column if not exists receiver_id uuid references public.profiles(id); -- Legacy support
alter table public.messages add column if not exists is_read boolean default false;

alter table public.messages enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;

drop policy if exists "Usuarios ven sus conversaciones" on public.conversations;
create policy "Usuarios ven sus conversaciones" on public.conversations for select using (
  exists (
    select 1 from conversation_participants cp
    where cp.conversation_id = conversations.id
    and cp.user_id = auth.uid()
  )
);

drop policy if exists "Usuarios ven sus participaciones" on public.conversation_participants;
create policy "Usuarios ven sus participaciones" on public.conversation_participants for select using (
  user_id = auth.uid()
);

drop policy if exists "Usuarios ven sus mensajes" on public.messages;
create policy "Usuarios ven sus mensajes" on public.messages for select using (
  exists (
    select 1 from conversation_participants cp
    where cp.conversation_id = messages.conversation_id
    and cp.user_id = auth.uid()
  )
  or sender_id = auth.uid()
  or receiver_id = auth.uid()
);

drop policy if exists "Usuarios envian mensajes" on public.messages;
create policy "Usuarios envian mensajes" on public.messages for insert with check (
  auth.uid() = sender_id or auth.role() = 'authenticated'
);

drop policy if exists "Usuarios actualizan mensajes" on public.messages;
create policy "Usuarios actualizan mensajes" on public.messages for update using (
  auth.uid() = sender_id or auth.role() = 'authenticated'
);


-- PAYMENTS
drop policy if exists "Directora ve todos los pagos" on public.payments;
create policy "Directora ve todos los pagos" on public.payments for all using (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Padres ven sus pagos" on public.payments;
create policy "Padres ven sus pagos" on public.payments for select using (
  is_parent_of_student(student_id)
);

drop policy if exists "Padres registran pagos" on public.payments;
create policy "Padres registran pagos" on public.payments for insert with check (
  is_parent_of_student(student_id)
);

-- NOTIFICATIONS
drop policy if exists "Usuarios ven sus notificaciones" on public.notifications;
create policy "Usuarios ven sus notificaciones" on public.notifications for select using (
  auth.uid() = user_id
);

drop policy if exists "Sistema crea notificaciones" on public.notifications;
create policy "Sistema crea notificaciones"
on public.notifications
for insert
with check (auth.role() = 'authenticated');

-- 1.11 Inquietudes (Inquiries - Comunicación Padres-Directora)
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  parent_id uuid references public.profiles(id) not null,
  student_id bigint references public.students(id), -- Opcional, para contexto
  subject text,
  message text not null,
  response text,
  status text default 'pending', -- pending, resolved
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  responded_at timestamp with time zone
);

-- Fix 400 Error: Missing columns in inquiries
alter table public.inquiries add column if not exists priority text default 'medium';
alter table public.inquiries add column if not exists folio text;
alter table public.inquiries add column if not exists updated_at timestamp with time zone;
alter table public.inquiries add column if not exists attachment_url text;

alter table public.inquiries enable row level security;

drop policy if exists "Directora ve todas las inquietudes" on public.inquiries;
create policy "Directora ve todas las inquietudes" on public.inquiries for all using (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Padres ven sus inquietudes" on public.inquiries;
create policy "Padres ven sus inquietudes" on public.inquiries for select using (
  auth.uid() = parent_id
);

drop policy if exists "Padres crean inquietudes" on public.inquiries;
create policy "Padres crean inquietudes" on public.inquiries for insert with check (
  auth.uid() = parent_id
);

drop policy if exists "Usuarios marcan leida" on public.notifications;
create policy "Usuarios marcan leida" on public.notifications for update using (
  auth.uid() = user_id
);

-- CLASSROOM CHAT
drop policy if exists "Ver chat aula" on public.classroom_chat;
create policy "Ver chat aula" on public.classroom_chat for select using (
  is_teacher_of_classroom(classroom_id) or is_parent_of_classroom(classroom_id)
);
drop policy if exists "Enviar chat aula" on public.classroom_chat;
create policy "Enviar chat aula" on public.classroom_chat for insert with check (auth.uid() = user_id);

-- INCIDENTS
drop policy if exists "Maestras crean incidentes" on public.incidents;
create policy "Maestras crean incidentes" on public.incidents for insert with check (auth.uid() = teacher_id);

drop policy if exists "Ver incidentes" on public.incidents;
create policy "Ver incidentes" on public.incidents for select using (
  auth.uid() = teacher_id OR get_my_role() in ('directora', 'asistente') OR is_parent_of_student(student_id)
);

-- DAILY LOGS & GALLERY POLICIES
drop policy if exists "Maestras gestionan daily_logs" on public.daily_logs;
create policy "Maestras gestionan daily_logs" on public.daily_logs for all using (
  is_teacher_of_classroom(classroom_id)
);

drop policy if exists "Maestras gestionan galeria" on public.classroom_gallery;
create policy "Maestras gestionan galeria" on public.classroom_gallery for all using (
  is_teacher_of_classroom(classroom_id)
);
drop policy if exists "Padres ven galeria" on public.classroom_gallery;
create policy "Padres ven galeria" on public.classroom_gallery for select using (
  is_parent_of_classroom(classroom_id)
);

-- 1. RPC: Reporte Financiero Mensual por Aula (Optimizado para gráficas)
create or replace function public.get_monthly_financial_report_by_classroom(p_month text)
returns table (
  classroom_name text,
  total_expected numeric,
  total_paid numeric,
  total_pending numeric
)
language plpgsql
security definer
as $$
begin
  return query
  select 
    c.name as classroom_name,
    coalesce(sum(p.amount), 0) as total_expected,
    coalesce(sum(case when p.status = 'paid' or p.status = 'efectivo' then p.amount else 0 end), 0) as total_paid,
    coalesce(sum(case when p.status = 'pending' then p.amount else 0 end), 0) as total_pending
  from classrooms c
  left join students s on s.classroom_id = c.id
  left join payments p on p.student_id = s.id and p.month_paid = p_month
  group by c.name
  order by c.name;
end;
$$;

-- 2. RPC: KPIs del Dashboard (Todos los contadores en una sola llamada)
create or replace function public.get_dashboard_kpis()
returns jsonb
language plpgsql
security definer
as $$
declare
  v_total_students int;
  v_total_teachers int;
  v_active_classrooms int;
  v_attendance_today int;
  v_pending_payments numeric;
  v_active_incidents int;
begin
  select count(*) into v_total_students from students where is_active = true;
  select count(*) into v_total_teachers from profiles where role = 'maestra';
  select count(*) into v_active_classrooms from classrooms;
  select count(*) into v_attendance_today from attendance where date = current_date and status = 'present';
  select coalesce(sum(amount), 0) into v_pending_payments from payments where status = 'pending';
  select count(*) into v_active_incidents from inquiries where status = 'pending';

  return jsonb_build_object(
    'total_students', v_total_students,
    'total_teachers', v_total_teachers,
    'active_classrooms', v_active_classrooms,
    'attendance_today', v_attendance_today,
    'pending_payments', v_pending_payments,
    'active_incidents', v_active_incidents
  );
end;
$$;

-- 1.15 Tabla de Eventos del Sistema (Arquitectura Event-Driven)
create table if not exists public.system_events (
  id uuid default gen_random_uuid() primary key,
  type text not null,
  payload jsonb,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  processed_at timestamp with time zone
);

-- RLS para system_events
alter table public.system_events enable row level security;
drop policy if exists "Staff ve eventos" on public.system_events;
create policy "Staff ve eventos"
on public.system_events
for select
using (
  exists (
    select 1
    from profiles
    where id = auth.uid()
    and role in ('directora','asistente','maestra')
  )
);
drop policy if exists "Cualquier autenticado puede insertar eventos" on public.system_events;
create policy "Cualquier autenticado puede insertar eventos" on public.system_events
  for insert with check (auth.role() = 'authenticated');

-- 4. TRIGGER: Notificar al padre sobre nuevo cargo
create or replace function public.notify_parent_on_new_charge()
returns trigger
language plpgsql
security definer
as $$
declare
  v_parent_id uuid;
  v_student_name text;
begin
  -- Solo notificar si el estado es 'pending' (generado por sistema o manual pendiente)
  if new.status = 'pending' then
    select parent_id, name into v_parent_id, v_student_name
    from public.students
    where id = new.student_id;

    if v_parent_id is not null then
      insert into public.notifications (user_id, title, message, type, link)
      values (
        v_parent_id,
        'Nuevo Cargo Generado',
        'Se ha generado un cargo de $' || new.amount || ' para ' || v_student_name || ' (' || coalesce(new.month_paid, 'Mensualidad') || ').',
        'alert',
        'panel_padres.html#payments'
      );
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists on_new_payment_charge on public.payments;
create trigger on_new_payment_charge
after insert on public.payments
for each row execute function public.notify_parent_on_new_charge();

-- 3. RPC: Calcular Deuda Total de Estudiante
create or replace function public.get_student_total_debt(p_student_id bigint)
returns numeric
language plpgsql
security definer
as $$
declare
  v_debt numeric;
begin
  select coalesce(sum(amount), 0) into v_debt
  from public.payments
  where student_id = p_student_id
    and status = 'pending';
  
  return v_debt;
end;
$$;

-- 5. RPC: Enviar Notificación Interna
-- Esta función es llamada por la Edge Function send-push
DROP FUNCTION IF EXISTS public.send_notification(uuid, text, text, text, text);
CREATE OR REPLACE FUNCTION public.send_notification(
  p_user_id uuid,
  p_title text,
  p_message text,
  p_type text DEFAULT 'info',
  p_link text DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.notifications (user_id, title, message, type, link)
  VALUES (p_user_id, p_title, p_message, p_type, p_link);
  RETURN true;
EXCEPTION WHEN OTHERS THEN
  RETURN false;
END;
$$;


-- Actualización de la función RPC para aceptar filtro de mes
create or replace function public.get_dashboard_kpis(p_month text)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_total_students int;
  v_total_teachers int;
  v_active_classrooms int;
  v_attendance_today int;
  v_pending_payments numeric;
  v_active_incidents int;
begin
  -- Contadores generales
  select count(*) into v_total_students from students where is_active = true;
  select count(*) into v_total_teachers from profiles where role = 'maestra';
  select count(*) into v_active_classrooms from classrooms;
  
  -- Asistencia de hoy (Métrica en tiempo real)
  select count(*) into v_attendance_today from attendance where date = current_date and status = 'present';
  
  -- Pagos Pendientes (Filtrado por mes seleccionado)
  -- Si el mes no coincide, no suma al KPI de "deuda del mes"
  select coalesce(sum(amount), 0) into v_pending_payments 
  from payments 
  where status = 'pending' 
  and month_paid ilike p_month;

  -- Incidencias activas
  select count(*) into v_active_incidents from inquiries where status = 'pending';

  return jsonb_build_object(
    'total_students', v_total_students,
    'total_teachers', v_total_teachers,
    'active_classrooms', v_active_classrooms,
    'attendance_today', v_attendance_today,
    'pending_payments', v_pending_payments,
    'active_incidents', v_active_incidents
  );
end;
$$;

-- 6. ÍNDICES PARA MEJORA DE RENDIMIENTO
-- -----------------------------------------------------------------------------
create index if not exists idx_students_parent on public.students(parent_id);
create index if not exists idx_students_classroom on public.students(classroom_id);
create index if not exists idx_posts_classroom on public.posts(classroom_id);
create index if not exists idx_comments_post on public.comments(post_id);
create index if not exists idx_likes_post on public.likes(post_id);
create index if not exists idx_messages_sender on public.messages(sender_id);
create index if not exists idx_messages_conversation on public.messages(conversation_id);
create index if not exists idx_payments_student on public.payments(student_id);

-- 7. RPCs CHAT OPTIMIZADO
-- -----------------------------------------------------------------------------

-- Obtener mensajes de chat directo (privado) entre usuario autenticado y otro usuario
create or replace function public.get_direct_messages(p_other_user_id uuid)
returns table (
  id bigint,
  content text,
  sender_id uuid,
  created_at timestamp with time zone,
  is_read boolean,
  conversation_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_conv_id bigint;
begin
  -- Buscar conversación privada compartida
  select c.id into v_conv_id
  from conversations c
  join conversation_participants cp1 on c.id = cp1.conversation_id
  join conversation_participants cp2 on c.id = cp2.conversation_id
  where c.type = 'private'
    and cp1.user_id = auth.uid()
    and cp2.user_id = p_other_user_id
  limit 1;

  if v_conv_id is not null then
    return query
    select m.id, m.content, m.sender_id, m.created_at, m.is_read, m.conversation_id
    from messages m
    where m.conversation_id = v_conv_id
    order by m.created_at asc;
  end if;
end;
$$;

-- Obtener conteo de mensajes no leídos por remitente
create or replace function public.get_unread_counts()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_object_agg(sender_id, count)
  from (
    select m.sender_id, count(*) as count
    from messages m
    join conversation_participants cp on cp.conversation_id = m.conversation_id
    where cp.user_id = auth.uid()
      and m.sender_id != auth.uid()
      and m.is_read = false
    group by m.sender_id
  ) t;
$$;

-- Marcar mensajes como leídos en una conversación
create or replace function public.mark_conversation_read(p_conversation_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update messages
  set is_read = true
  where conversation_id = p_conversation_id
    and sender_id != auth.uid()
    and is_read = false;
$$;

-- 8. RPCs DASHBOARD DIRECTORA
-- -----------------------------------------------------------------------------

-- 📊 RPC: Tendencia de asistencia últimos 7 días
create or replace function public.attendance_last_7_days()
returns table (
  date date,
  present integer,
  absent integer,
  late integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    a.date,
    count(*) filter (where a.status = 'present') as present,
    count(*) filter (where a.status = 'absent') as absent,
    count(*) filter (where a.status = 'late') as late
  from attendance a
  where a.date >= current_date - interval '7 days'
    and a.date <= current_date
  group by a.date
  order by a.date desc;
$$;

-- 💰 RPC: Resumen financiero del mes
create or replace function public.financial_summary_month(
  p_year integer default extract(year from now())::integer,
  p_month integer default extract(month from now())::integer
)
returns table (
  total_invoiced numeric,
  total_paid numeric,
  total_pending numeric,
  percentagePaid numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(sum(amount), 0)::numeric as total_invoiced,
    coalesce(sum(amount) filter (where status = 'paid'), 0)::numeric as total_paid,
    coalesce(sum(amount) filter (where status = 'pending'), 0)::numeric as total_pending,
    case
      when coalesce(sum(amount), 0) > 0 
      then round((coalesce(sum(amount) filter (where status = 'paid'), 0) / sum(amount)) * 100, 2)
      else 0
    end::numeric as percentagePaid
  from payments
  where extract(year from due_date) = p_year
    and extract(month from due_date) = p_month;
$$;


-- Verificar que RPCs existen
SELECT routine_name FROM information_schema.routines 
WHERE routine_name IN ('attendance_last_7_days', 'financial_summary_month');

-- Prueba rápida
SELECT * FROM attendance_last_7_days() LIMIT 5;
SELECT * FROM financial_summary_month();

-- Agregar columna images si no existe
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS images TEXT[] DEFAULT '{}';

-- (Opcional) Migrar datos antiguos si tenías image_url antes
-- UPDATE public.posts SET images = ARRAY[image_url] WHERE image_url IS NOT NULL AND images = '{}';
-- ALTER TABLE public.posts DROP COLUMN IF EXISTS image_url;
-- 1. TABLA DE CONFIGURACIÓN GLOBAL
create table if not exists public.school_settings (
  id int primary key default 1, -- Singleton pattern
  generation_day int default 25,
  due_day int default 5,
  updated_at timestamp with time zone default now()
);

-- RLS para settings
alter table public.school_settings enable row level security;
drop policy if exists "Solo directores editan config" on public.school_settings;
create policy "Solo directores editan config" on public.school_settings 
  for all using (get_my_role() in ('directora', 'admin'));

-- 2. FUNCIÓN INTELIGENTE: CICLO DE PAGOS (El Cerebro)
-- Esta función hace 3 cosas:
-- A. Genera pagos del próximo mes si hoy es >= día de generación
-- B. Marca como VENCIDOS los pagos pendientes que pasaron el día límite
-- C. Retorna estadísticas de lo que hizo
create or replace function public.run_payment_cycle()
returns jsonb
language plpgsql
security definer
as $$
declare
  v_settings record;
  v_today int := extract(day from current_date);
  v_next_month int;
  v_next_year int;
  v_gen_count int := 0;
  v_expire_count int := 0;
  v_student record;
  v_target_date date;
begin
  -- Obtener configuración
  select * into v_settings from public.school_settings where id = 1;
  if not found then
    -- Usar una tabla temporal o valores fijos para asegurar que los campos existan
    return jsonb_build_object('error', 'No se encontró la configuración en school_settings con id = 1');
  end if;

  -- A. GENERACIÓN DE CUOTAS (Si es día de generación o posterior)
  if v_today >= v_settings.generation_day then
    v_next_month := extract(month from current_date) + 1;
    v_next_year := extract(year from current_date);
    
    if v_next_month > 12 then
      v_next_month := 1;
      v_next_year := v_next_year + 1;
    end if;
    
    v_target_date := make_date(v_next_year, v_next_month, v_settings.due_day);

    -- Loop para generar (Solo si no existe ya)
    for v_student in select id, monthly_fee from public.students where is_active = true and monthly_fee > 0 loop
      if not exists (
        select 1 from public.payments 
        where student_id = v_student.id 
        and (
          (extract(month from due_date) = v_next_month and extract(year from due_date) = v_next_year)
          or month_paid = to_char(v_target_date, 'FMMonth')
        )
      ) then
        insert into public.payments (student_id, amount, status, due_date, month_paid)
        values (v_student.id, v_student.monthly_fee, 'pending', v_target_date, to_char(v_target_date, 'FMMonth'));
        v_gen_count := v_gen_count + 1;
      end if;
    end loop;
  end if;

  -- B. VENCIMIENTO DE PAGOS (Inteligente)
  -- Busca pagos 'pending' o 'review' cuya fecha límite ya pasó
  with updated_rows as (
    update public.payments
    set status = 'overdue'
    where status in ('pending') 
    and due_date < current_date
    returning 1
  )
  select count(*) into v_expire_count from updated_rows;

  return jsonb_build_object('generated', v_gen_count, 'expired', v_expire_count);
end;
$$;

-- 🛠️ CORRECCIONES DE SCHEMA PARA EVITAR ERRORES 400

-- 1. Arreglar tabla TASKS (Error al guardar tarea)
-- Agrega las columnas que el JS está enviando pero la DB no tiene
ALTER TABLE public.tasks 
ADD COLUMN IF NOT EXISTS teacher_id uuid references public.profiles(id),
ADD COLUMN IF NOT EXISTS grading_system text DEFAULT 'letter_stars',
ADD COLUMN IF NOT EXISTS file_url text;

-- 2. Arreglar tabla DAILY_LOGS (Error al guardar rutina)
-- Asegura compatibilidad entre 'sleeping' y 'nap'
ALTER TABLE public.daily_logs
ADD COLUMN IF NOT EXISTS nap text,
ADD COLUMN IF NOT EXISTS eating text,
ADD COLUMN IF NOT EXISTS sleeping text, -- Agregamos sleeping para que no falle si el JS lo envía
ADD COLUMN IF NOT EXISTS activities text,
ADD COLUMN IF NOT EXISTS notes text; -- 🔥 FIX: Agregar columna notes solicitada

-- 3. Arreglar permisos (Por si acaso es un error 403 disfrazado)
GRANT ALL ON public.tasks TO authenticated;
GRANT ALL ON public.daily_logs TO authenticated;

-- 4. Asegurar tabla de incidencias
ALTER TABLE public.incidents
ADD COLUMN IF NOT EXISTS teacher_id uuid references public.profiles(id);