-- Karpus Kids - Esquema de Base de Datos para Supabase (Postgres)
-- ARQUITECTURA FINAL KARPUS KIDS (Supabase Auth + RLS)
-- Versión Corregida y Optimizada con Sistema de Notificaciones

-- 1. TABLAS PRINCIPALES
-- -----------------------------------------------------------------------------

-- 1.1 Perfiles (Usuarios del sistema)
create table if not exists public.profiles (
  id uuid not null references auth.users(id) on delete cascade primary key,
  email text unique,
  name text,
  role text check (role in ('directora', 'maestra', 'padre', 'asistente')),
  avatar_url text,
  phone text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('directora','maestra','padre','asistente'));

-- 1.2 Aulas
create table if not exists public.classrooms (
  id bigint generated by default as identity primary key,
  name text not null,
  level text,
  capacity integer default 20,
  teacher_id uuid references public.profiles(id) on delete set null, -- Maestra asignada
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.3 Estudiantes
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  classroom_id bigint references public.classrooms(id) on delete set null,
  parent_id uuid references public.profiles(id),
  is_active boolean default true,
  avatar_url text,
  
  -- Información Adicional (Padres y Datos Médicos)
  p1_name text,
  p1_phone text,
  p1_email text,
  p1_job text,
  p1_address text,
  p1_emergency_contact text,
  p2_name text,
  p2_phone text,
  p2_email text,
  p2_job text,
  p2_address text,
  p2_emergency_contact text,
  start_date date,
  allergies text,
  blood_type text,
  authorized_pickup text,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.4 Asistencia
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  classroom_id bigint references public.classrooms(id),
  date date default current_date,
  status text check (status in ('present', 'absent', 'late')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(student_id, date)
);

-- 1.5 Tareas (Tasks)
-- Aseguramos que exista la tabla de tareas mencionada en el código JS
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  title text not null,
  description text,
  due_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.5.1 Evidencias de Tareas (Entregas de padres)
create table if not exists public.task_evidences (
  id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(id) on delete cascade,
  student_id bigint references public.students(id) on delete cascade,
  parent_id uuid references public.profiles(id),
  file_url text,
  comment text,
  status text default 'submitted', -- submitted, graded
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.6 Publicaciones (Muro)
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  teacher_id uuid references public.profiles(id),
  content text,
  media_url text,
  media_type text, -- 'image', 'video', 'document'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.7 Comentarios
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.8 Likes
create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(post_id, user_id)
);

-- 1.9 NOTIFICACIONES (NUEVO SISTEMA)
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  message text not null,
  type text default 'info', -- 'info', 'post', 'alert', 'grade'
  link text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.10 Calificaciones (Grades)
create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  classroom_id bigint references public.classrooms(id),
  subject text not null, -- Matemáticas, Lenguaje, etc.
  score numeric(5,2),
  period text, -- Trimestre 1, etc.
  teacher_id uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. SEGURIDAD (Row Level Security)
-- -----------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.classrooms enable row level security;
alter table public.students enable row level security;
alter table public.attendance enable row level security;
alter table public.tasks enable row level security;
alter table public.task_evidences enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.likes enable row level security;
alter table public.notifications enable row level security;
alter table public.grades enable row level security;

-- 3. FUNCIONES AUXILIARES
-- -----------------------------------------------------------------------------

-- Función segura para obtener rol (evita recursión)
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS text
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$;

-- Función para manejar nuevos usuarios (Trigger Auth)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'name',
    coalesce(new.raw_user_meta_data->>'role', 'padre')
  );
  return new;
end;
$$;

-- 4. POLÍTICAS DE ACCESO (RLS)
-- -----------------------------------------------------------------------------

-- PROFILES
drop policy if exists "Directora ve todos los perfiles" on public.profiles;
create policy "Directora ve todos los perfiles" on public.profiles for select using (
  get_my_role() = 'directora'
);

drop policy if exists "Usuarios ven su propio perfil" on public.profiles;
create policy "Usuarios ven su propio perfil" on public.profiles for select using (
  auth.uid() = id
);

drop policy if exists "Editar propio perfil" on public.profiles;
create policy "Editar propio perfil" on public.profiles for update using (auth.uid() = id);

drop policy if exists "Insertar propio perfil" on public.profiles;
create policy "Insertar propio perfil" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Directora edita perfiles" on public.profiles;
create policy "Directora edita perfiles" on public.profiles for update using (
  get_my_role() = 'directora'
);

-- DATA FIX: corregir rol de asistente creado como padre
update public.profiles set role = 'asistente' where id = 'b9eaa8f4-5e53-4079-b01d-92a4c1707553';

-- CLASSROOMS
drop policy if exists "Directora gestiona aulas" on public.classrooms;
create policy "Directora gestiona aulas" on public.classrooms for all using (
  get_my_role() = 'directora'
);

drop policy if exists "Maestra ve sus aulas" on public.classrooms;
create policy "Maestra ve sus aulas" on public.classrooms for select using (
  teacher_id = auth.uid() OR get_my_role() = 'directora'
);

-- STUDENTS
drop policy if exists "Directora gestiona estudiantes" on public.students;
create policy "Directora gestiona estudiantes" on public.students for all using (
  get_my_role() = 'directora'
);

drop policy if exists "Maestra ve estudiantes de sus aulas" on public.students;
create policy "Maestra ve estudiantes de sus aulas" on public.students for select using (
  exists (select 1 from public.classrooms c where c.id = students.classroom_id and c.teacher_id = auth.uid())
);

drop policy if exists "Padres ven sus hijos" on public.students;
create policy "Padres ven sus hijos" on public.students for select using (parent_id = auth.uid());

-- ATTENDANCE
drop policy if exists "Directora ve asistencia" on public.attendance;
create policy "Directora ve asistencia" on public.attendance for select using (
  get_my_role() = 'directora'
);

drop policy if exists "Maestra registra asistencia" on public.attendance;
create policy "Maestra registra asistencia" on public.attendance for all using (
  exists (select 1 from public.classrooms c where c.id = attendance.classroom_id and c.teacher_id = auth.uid())
);

-- TASK EVIDENCES
drop policy if exists "Padres suben evidencias" on public.task_evidences;
create policy "Padres suben evidencias" on public.task_evidences for insert with check (auth.uid() = parent_id);
drop policy if exists "Padres ven sus evidencias" on public.task_evidences;
create policy "Padres ven sus evidencias" on public.task_evidences for select using (auth.uid() = parent_id);

-- POSTS & COMMENTS
drop policy if exists "Ver posts" on public.posts;
create policy "Ver posts" on public.posts for select using (true); -- Ajustar según privacidad deseada

drop policy if exists "Maestras crean posts" on public.posts;
create policy "Maestras crean posts" on public.posts for insert with check (auth.uid() = teacher_id);

-- LIKES
drop policy if exists "Ver likes" on public.likes;
create policy "Ver likes" on public.likes for select using (true);

drop policy if exists "Padres pueden dar like" on public.likes;
create policy "Padres pueden dar like" on public.likes for insert with check (auth.uid() = user_id);

drop policy if exists "Padres pueden quitar like" on public.likes;
create policy "Padres pueden quitar like" on public.likes for delete using (auth.uid() = user_id);

-- NOTIFICATIONS
drop policy if exists "Usuarios ven sus notificaciones" on public.notifications;
create policy "Usuarios ven sus notificaciones" on public.notifications for select using (
  auth.uid() = user_id
);

drop policy if exists "Usuarios marcan leida" on public.notifications;
create policy "Usuarios marcan leida" on public.notifications for update using (
  auth.uid() = user_id
);

-- GRADES
drop policy if exists "Padres ven notas de sus hijos" on public.grades;
create policy "Padres ven notas de sus hijos" on public.grades for select using (
  exists (select 1 from public.students s where s.id = grades.student_id and s.parent_id = auth.uid())
);

-- 5. FUNCIONALIDAD DE NOTIFICACIONES (PUSH DB)
-- -----------------------------------------------------------------------------

-- Función para enviar notificaciones (invocable desde SQL o triggers)
CREATE OR REPLACE FUNCTION public.send_notification(
    p_user_id uuid,
    p_title text,
    p_message text,
    p_type text DEFAULT 'info',
    p_link text DEFAULT null
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.notifications (user_id, title, message, type, link)
    VALUES (p_user_id, p_title, p_message, p_type, p_link);
END;
$$;

-- Trigger: Notificar a padres cuando hay nuevo post en su aula
CREATE OR REPLACE FUNCTION public.notify_new_post_func()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    parent_rec RECORD;
BEGIN
    -- Seleccionar todos los padres con hijos en el aula del post
    FOR parent_rec IN 
        SELECT DISTINCT parent_id 
        FROM public.students 
        WHERE classroom_id = NEW.classroom_id AND parent_id IS NOT NULL
    LOOP
        -- Enviar notificación a cada padre
        PERFORM public.send_notification(
            parent_rec.parent_id,
            'Nueva publicación en el aula',
            left(NEW.content, 50) || '...',
            'post',
            '/panel_padres.html' -- O link dinámico
        );
    END LOOP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_new_post_notify ON public.posts;
CREATE TRIGGER on_new_post_notify
    AFTER INSERT ON public.posts
    FOR EACH ROW
    EXECUTE PROCEDURE public.notify_new_post_func();

-- 6. TRIGGERS DE SISTEMA
-- -----------------------------------------------------------------------------
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 7. STORAGE
-- -----------------------------------------------------------------------------
insert into storage.buckets (id, name, public) values ('classroom_media', 'classroom_media', true) on conflict do nothing;

drop policy if exists "Public Access Media" on storage.objects;
create policy "Public Access Media" on storage.objects for select using ( bucket_id = 'classroom_media' );

drop policy if exists "Teachers Upload Media" on storage.objects;
create policy "Teachers Upload Media" on storage.objects for insert with check ( bucket_id = 'classroom_media' and auth.role() = 'authenticated' );

insert into storage.buckets (id, name, public) values ('payments_evidence', 'payments_evidence', true) on conflict do nothing;
drop policy if exists "Public Access Payments" on storage.objects;
create policy "Public Access Payments" on storage.objects for select using ( bucket_id = 'payments_evidence' );
drop policy if exists "Auth Upload Payments" on storage.objects;
create policy "Auth Upload Payments" on storage.objects for insert with check ( bucket_id = 'payments_evidence' and auth.role() = 'authenticated' );

-- 8. PAYMENTS
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  amount numeric not null,
  month_paid text,
  method text check (method in ('transferencia','efectivo')),
  bank text,
  reference text,
  transfer_date date,
  evidence_url text,
  status text check (status in ('pendiente','confirmado','rechazado','efectivo')) default 'pendiente',
  recorded_by uuid references public.profiles(id),
  validated_by uuid references public.profiles(id),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.payments enable row level security;
drop policy if exists "Directora ve pagos" on public.payments;
create policy "Directora ve pagos" on public.payments for select using ( get_my_role() = 'directora' );
drop policy if exists "Asistente ve pagos" on public.payments;
create policy "Asistente ve pagos" on public.payments for select using ( get_my_role() = 'asistente' );
drop policy if exists "Padre ve sus pagos" on public.payments;
create policy "Padre ve sus pagos" on public.payments for select using (
  exists (select 1 from public.students s where s.id = payments.student_id and s.parent_id = auth.uid())
);
drop policy if exists "Insert pagos padres/asistente/directora" on public.payments;
create policy "Insert pagos padres/asistente/directora" on public.payments for insert with check (
  get_my_role() in ('directora','asistente') OR exists (select 1 from public.students s where s.id = payments.student_id and s.parent_id = auth.uid())
);
drop policy if exists "Validar pagos" on public.payments;
create policy "Validar pagos" on public.payments for update using ( get_my_role() in ('directora','asistente') );

create table if not exists public.payment_reminders (
  id bigint generated by default as identity primary key,
  day_of_month integer check (day_of_month >= 1 and day_of_month <= 28),
  message text,
  created_by uuid references public.profiles(id),
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.payment_reminders enable row level security;
drop policy if exists "Asistente gestiona recordatorios" on public.payment_reminders;
create policy "Asistente gestiona recordatorios" on public.payment_reminders for all using ( get_my_role() in ('asistente','directora') );
