-- Karpus Kids - Esquema de Base de Datos para Supabase (Postgres)
-- ARQUITECTURA FINAL KARPUS KIDS (Supabase Auth + RLS)
-- Versión Corregida y Optimizada con Sistema de Notificaciones

-- 1. TABLAS PRINCIPALES
-- -----------------------------------------------------------------------------

-- 1.1 Perfiles (Usuarios del sistema)
create table if not exists public.profiles (
  id uuid not null references auth.users(id) on delete cascade primary key,
  email text unique,
  name text,
  role text check (role in ('directora', 'maestra', 'padre', 'asistente')),
  avatar_url text,
  phone text,
  notes text,
  bio text, -- Nueva columna para biografía/presentación
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('directora','maestra','padre','asistente'));

-- 1.2 Aulas
create table if not exists public.classrooms (
  id bigint generated by default as identity primary key,
  name text not null,
  level text,
  capacity integer default 20,
  teacher_id uuid references public.profiles(id) on delete set null, -- Maestra asignada
  is_live boolean default false, -- Estado de videollamada activa
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.3 Estudiantes
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  classroom_id bigint references public.classrooms(id) on delete set null,
  parent_id uuid references public.profiles(id),
  is_active boolean default true,
  avatar_url text,
  
  -- Información Adicional (Padres y Datos Médicos)
  p1_name text,
  p1_phone text,
  p1_email text,
  p1_job text,
  p1_address text,
  p1_emergency_contact text,
  p2_name text,
  p2_phone text,
  p2_email text,
  p2_job text,
  p2_address text,
  p2_emergency_contact text,
  start_date date,
  allergies text,
  blood_type text,
  authorized_pickup text,
  monthly_fee numeric default 0,
  due_day integer default 5,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.4 Asistencia
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  classroom_id bigint references public.classrooms(id),
  date date default current_date,
  status text check (status in ('present', 'absent', 'late')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(student_id, date)
);

-- 1.5 Tareas (Tasks)
-- Aseguramos que exista la tabla de tareas mencionada en el código JS
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  title text not null,
  description text,
  due_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Ajuste: adjunto opcional en la tarea (foto/video/pdf)
alter table public.tasks add column if not exists file_url text;

-- 1.5.1 Evidencias de Tareas (Entregas de padres)
create table if not exists public.task_evidences (
  id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(id) on delete cascade,
  student_id bigint references public.students(id) on delete cascade,
  parent_id uuid references public.profiles(id),
  file_url text,
  comment text,
  status text default 'submitted', -- submitted, graded
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Ajuste: calificación por letra y estrellas
alter table public.task_evidences add column if not exists grade_letter text;
alter table public.task_evidences add column if not exists stars integer;

-- 1.6 Publicaciones (Muro)
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  teacher_id uuid references public.profiles(id),
  content text,
  media_url text,
  media_type text, -- 'image', 'video', 'document'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.7 Comentarios
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.8 Likes
create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(post_id, user_id)
);

-- 1.9 NOTIFICACIONES (NUEVO SISTEMA)
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  message text not null,
  type text default 'info', -- 'info', 'post', 'alert', 'grade'
  link text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.12 Chat de Aula (Videollamada)
create table if not exists public.classroom_chat (
  id bigint generated by default as identity primary key,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.10 Calificaciones (Grades)
create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  classroom_id bigint references public.classrooms(id),
  subject text not null, -- Matemáticas, Lenguaje, etc.
  score numeric(5,2),
  period text, -- Trimestre 1, etc.
  teacher_id uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create unique index if not exists grades_unique_student_subject_period
  on public.grades (student_id, subject, period);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  amount numeric(10,2) not null,
  concept text not null,
  status text default 'pending',
  due_date date,
  paid_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Fix 400 Error: Missing columns in payments
alter table public.payments add column if not exists month_paid text;
alter table public.payments add column if not exists method text;
alter table public.payments add column if not exists proof_url text;
alter table public.payments add column if not exists evidence_url text; -- Alias for compatibility

-- 1.13 Incidentes (Reportes de conducta)
create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  teacher_id uuid references public.profiles(id),
  severity text check (severity in ('leve', 'media', 'alta')),
  description text,
  reported_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.14 Rutina Diaria (Daily Logs) - Fix 404 daily_logs
create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete cascade,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  date date default current_date,
  mood text,
  food text,
  nap text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(student_id, date)
);

-- 1.15 Galería del Aula - Fix 404 classroom_gallery
create table if not exists public.classroom_gallery (
  id bigint generated by default as identity primary key,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  image_url text not null,
  caption text,
  date date default current_date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. SEGURIDAD (Row Level Security)
-- -----------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.classrooms enable row level security;
alter table public.students enable row level security;
alter table public.attendance enable row level security;
alter table public.tasks enable row level security;
alter table public.task_evidences enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.likes enable row level security;
alter table public.notifications enable row level security;
alter table public.classroom_chat enable row level security;
alter table public.grades enable row level security;
alter table public.payments enable row level security;
alter table public.incidents enable row level security;
alter table public.daily_logs enable row level security;
alter table public.classroom_gallery enable row level security;

-- 3. FUNCIONES AUXILIARES
-- -----------------------------------------------------------------------------

-- Función segura para obtener rol (evita recursión)
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS text
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$;

-- Función para manejar nuevos usuarios (Trigger Auth)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'name',
    coalesce(new.raw_user_meta_data->>'role', 'padre')
  );
  return new;
end;
$$;

-- 4. POLÍTICAS DE ACCESO (RLS)
-- -----------------------------------------------------------------------------

-- PROFILES
drop policy if exists "Directora y Asistente ven todos los perfiles" on public.profiles;
create policy "Directora y Asistente ven todos los perfiles" on public.profiles for select using (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Usuarios ven su propio perfil" on public.profiles;
create policy "Usuarios ven su propio perfil" on public.profiles for select using (
  auth.uid() = id
);

drop policy if exists "Editar propio perfil" on public.profiles;
create policy "Editar propio perfil" on public.profiles for update using (auth.uid() = id);

drop policy if exists "Insertar propio perfil" on public.profiles;
create policy "Insertar propio perfil" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Directora y Asistente insertan perfiles" on public.profiles;
create policy "Directora y Asistente insertan perfiles" on public.profiles for insert with check (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Directora y Asistente editan perfiles" on public.profiles;
create policy "Directora y Asistente editan perfiles" on public.profiles for update using (
  get_my_role() in ('directora', 'asistente')
);

-- DATA FIX: corregir rol de asistente creado como padre
update public.profiles set role = 'asistente' where id = 'b9eaa8f4-5e53-4079-b01d-92a4c1707553';

-- CLASSROOMS
drop policy if exists "Directora y Asistente gestionan aulas" on public.classrooms;
create policy "Directora y Asistente gestionan aulas" on public.classrooms for all using (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Maestra ve sus aulas" on public.classrooms;
create policy "Maestra ve sus aulas" on public.classrooms for select using (
  teacher_id = auth.uid() OR get_my_role() in ('directora', 'asistente')
);

-- STUDENTS
drop policy if exists "Directora y Asistente gestionan estudiantes" on public.students;
create policy "Directora y Asistente gestionan estudiantes" on public.students for all using (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Maestra ve estudiantes de sus aulas" on public.students;
create policy "Maestra ve estudiantes de sus aulas" on public.students for select using (
  exists (select 1 from public.classrooms c where c.id = students.classroom_id and c.teacher_id = auth.uid())
);

drop policy if exists "Padres ven sus hijos" on public.students;
create policy "Padres ven sus hijos" on public.students for select using (parent_id = auth.uid());

drop policy if exists "Padres actualizan datos hijo" on public.students;
create policy "Padres actualizan datos hijo" on public.students for update
  using (parent_id = auth.uid())
  with check (parent_id = auth.uid());

-- ATTENDANCE
drop policy if exists "Directora y Asistente ven asistencia" on public.attendance;
create policy "Directora y Asistente ven asistencia" on public.attendance for select using (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Maestra registra asistencia" on public.attendance;
create policy "Maestra registra asistencia" on public.attendance for all using (
  exists (select 1 from public.classrooms c where c.id = attendance.classroom_id and c.teacher_id = auth.uid())
);

-- TASKS
drop policy if exists "Maestras ven tareas de sus aulas" on public.tasks;
create policy "Maestras ven tareas de sus aulas" on public.tasks for select using (
  exists (
    select 1
    from public.classrooms c
    where c.id = public.tasks.classroom_id
      and c.teacher_id = auth.uid()
  )
);

drop policy if exists "Maestras crean tareas" on public.tasks;
create policy "Maestras crean tareas" on public.tasks for insert with check (
  exists (
    select 1
    from public.classrooms c
    where c.id = public.tasks.classroom_id
      and c.teacher_id = auth.uid()
  )
);

drop policy if exists "Maestras actualizan tareas" on public.tasks;
create policy "Maestras actualizan tareas" on public.tasks for update using (
  exists (
    select 1
    from public.classrooms c
    where c.id = public.tasks.classroom_id
      and c.teacher_id = auth.uid()
  )
);

drop policy if exists "Padres ven tareas del aula de su hijo" on public.tasks;
create policy "Padres ven tareas del aula de su hijo" on public.tasks for select using (
  exists (
    select 1
    from public.students s
    where s.parent_id = auth.uid()
      and s.classroom_id = public.tasks.classroom_id
  )
);

-- TASK EVIDENCES
drop policy if exists "Padres suben evidencias" on public.task_evidences;
create policy "Padres suben evidencias" on public.task_evidences for insert with check (auth.uid() = parent_id);
drop policy if exists "Padres ven sus evidencias" on public.task_evidences;
create policy "Padres ven sus evidencias" on public.task_evidences for select using (auth.uid() = parent_id);
drop policy if exists "Maestras ven evidencias de sus aulas" on public.task_evidences;
create policy "Maestras ven evidencias de sus aulas" on public.task_evidences for select using (
  exists (
    select 1
    from public.tasks t
    join public.classrooms c on c.id = t.classroom_id
    where t.id = public.task_evidences.task_id
      and c.teacher_id = auth.uid()
  )
);
drop policy if exists "Maestras califican evidencias" on public.task_evidences;
create policy "Maestras califican evidencias" on public.task_evidences for update using (
  exists (
    select 1
    from public.tasks t
    join public.classrooms c on c.id = t.classroom_id
    where t.id = public.task_evidences.task_id
      and c.teacher_id = auth.uid()
  )
);

-- POSTS & COMMENTS
drop policy if exists "Ver posts" on public.posts;
create policy "Ver posts" on public.posts for select using (true); -- Ajustar según privacidad deseada

drop policy if exists "Maestras crean posts" on public.posts;
create policy "Maestras crean posts" on public.posts for insert with check (auth.uid() = teacher_id);

-- COMMENTS
drop policy if exists "Authenticated users can comment" on public.comments;
create policy "Authenticated users can comment" on public.comments for insert with check (auth.role() = 'authenticated');

-- LIKES
drop policy if exists "Ver likes" on public.likes;
create policy "Ver likes" on public.likes for select using (true);

drop policy if exists "Padres pueden dar like" on public.likes;
create policy "Padres pueden dar like" on public.likes for insert with check (auth.uid() = user_id);

drop policy if exists "Padres pueden quitar like" on public.likes;
create policy "Padres pueden quitar like" on public.likes for delete using (auth.uid() = user_id);

-- PAYMENTS
drop policy if exists "Directora ve todos los pagos" on public.payments;
create policy "Directora ve todos los pagos" on public.payments for all using (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Padres ven sus pagos" on public.payments;
create policy "Padres ven sus pagos" on public.payments for select using (
  exists (select 1 from public.students s where s.id = payments.student_id and s.parent_id = auth.uid())
);

-- NOTIFICATIONS
drop policy if exists "Usuarios ven sus notificaciones" on public.notifications;
create policy "Usuarios ven sus notificaciones" on public.notifications for select using (
  auth.uid() = user_id
);

-- 1.11 Inquietudes (Inquiries - Comunicación Padres-Directora)
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  parent_id uuid references public.profiles(id) not null,
  student_id bigint references public.students(id), -- Opcional, para contexto
  subject text,
  message text not null,
  response text,
  status text default 'pending', -- pending, resolved
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  responded_at timestamp with time zone
);

-- Fix 400 Error: Missing columns in inquiries
alter table public.inquiries add column if not exists priority text default 'medium';
alter table public.inquiries add column if not exists folio text;
alter table public.inquiries add column if not exists updated_at timestamp with time zone;
alter table public.inquiries add column if not exists attachment_url text;

alter table public.inquiries enable row level security;

drop policy if exists "Directora ve todas las inquietudes" on public.inquiries;
create policy "Directora ve todas las inquietudes" on public.inquiries for all using (
  get_my_role() in ('directora', 'asistente')
);

drop policy if exists "Padres ven sus inquietudes" on public.inquiries;
create policy "Padres ven sus inquietudes" on public.inquiries for select using (
  auth.uid() = parent_id
);

drop policy if exists "Padres crean inquietudes" on public.inquiries;
create policy "Padres crean inquietudes" on public.inquiries for insert with check (
  auth.uid() = parent_id
);

drop policy if exists "Usuarios marcan leida" on public.notifications;
create policy "Usuarios marcan leida" on public.notifications for update using (
  auth.uid() = user_id
);

-- CLASSROOM CHAT
drop policy if exists "Ver chat aula" on public.classroom_chat;
create policy "Ver chat aula" on public.classroom_chat for select using (
  exists (select 1 from public.classrooms c where c.id = classroom_chat.classroom_id and (c.teacher_id = auth.uid() or exists (select 1 from public.students s where s.classroom_id = c.id and s.parent_id = auth.uid())))
);
drop policy if exists "Enviar chat aula" on public.classroom_chat;
create policy "Enviar chat aula" on public.classroom_chat for insert with check (auth.uid() = user_id);

-- INCIDENTS
drop policy if exists "Maestras crean incidentes" on public.incidents;
create policy "Maestras crean incidentes" on public.incidents for insert with check (auth.uid() = teacher_id);

drop policy if exists "Ver incidentes" on public.incidents;
create policy "Ver incidentes" on public.incidents for select using (
  auth.uid() = teacher_id OR exists (select 1 from public.profiles where id = auth.uid() and role in ('directora', 'asistente')) OR exists (select 1 from public.students s where s.id = incidents.student_id and s.parent_id = auth.uid())
);

-- DAILY LOGS & GALLERY POLICIES
drop policy if exists "Maestras gestionan daily_logs" on public.daily_logs;
create policy "Maestras gestionan daily_logs" on public.daily_logs for all using (
  exists (select 1 from public.classrooms c where c.id = daily_logs.classroom_id and c.teacher_id = auth.uid())
);

drop policy if exists "Maestras gestionan galeria" on public.classroom_gallery;
create policy "Maestras gestionan galeria" on public.classroom_gallery for all using (
  exists (select 1 from public.classrooms c where c.id = classroom_gallery.classroom_id and c.teacher_id = auth.uid())
);
drop policy if exists "Padres ven galeria" on public.classroom_gallery;
create policy "Padres ven galeria" on public.classroom_gallery for select using (
  exists (select 1 from public.students s where s.parent_id = auth.uid() and s.classroom_id = classroom_gallery.classroom_id)
);

-- 1. RPC: Reporte Financiero Mensual por Aula (Optimizado para gráficas)
create or replace function public.get_monthly_financial_report_by_classroom(p_month text)
returns table (
  classroom_name text,
  total_expected numeric,
  total_paid numeric,
  total_pending numeric
)
language plpgsql
security definer
as $$
begin
  return query
  select 
    c.name as classroom_name,
    coalesce(sum(p.amount), 0) as total_expected,
    coalesce(sum(case when p.status = 'paid' or p.status = 'efectivo' then p.amount else 0 end), 0) as total_paid,
    coalesce(sum(case when p.status = 'pending' then p.amount else 0 end), 0) as total_pending
  from classrooms c
  left join students s on s.classroom_id = c.id
  left join payments p on p.student_id = s.id and p.month_paid = p_month
  group by c.name
  order by c.name;
end;
$$;

-- 2. RPC: KPIs del Dashboard (Todos los contadores en una sola llamada)
create or replace function public.get_dashboard_kpis()
returns jsonb
language plpgsql
security definer
as $$
declare
  v_total_students int;
  v_total_teachers int;
  v_active_classrooms int;
  v_attendance_today int;
  v_pending_payments numeric;
  v_active_incidents int;
begin
  select count(*) into v_total_students from students where is_active = true;
  select count(*) into v_total_teachers from profiles where role = 'maestra';
  select count(*) into v_active_classrooms from classrooms;
  select count(*) into v_attendance_today from attendance where date = current_date and status = 'present';
  select coalesce(sum(amount), 0) into v_pending_payments from payments where status = 'pending';
  select count(*) into v_active_incidents from inquiries where status = 'pending';

  return jsonb_build_object(
    'total_students', v_total_students,
    'total_teachers', v_total_teachers,
    'active_classrooms', v_active_classrooms,
    'attendance_today', v_attendance_today,
    'pending_payments', v_pending_payments,
    'active_incidents', v_active_incidents
  );
end;
$$;


-- Actualización de la función RPC para aceptar filtro de mes
create or replace function public.get_dashboard_kpis(p_month text)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_total_students int;
  v_total_teachers int;
  v_active_classrooms int;
  v_attendance_today int;
  v_pending_payments numeric;
  v_active_incidents int;
begin
  -- Contadores generales
  select count(*) into v_total_students from students where is_active = true;
  select count(*) into v_total_teachers from profiles where role = 'maestra';
  select count(*) into v_active_classrooms from classrooms;
  
  -- Asistencia de hoy (Métrica en tiempo real)
  select count(*) into v_attendance_today from attendance where date = current_date and status = 'present';
  
  -- Pagos Pendientes (Filtrado por mes seleccionado)
  -- Si el mes no coincide, no suma al KPI de "deuda del mes"
  select coalesce(sum(amount), 0) into v_pending_payments 
  from payments 
  where status = 'pending' 
  and month_paid ilike p_month;

  -- Incidencias activas
  select count(*) into v_active_incidents from inquiries where status = 'pending';

  return jsonb_build_object(
    'total_students', v_total_students,
    'total_teachers', v_total_teachers,
    'active_classrooms', v_active_classrooms,
    'attendance_today', v_attendance_today,
    'pending_payments', v_pending_payments,
    'active_incidents', v_active_incidents
  );
end;
$$;
