-- ============================================================
-- Karpus Kids — Sistema de Calificaciones V2
-- Actividades Evaluables + Promedios por Materia
-- Ejecutar en Supabase SQL Editor
-- ============================================================

-- ── 1. Tabla de Materias ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.subjects (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            text NOT NULL UNIQUE,
  education_level text NOT NULL CHECK (education_level IN ('estancia','preescolar','primaria')),
  description     text,
  is_active       boolean DEFAULT true,
  created_at      timestamp with time zone DEFAULT now() NOT NULL
);

-- Materias base por nivel
INSERT INTO public.subjects (name, education_level, description) VALUES
  ('Desarrollo Socioemocional', 'estancia',    'Habilidades socioemocionales y adaptación'),
  ('Psicomotricidad',           'estancia',    'Desarrollo motor grueso y fino'),
  ('Lenguaje',                  'estancia',    'Expresión y comprensión verbal'),
  ('Descubrimiento del Entorno','estancia',    'Exploración y conocimiento del mundo'),
  ('Arte y Creatividad',        'estancia',    'Expresión artística y creativa'),
  ('Inglés',                    'estancia',    'Introducción al inglés'),

  ('Lenguaje y Comunicación',   'preescolar',  'Lectura, escritura y comprensión'),
  ('Pensamiento Matemático',    'preescolar',  'Números, operaciones y lógica'),
  ('Exploración y Conocimiento','preescolar',  'Ciencias naturales y sociales'),
  ('Desarrollo Socioemocional', 'preescolar',  'Convivencia y autoestima'),
  ('Inglés',                    'preescolar',  'Inglés como segundo idioma'),
  ('Arte y Expresión',          'preescolar',  'Arte, música y dramatización'),
  ('Formación Cívica y Ética',  'preescolar',  'Valores y ciudadanía'),
  ('Educación Física',          'preescolar',  'Actividad física y salud'),

  ('Español',                   'primaria',    'Lengua y literatura'),
  ('Matemáticas',               'primaria',    'Aritmética, álgebra y geometría'),
  ('Ciencias Naturales',        'primaria',    'Biología, química y física básica'),
  ('Ciencias Sociales',         'primaria',    'Historia, geografía y sociedad'),
  ('Inglés',                    'primaria',    'English as a second language'),
  ('Formación Cívica y Ética',  'primaria',    'Valores, derechos y responsabilidades'),
  ('Educación Física',          'primaria',    'Deporte y condición física'),
  ('Arte',                      'primaria',    'Artes visuales, música y teatro'),
  ('Tecnología',                'primaria',    'Herramientas digitales y pensamiento computacional')
ON CONFLICT (name) DO NOTHING;

-- ── 2. Configuración de Actividades por Período ───────────────
-- La directora configura cuántas actividades por materia en cada período
CREATE TABLE IF NOT EXISTS public.period_config (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id    bigint REFERENCES public.periods(id) ON DELETE CASCADE NOT NULL,
  subject_id   bigint REFERENCES public.subjects(id) ON DELETE CASCADE NOT NULL,
  activity_count int NOT NULL CHECK (activity_count >= 5 AND activity_count <= 8),
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(period_id, subject_id)
);

-- ── 3. Tabla de Actividades Evaluables ────────────────────────
-- Cada fila es una "evidencia de aprendizaje" individual
CREATE TABLE IF NOT EXISTS public.activities (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_id       bigint REFERENCES public.period_config(id) ON DELETE CASCADE NOT NULL,
  title           text NOT NULL,
  description     text,
  max_score       numeric(5,2) DEFAULT 100,
  activity_number int NOT NULL,
  is_mandatory    boolean DEFAULT true,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(config_id, activity_number)
);

-- ── 4. Tabla de Calificaciones V2 (0-100) ────────────────────
-- Nota: la tabla grades ya existe. Se agrega activity_id como FK.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'grades' AND column_name = 'activity_id'
  ) THEN
    ALTER TABLE public.grades ADD COLUMN activity_id bigint REFERENCES public.activities(id) ON DELETE CASCADE;
    ALTER TABLE public.grades ADD COLUMN score_v2 numeric(5,2) CHECK (score_v2 >= 0 AND score_v2 <= 100);
    CREATE INDEX IF NOT EXISTS idx_grades_activity ON public.grades(activity_id);
    CREATE INDEX IF NOT EXISTS idx_grades_student_period ON public.grades(student_id, period_id);
  END IF;
END $$;

-- ── 5. Tabla de Promedios por Materia (calculados al cerrar) ─
CREATE TABLE IF NOT EXISTS public.subject_averages (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE NOT NULL,
  period_id    bigint REFERENCES public.periods(id) ON DELETE CASCADE NOT NULL,
  subject_id   bigint REFERENCES public.subjects(id) ON DELETE CASCADE NOT NULL,
  average      numeric(5,2) NOT NULL,
  graded_count int NOT NULL DEFAULT 0,
  method       text DEFAULT 'best_5' CHECK (method IN ('best_5','all')),
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(student_id, period_id, subject_id)
);

-- ── 6. RPC: Obtener configuración de actividades del período ──
DROP FUNCTION IF EXISTS public.get_period_config(bigint);
CREATE OR REPLACE FUNCTION public.get_period_config(p_period_id bigint)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id',             pc.id,
        'subject_id',     pc.subject_id,
        'subject_name',   s.name,
        'education_level',s.education_level,
        'activity_count', pc.activity_count
      )
      ORDER BY s.name
    ),
    '[]'::jsonb
  )
  FROM public.period_config pc
  JOIN public.subjects s ON s.id = pc.subject_id
  WHERE pc.period_id = p_period_id;
$$;

GRANT EXECUTE ON FUNCTION public.get_period_config(bigint) TO authenticated;

-- ── 7. RPC: Obtener actividades con calificaciones ────────────
DROP FUNCTION IF EXISTS public.get_activities_with_grades(bigint);
CREATE OR REPLACE FUNCTION public.get_activities_with_grades(p_period_id bigint)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id',             a.id,
        'title',          a.title,
        'description',    a.description,
        'max_score',      a.max_score,
        'activity_number',a.activity_number,
        'is_mandatory',   a.is_mandatory,
        'config_id',      a.config_id,
        'subject_id',     pc.subject_id,
        'subject_name',   s.name,
        'grade_count',    COALESCE(g.grade_count, 0),
        'graded_count',   COALESCE(g.graded_count, 0)
      )
      ORDER BY s.name, a.activity_number
    ),
    '[]'::jsonb
  )
  FROM public.activities a
  JOIN public.period_config pc ON pc.id = a.config_id
  JOIN public.subjects s ON s.id = pc.subject_id
  LEFT JOIN LATERAL (
    SELECT
      COUNT(*)::int AS grade_count,
      COUNT(g.score_v2)::int AS graded_count
    FROM public.grades g
    WHERE g.activity_id = a.id
  ) g ON true
  WHERE pc.period_id = p_period_id;
$$;

GRANT EXECUTE ON FUNCTION public.get_activities_with_grades(bigint) TO authenticated;

-- ── 8. RPC: Obtener calificaciones de un estudiante por período ─
DROP FUNCTION IF EXISTS public.get_student_grades_v2(bigint, bigint);
CREATE OR REPLACE FUNCTION public.get_student_grades_v2(p_student_id bigint, p_period_id bigint)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'activity_id',   g.activity_id,
        'score',         g.score_v2,
        'subject_name',  s.name,
        'activity_title',a.title,
        'activity_number',a.activity_number,
        'comment',       g.notes
      )
      ORDER BY s.name, a.activity_number
    ),
    '[]'::jsonb
  )
  FROM public.grades g
  JOIN public.activities a ON a.id = g.activity_id
  JOIN public.period_config pc ON pc.id = a.config_id
  JOIN public.subjects s ON s.id = pc.subject_id
  WHERE g.student_id = p_student_id
    AND pc.period_id = p_period_id
    AND g.score_v2 IS NOT NULL;
$$;

GRANT EXECUTE ON FUNCTION public.get_student_grades_v2(bigint, bigint) TO authenticated;

-- ── 9. RPC: Obtener promedios por materia de un estudiante ────
DROP FUNCTION IF EXISTS public.get_student_subject_averages(bigint, bigint);
CREATE OR REPLACE FUNCTION public.get_student_subject_averages(p_student_id bigint, p_period_id bigint)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'subject_name',  s.name,
        'average',       sa.average,
        'graded_count',  sa.graded_count,
        'method',        sa.method
      )
      ORDER BY s.name
    ),
    '[]'::jsonb
  )
  FROM public.subject_averages sa
  JOIN public.subjects s ON s.id = sa.subject_id
  WHERE sa.student_id = p_student_id
    AND sa.period_id = p_period_id;
$$;

GRANT EXECUTE ON FUNCTION public.get_student_subject_averages(bigint, bigint) TO authenticated;

-- ── 10. RPC: Obtener período activo de un aula ────────────────
DROP FUNCTION IF EXISTS public.get_active_period(bigint);
CREATE OR REPLACE FUNCTION public.get_active_period(p_classroom_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_period periods%ROWTYPE;
BEGIN
  SELECT * INTO v_period
  FROM public.periods
  WHERE classroom_id = p_classroom_id
    AND status = 'open'
    AND is_active = true
  ORDER BY created_at DESC
  LIMIT 1;

  IF NOT FOUND THEN
    SELECT * INTO v_period
    FROM public.periods
    WHERE classroom_id = p_classroom_id
      AND status = 'open'
    ORDER BY created_at DESC
    LIMIT 1;
  END IF;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('found', false, 'status', 'no_period');
  END IF;

  RETURN jsonb_build_object(
    'found',      true,
    'id',         v_period.id,
    'name',       v_period.name,
    'status',     v_period.status,
    'is_active',  v_period.is_active,
    'start_date', v_period.start_date,
    'end_date',   v_period.end_date
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_active_period(bigint) TO authenticated;

-- ── 11. RPC: Cerrar período con sistema V2 ────────────────────
-- Calcula promedios por materia usando las mejores N calificaciones
-- y genera report_cards con el promedio general del período
DROP FUNCTION IF EXISTS public.close_period(bigint);
CREATE OR REPLACE FUNCTION public.close_period(p_period_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_period        periods%ROWTYPE;
  v_user_id       uuid;
  v_role          text;
  v_student       record;
  v_config        record;
  v_subject_avg   numeric(5,2);
  v_method        text;
  v_total_avg     numeric(5,2);
  v_subject_count int;
  v_cards_created int := 0;
  v_level         text;
BEGIN
  v_user_id := auth.uid();
  SELECT role INTO v_role FROM public.profiles WHERE id = v_user_id;
  IF v_role NOT IN ('directora', 'admin') THEN
    RETURN jsonb_build_object('error', 'Solo la directora puede cerrar periodos');
  END IF;

  SELECT * INTO v_period FROM public.periods WHERE id = p_period_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Periodo no encontrado');
  END IF;
  IF v_period.status = 'closed' THEN
    RETURN jsonb_build_object('error', 'El periodo ya esta cerrado');
  END IF;

  -- Para cada estudiante activo del aula
  FOR v_student IN
    SELECT s.id AS student_id, s.name AS student_name
    FROM public.students s
    WHERE s.classroom_id = v_period.classroom_id
      AND s.is_active = true
  LOOP
    v_total_avg := 0;
    v_subject_count := 0;

    -- Para cada materia configurada en el período
    FOR v_config IN
      SELECT pc.id AS config_id, pc.subject_id, pc.activity_count, s.name AS subject_name
      FROM public.period_config pc
      JOIN public.subjects s ON s.id = pc.subject_id
      WHERE pc.period_id = p_period_id
    LOOP
      -- Determinar método: si hay 5+ calificaciones usar best_5, si no all
      SELECT COUNT(*) INTO v_method
      FROM public.grades g
      JOIN public.activities a ON a.id = g.activity_id
      WHERE a.config_id = v_config.config_id
        AND g.student_id = v_student.student_id
        AND g.score_v2 IS NOT NULL;

      IF v_method::int >= 5 THEN
        v_method := 'best_5';
      ELSE
        v_method := 'all';
      END IF;

      -- Calcular promedio de la materia
      IF v_method = 'best_5' THEN
        SELECT ROUND(AVG(score_v2), 2) INTO v_subject_avg
        FROM (
          SELECT g.score_v2
          FROM public.grades g
          JOIN public.activities a ON a.id = g.activity_id
          WHERE a.config_id = v_config.config_id
            AND g.student_id = v_student.student_id
            AND g.score_v2 IS NOT NULL
          ORDER BY g.score_v2 DESC
          LIMIT 5
        ) best_scores;
      ELSE
        SELECT ROUND(AVG(g.score_v2), 2) INTO v_subject_avg
        FROM public.grades g
        JOIN public.activities a ON a.id = g.activity_id
        WHERE a.config_id = v_config.config_id
          AND g.student_id = v_student.student_id
          AND g.score_v2 IS NOT NULL;
      END IF;

      IF v_subject_avg IS NOT NULL THEN
        -- Guardar promedio de la materia
        INSERT INTO public.subject_averages (student_id, period_id, subject_id, average, graded_count, method)
        VALUES (
          v_student.student_id, p_period_id, v_config.subject_id,
          v_subject_avg, v_method::int,
          CASE WHEN v_method = 'best_5' THEN 'best_5' ELSE 'all' END
        )
        ON CONFLICT (student_id, period_id, subject_id) DO UPDATE SET
          average     = EXCLUDED.average,
          graded_count = EXCLUDED.graded_count,
          method      = EXCLUDED.method;

        v_total_avg := v_total_avg + v_subject_avg;
        v_subject_count := v_subject_count + 1;
      END IF;
    END LOOP;

    -- Promedio general del período (promedio de promedios de materias)
    IF v_subject_count > 0 THEN
      v_total_avg := ROUND(v_total_avg / v_subject_count, 2);
    ELSE
      v_total_avg := NULL;
    END IF;

    -- Determinar nivel (escala 0-100)
    v_level := CASE
      WHEN v_total_avg IS NULL THEN 'Sin calificar'
      WHEN v_total_avg >= 90   THEN 'Excelente'
      WHEN v_total_avg >= 80   THEN 'Bueno'
      WHEN v_total_avg >= 70   THEN 'En proceso'
      ELSE                          'Requiere apoyo'
    END;

    -- Upsert report_card
    INSERT INTO public.report_cards (
      student_id, classroom_id, period_id,
      task_avg, formal_avg, final_score, level,
      generated_at
    )
    VALUES (
      v_student.student_id, v_period.classroom_id, p_period_id,
      v_total_avg, v_total_avg, v_total_avg, v_level,
      now()
    )
    ON CONFLICT (student_id, period_id) DO UPDATE SET
      task_avg    = EXCLUDED.task_avg,
      formal_avg  = EXCLUDED.formal_avg,
      final_score = EXCLUDED.final_score,
      level       = EXCLUDED.level,
      generated_at = now();

    v_cards_created := v_cards_created + 1;
  END LOOP;

  -- Cerrar el período
  UPDATE public.periods
  SET status = 'closed', is_active = false
  WHERE id = p_period_id;

  -- Auditoría
  INSERT INTO public.audit_logs (user_id, action, payload, created_at)
  VALUES (v_user_id, 'period.closed.v2', jsonb_build_object(
    'period_id',       p_period_id,
    'period_name',     v_period.name,
    'cards_generated', v_cards_created
  ), now());

  RETURN jsonb_build_object(
    'success',         true,
    'period_id',       p_period_id,
    'period_name',     v_period.name,
    'cards_generated', v_cards_created
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.close_period(bigint) TO authenticated;

-- ── 12. RPC: Obtener historial académico del estudiante ───────
DROP FUNCTION IF EXISTS public.get_student_history(bigint);
CREATE OR REPLACE FUNCTION public.get_student_history(p_student_id bigint)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'period_name',    p.name,
        'classroom_name', c.name,
        'task_avg',       rc.task_avg,
        'formal_avg',     rc.formal_avg,
        'final_score',    rc.final_score,
        'level',          rc.level,
        'teacher_comment',rc.teacher_comment,
        'generated_at',   rc.generated_at
      )
      ORDER BY p.start_date DESC
    ),
    '[]'::jsonb
  )
  FROM public.report_cards rc
  JOIN public.periods p ON p.id = rc.period_id
  LEFT JOIN public.classrooms c ON c.id = rc.classroom_id
  WHERE rc.student_id = p_student_id;
$$;

GRANT EXECUTE ON FUNCTION public.get_student_history(bigint) TO authenticated;

-- ── 13. RLS Policies ─────────────────────────────────────────

-- Subjects: lectura pública para todos los autenticados
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "subjects_auth" ON public.subjects;
CREATE POLICY "subjects_auth" ON public.subjects
  FOR SELECT USING (auth.role() = 'authenticated');

-- Period Config: staff puede gestionar
ALTER TABLE public.period_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "period_config_staff" ON public.period_config;
CREATE POLICY "period_config_staff" ON public.period_config FOR ALL
  USING (get_my_role() IN ('directora','asistente','maestra','admin'));

-- Activities: staff puede gestionar
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "activities_staff" ON public.activities;
CREATE POLICY "activities_staff" ON public.activities FOR ALL
  USING (get_my_role() IN ('directora','asistente','maestra','admin'));

-- Subject Averages: staff lectura, cálculo via SECURITY DEFINER
ALTER TABLE public.subject_averages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "subject_averages_staff" ON public.subject_averages;
CREATE POLICY "subject_averages_staff" ON public.subject_averages FOR ALL
  USING (get_my_role() IN ('directora','asistente','maestra','admin'));
DROP POLICY IF EXISTS "subject_averages_parent" ON public.subject_averages;
CREATE POLICY "subject_averages_parent" ON public.subject_averages FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.students st
      WHERE st.id = subject_averages.student_id
        AND st.parent_id = auth.uid()
    )
  );

-- ── 14. Constraint UNIQUE en report_cards ─────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'report_cards_student_period_unique'
      AND conrelid = 'public.report_cards'::regclass
  ) THEN
    ALTER TABLE public.report_cards
      ADD CONSTRAINT report_cards_student_period_unique
      UNIQUE (student_id, period_id);
  END IF;
END $$;
