-- ============================================================
-- KARPUS KIDS — School Engine Migration
-- Motor Escolar Inteligente v1.0
-- Ejecutar en Supabase SQL Editor
-- ============================================================

-- ── 0. CLEANUP ────────────────────────────────────────────────
DO $$
DECLARE fn record;
BEGIN
  FOR fn IN
    SELECT p.oid, p.proname, n.nspname
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname IN (
        'get_active_school_year','get_active_period','get_current_period',
        'get_school_year_status','close_period','close_school_year',
        'promote_students','get_student_history','can_enroll_student',
        'can_reenroll_student','get_enrollment_status','advance_school_year_state',
        'get_period_stats','get_teacher_year_data','get_parent_year_data'
      )
  LOOP
    EXECUTE format('DROP FUNCTION IF EXISTS %I.%I(%s) CASCADE',
      fn.nspname, fn.proname,
      pg_get_function_identity_arguments(fn.oid));
  END LOOP;
END $$;

-- ── 1. NEW TABLES ─────────────────────────────────────────────

-- Año Escolar: Motor central del sistema
CREATE TABLE IF NOT EXISTS public.school_years (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              text NOT NULL,               -- '2026-2027'
  start_date        date NOT NULL,
  end_date          date NOT NULL,
  enrollment_start  date,                        -- Ventana de inscripciones
  enrollment_end    date,
  reenrollment_start date,                       -- Ventana de reinscripciones
  reenrollment_end  date,
  status            text DEFAULT 'draft'
                    CHECK (status IN (
                      'draft','enrollment','reenrollment',
                      'active','closed','archived'
                    )),
  created_by        uuid REFERENCES public.profiles(id),
  created_at        timestamp with time zone DEFAULT now() NOT NULL,
  updated_at        timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT valid_dates CHECK (end_date > start_date),
  CONSTRAINT valid_enrollment CHECK (
    enrollment_start IS NULL OR enrollment_end IS NULL
    OR enrollment_end >= enrollment_start
  ),
  CONSTRAINT valid_reenrollment CHECK (
    reenrollment_start IS NULL OR reenrollment_end IS NULL
    OR reenrollment_end >= reenrollment_start
  )
);

-- Solo un año puede estar activo/inscripción/reinscripción a la vez
CREATE UNIQUE INDEX IF NOT EXISTS idx_school_years_one_active
  ON public.school_years (status)
  WHERE status IN ('active', 'enrollment', 'reenrollment');

-- Períodos académicos: ahora con school_year_id
CREATE TABLE IF NOT EXISTS public.academic_periods (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_year_id    bigint NOT NULL REFERENCES public.school_years(id) ON DELETE CASCADE,
  name              text NOT NULL,               -- 'Periodo 1', 'Periodo 2', 'Periodo 3'
  start_date        date NOT NULL,
  end_date          date NOT NULL,
  order_index       integer NOT NULL DEFAULT 1,  -- Para ordenar: 1, 2, 3...
  status            text DEFAULT 'pending'
                    CHECK (status IN ('pending','open','closed')),
  is_active         boolean DEFAULT false,
  created_at        timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT valid_period_dates CHECK (end_date > start_date),
  CONSTRAINT unique_period_order UNIQUE (school_year_id, order_index)
);

-- Migrar datos de periods existentes a academic_periods si hay datos
-- (Ejecutar solo si ya tienes periods con datos)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='periods') THEN
    IF EXISTS (SELECT 1 FROM public.periods WHERE start_date IS NOT NULL LIMIT 1) THEN
      -- Crear un año escolar de respaldo si no existe
      IF NOT EXISTS (SELECT 1 FROM public.school_years LIMIT 1) THEN
        BEGIN
          INSERT INTO public.school_years (name, start_date, end_date, status, created_at)
          SELECT
            EXTRACT(YEAR FROM min(start_date))::text || '-' || (EXTRACT(YEAR FROM max(start_date))::int + 1)::text,
            min(start_date)::date,
            COALESCE(max(end_date), (max(start_date) + interval '1 year'))::date,
            'archived',
            now()
          FROM public.periods
          WHERE start_date IS NOT NULL
          GROUP BY EXTRACT(YEAR FROM min(start_date));
        EXCEPTION WHEN OTHERS THEN
          RAISE NOTICE 'Skip school_years migration: %', SQLERRM;
        END;
      END IF;

      -- Migrar períodos existentes al primer año escolar creado
      IF EXISTS (SELECT 1 FROM public.school_years LIMIT 1) THEN
        BEGIN
          INSERT INTO public.academic_periods (school_year_id, name, start_date, end_date, order_index, status, is_active, created_at)
          SELECT
            (SELECT id FROM public.school_years ORDER BY created_at DESC LIMIT 1),
            p.name,
            p.start_date,
            p.end_date,
            ROW_NUMBER() OVER (ORDER BY p.start_date)::int,
            CASE WHEN p.status = 'open' THEN 'open' ELSE 'closed' END,
            COALESCE(p.is_active, false),
            COALESCE(p.created_at, now())
          FROM public.periods p
          WHERE p.start_date IS NOT NULL
          ON CONFLICT DO NOTHING;
        EXCEPTION WHEN OTHERS THEN
          RAISE NOTICE 'Skip academic_periods migration: %', SQLERRM;
        END;
      END IF;
    END IF;
  END IF;
END $$;

-- Historial de estudiantes: NUNCA se borra
CREATE TABLE IF NOT EXISTS public.student_history (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id        bigint NOT NULL,             -- Referencia lógica (no FK para permitir historial permanent)
  student_name      text NOT NULL,
  school_year_id    bigint NOT NULL REFERENCES public.school_years(id),
  academic_period_id bigint REFERENCES public.academic_periods(id),
  classroom_id      bigint REFERENCES public.classrooms(id),
  classroom_name    text,
  teacher_name      text,
  grade_level       text,                        -- 'Kinder A', 'Pre-Primario', 'Primero'
  average_score     numeric(5,2),
  attendance_pct    numeric(5,2),
  total_days        integer DEFAULT 0,
  absent_days       integer DEFAULT 0,
  late_days         integer DEFAULT 0,
  status            text DEFAULT 'active'
                    CHECK (status IN ('active','promoted','retained','withdrawn','graduated')),
  notes             text,
  created_at        timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT unique_student_year UNIQUE (student_id, school_year_id)
);

-- Inscripciones/Reinscripciones
CREATE TABLE IF NOT EXISTS public.enrollments (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id        bigint REFERENCES public.students(id) ON DELETE SET NULL,
  school_year_id    bigint NOT NULL REFERENCES public.school_years(id),
  type              text NOT NULL CHECK (type IN ('new','reenrollment')),
  classroom_id      bigint REFERENCES public.classrooms(id),
  parent_id         uuid REFERENCES public.profiles(id),
  student_name      text,
  status            text DEFAULT 'pending'
                    CHECK (status IN ('pending','approved','rejected')),
  enrolled_at       timestamp with time zone,
  approved_by       uuid REFERENCES public.profiles(id),
  notes             text,
  created_at        timestamp with time zone DEFAULT now() NOT NULL
);

-- Configuración de promoción automática
CREATE TABLE IF NOT EXISTS public.promotion_rules (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_year_id    bigint NOT NULL REFERENCES public.school_years(id) ON DELETE CASCADE,
  from_grade        text NOT NULL,               -- 'Kinder A'
  to_grade          text NOT NULL,               -- 'Kinder B' o 'Pre-Primario'
  min_average       numeric(5,2) DEFAULT 70.00,  -- Mínimo promedio para promover
  min_attendance    numeric(5,2) DEFAULT 80.00,  -- Mínimo % asistencia
  auto_promote      boolean DEFAULT true,
  created_at        timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT unique_promotion_rule UNIQUE (school_year_id, from_grade)
);

-- ── 2. ADD COLUMNS TO EXISTING TABLES ────────────────────────

-- students: agregar school_year_id y academic_period_id
ALTER TABLE public.students
  ADD COLUMN IF NOT EXISTS school_year_id bigint REFERENCES public.school_years(id),
  ADD COLUMN IF NOT EXISTS academic_period_id bigint REFERENCES public.academic_periods(id),
  ADD COLUMN IF NOT EXISTS enrollment_type text DEFAULT 'new' CHECK (enrollment_type IN ('new','reenrollment')),
  ADD COLUMN IF NOT EXISTS enrolled_at timestamp with time zone;

-- grades: ya tiene period_id, agregar school_year_id
ALTER TABLE public.grades
  ADD COLUMN IF NOT EXISTS school_year_id bigint REFERENCES public.school_years(id);

-- tasks: ya tiene period_id, agregar school_year_id
ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS school_year_id bigint REFERENCES public.school_years(id);

-- posts: agregar school_year_id
ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS school_year_id bigint REFERENCES public.school_years(id);

-- attendance: agregar school_year_id y academic_period_id
ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS school_year_id bigint REFERENCES public.school_years(id),
  ADD COLUMN IF NOT EXISTS academic_period_id bigint REFERENCES public.academic_periods(id);

-- daily_logs: agregar school_year_id y academic_period_id
ALTER TABLE public.daily_logs
  ADD COLUMN IF NOT EXISTS school_year_id bigint REFERENCES public.school_years(id),
  ADD COLUMN IF NOT EXISTS academic_period_id bigint REFERENCES public.academic_periods(id);

-- report_cards: agregar school_year_id
ALTER TABLE public.report_cards
  ADD COLUMN IF NOT EXISTS school_year_id bigint REFERENCES public.school_years(id);

-- ── 3. INDEXES ────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_school_years_status ON public.school_years(status);
CREATE INDEX IF NOT EXISTS idx_academic_periods_year ON public.academic_periods(school_year_id);
CREATE INDEX IF NOT EXISTS idx_academic_periods_active ON public.academic_periods(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_student_history_student ON public.student_history(student_id);
CREATE INDEX IF NOT EXISTS idx_student_history_year ON public.student_history(school_year_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_student_history_student_year ON public.student_history(student_id, school_year_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_year ON public.enrollments(school_year_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_student ON public.enrollments(student_id);
CREATE INDEX IF NOT EXISTS idx_grades_school_year ON public.grades(school_year_id) WHERE school_year_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_school_year ON public.tasks(school_year_id) WHERE school_year_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_posts_school_year ON public.posts(school_year_id) WHERE school_year_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_attendance_school_year ON public.attendance(school_year_id) WHERE school_year_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_enrollments_classroom ON public.enrollments(classroom_id) WHERE classroom_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_enrollments_parent ON public.enrollments(parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_student_history_classroom ON public.student_history(classroom_id) WHERE classroom_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_school_years_created_by ON public.school_years(created_by) WHERE created_by IS NOT NULL;

-- ── 3b. PROFESIONAL INDEXES — Todas las tablas existentes ──────

-- students: búsquedas frecuentes por parent (padre panel) y classroom (maestra)
CREATE INDEX IF NOT EXISTS idx_students_parent_active ON public.students(parent_id, is_active) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_students_classroom_active ON public.students(classroom_id, is_active) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_students_year ON public.students(school_year_id) WHERE school_year_id IS NOT NULL;

-- posts: feed del muro por fecha + classroom, paginación
CREATE INDEX IF NOT EXISTS idx_posts_classroom_created ON public.posts(classroom_id, created_at DESC) WHERE classroom_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_posts_teacher ON public.posts(teacher_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_feed ON public.posts(created_at DESC) INCLUDE (content, media_url, media_type, teacher_id, classroom_id);

-- attendance: consultas diarias de maestra + reportes padre
CREATE INDEX IF NOT EXISTS idx_attendance_date_classroom_status ON public.attendance(date, classroom_id, status);
CREATE INDEX IF NOT EXISTS idx_attendance_student_status ON public.attendance(student_id, status, date);

-- grades: calificaciones por estudiante + periodo
CREATE INDEX IF NOT EXISTS idx_grades_student_period ON public.grades(student_id, period_id);
CREATE INDEX IF NOT EXISTS idx_grades_student_activity ON public.grades(student_id, activity_id);

-- tasks: tareas por aula + periodo
CREATE INDEX IF NOT EXISTS idx_tasks_classroom_date ON public.tasks(classroom_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_classroom_period ON public.tasks(classroom_id, period_id) WHERE period_id IS NOT NULL;

-- daily_logs: rutina diaria por estudiante + fecha
CREATE INDEX IF NOT EXISTS idx_daily_logs_student_date ON public.daily_logs(student_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_logs_classroom_date ON public.daily_logs(classroom_id, date DESC) WHERE classroom_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_daily_logs_year ON public.daily_logs(school_year_id) WHERE school_year_id IS NOT NULL;

-- payments: búsquedas financieras
CREATE INDEX IF NOT EXISTS idx_payments_student_status ON public.payments(student_id, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_payments_due_overdue ON public.payments(due_date, status) WHERE status IN ('pending','overdue') AND deleted_at IS NULL;

-- task_evidences: entregas por tarea + estudiante
CREATE INDEX IF NOT EXISTS idx_task_evidences_task_status ON public.task_evidences(task_id, status);
CREATE INDEX IF NOT EXISTS idx_task_evidences_student ON public.task_evidences(student_id, task_id);

-- messages: chat por conversación + fecha
CREATE INDEX IF NOT EXISTS idx_messages_sender ON public.messages(sender_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_unread ON public.messages(conversation_id, is_read) WHERE is_read = false;

-- notifications: notificaciones por usuario
CREATE INDEX IF NOT EXISTS idx_notifications_user_date ON public.notifications(user_id, created_at DESC);

-- incidents: incidentes por estudiante
CREATE INDEX IF NOT EXISTS idx_incidents_student ON public.incidents(student_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_incidents_classroom ON public.incidents(classroom_id, created_at DESC);

-- door_punches: registros de acceso por fecha + estudiante
CREATE INDEX IF NOT EXISTS idx_door_punches_classroom_date ON public.door_punches(classroom_id, date) WHERE classroom_id IS NOT NULL;

-- report_cards: boletas por estudiante + año
CREATE INDEX IF NOT EXISTS idx_report_cards_student ON public.report_cards(student_id, period_id);

-- period_config: configuración de materias por periodo
CREATE INDEX IF NOT EXISTS idx_period_config_period ON public.period_config(period_id);

-- activities: actividades por configuración de periodo
CREATE INDEX IF NOT EXISTS idx_activities_config ON public.activities(config_id);

-- conversations: lista de chats por participantes
CREATE INDEX IF NOT EXISTS idx_conversations_updated ON public.conversations(updated_at DESC);

-- ── 4. RLS ────────────────────────────────────────────────────
ALTER TABLE public.school_years      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.academic_periods  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_history   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotion_rules   ENABLE ROW LEVEL SECURITY;

-- School Years
DROP POLICY IF EXISTS "school_years_staff" ON public.school_years;
CREATE POLICY "school_years_staff" ON public.school_years FOR ALL
  USING (get_my_role() IN ('directora','admin'))
  WITH CHECK (get_my_role() IN ('directora','admin'));

DROP POLICY IF EXISTS "school_years_read" ON public.school_years;
CREATE POLICY "school_years_read" ON public.school_years FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- Academic Periods
DROP POLICY IF EXISTS "academic_periods_staff" ON public.academic_periods;
CREATE POLICY "academic_periods_staff" ON public.academic_periods FOR ALL
  USING (get_my_role() IN ('directora','maestra','asistente','admin'))
  WITH CHECK (get_my_role() IN ('directora','maestra','asistente','admin'));

DROP POLICY IF EXISTS "academic_periods_parent" ON public.academic_periods;
CREATE POLICY "academic_periods_parent" ON public.academic_periods FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- Student History
DROP POLICY IF EXISTS "student_history_staff" ON public.student_history;
CREATE POLICY "student_history_staff" ON public.student_history FOR ALL
  USING (get_my_role() IN ('directora','admin'))
  WITH CHECK (get_my_role() IN ('directora','admin'));

DROP POLICY IF EXISTS "student_history_teacher" ON public.student_history;
CREATE POLICY "student_history_teacher" ON public.student_history FOR SELECT
  USING (get_my_role() IN ('maestra','asistente'));

DROP POLICY IF EXISTS "student_history_parent" ON public.student_history;
CREATE POLICY "student_history_parent" ON public.student_history FOR SELECT
  USING (
    student_id IN (SELECT id FROM public.students WHERE parent_id = auth.uid())
  );

-- Enrollments
DROP POLICY IF EXISTS "enrollments_staff" ON public.enrollments;
CREATE POLICY "enrollments_staff" ON public.enrollments FOR ALL
  USING (get_my_role() IN ('directora','asistente','admin'))
  WITH CHECK (get_my_role() IN ('directora','asistente','admin'));

DROP POLICY IF EXISTS "enrollments_parent" ON public.enrollments;
CREATE POLICY "enrollments_parent" ON public.enrollments FOR SELECT
  USING (parent_id = auth.uid());

-- Promotion Rules
DROP POLICY IF EXISTS "promotion_rules_staff" ON public.promotion_rules;
CREATE POLICY "promotion_rules_staff" ON public.promotion_rules FOR ALL
  USING (get_my_role() IN ('directora','admin'))
  WITH CHECK (get_my_role() IN ('directora','admin'));

-- ── 5. CORE FUNCTIONS ─────────────────────────────────────────

-- Obtener año escolar activo
CREATE OR REPLACE FUNCTION public.get_active_school_year()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public AS $$
DECLARE
  v_result jsonb;
BEGIN
  SELECT jsonb_build_object(
    'id', id,
    'name', name,
    'start_date', start_date,
    'end_date', end_date,
    'status', status,
    'enrollment_start', enrollment_start,
    'enrollment_end', enrollment_end,
    'reenrollment_start', reenrollment_start,
    'reenrollment_end', reenrollment_end
  ) INTO v_result
  FROM public.school_years
  WHERE status IN ('active', 'enrollment', 'reenrollment')
  ORDER BY
    CASE status WHEN 'active' THEN 1 WHEN 'enrollment' THEN 2 WHEN 'reenrollment' THEN 3 END
  LIMIT 1;

  RETURN COALESCE(v_result, '{}'::jsonb);
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_active_school_year() TO authenticated;

-- Obtener período activo actual
CREATE OR REPLACE FUNCTION public.get_active_period(p_classroom_id bigint DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public AS $$
DECLARE
  v_result jsonb;
BEGIN
  SELECT jsonb_build_object(
    'found', true,
    'id', ap.id,
    'name', ap.name,
    'start_date', ap.start_date,
    'end_date', ap.end_date,
    'status', ap.status,
    'is_active', ap.is_active,
    'school_year_id', ap.school_year_id,
    'school_year_name', sy.name,
    'order_index', ap.order_index
  ) INTO v_result
  FROM public.academic_periods ap
  JOIN public.school_years sy ON sy.id = ap.school_year_id
  WHERE ap.is_active = true AND ap.status = 'open'
    AND sy.status = 'active'
  ORDER BY ap.order_index
  LIMIT 1;

  RETURN COALESCE(v_result, jsonb_build_object('found', false));
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_active_period(bigint) TO authenticated;

-- Obtener todos los períodos de un año escolar
CREATE OR REPLACE FUNCTION public.get_periods_for_year(p_school_year_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public AS $$
DECLARE
  v_result jsonb;
BEGIN
  SELECT jsonb_agg(
    jsonb_build_object(
      'id', ap.id,
      'name', ap.name,
      'start_date', ap.start_date,
      'end_date', ap.end_date,
      'status', ap.status,
      'is_active', ap.is_active,
      'order_index', ap.order_index
    ) ORDER BY ap.order_index
  ) INTO v_result
  FROM public.academic_periods ap
  WHERE ap.school_year_id = p_school_year_id;

  RETURN COALESCE(v_result, '[]'::jsonb);
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_periods_for_year(bigint) TO authenticated;

-- Cerrar un período y abrir el siguiente
CREATE OR REPLACE FUNCTION public.close_period(p_period_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_period record;
  v_next record;
  v_role text;
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role NOT IN ('directora', 'admin') THEN
    RETURN jsonb_build_object('error', 'Solo la directora puede cerrar períodos');
  END IF;

  SELECT * INTO v_period FROM public.academic_periods WHERE id = p_period_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Período no encontrado');
  END IF;

  IF v_period.status = 'closed' THEN
    RETURN jsonb_build_object('error', 'El período ya está cerrado');
  END IF;

  -- Cerrar el período actual
  UPDATE public.academic_periods
  SET status = 'closed', is_active = false
  WHERE id = p_period_id;

  -- Buscar el siguiente período
  SELECT * INTO v_next
  FROM public.academic_periods
  WHERE school_year_id = v_period.school_year_id
    AND order_index = v_period.order_index + 1;

  IF FOUND THEN
    -- Abrir el siguiente período
    UPDATE public.academic_periods
    SET status = 'open', is_active = true
    WHERE id = v_next.id;

    RETURN jsonb_build_object(
      'success', true,
      'message', 'Período cerrado. Abierto: ' || v_next.name,
      'closed_period', v_period.name,
      'opened_period', v_next.name,
      'next_period_id', v_next.id
    );
  ELSE
    -- No hay más períodos: cerrar el año escolar
    UPDATE public.school_years
    SET status = 'closed'
    WHERE id = v_period.school_year_id;

    RETURN jsonb_build_object(
      'success', true,
      'message', 'Último período cerrado. Año escolar cerrado.',
      'closed_period', v_period.name,
      'year_closed', true
    );
  END IF;
END;
$$;
GRANT EXECUTE ON FUNCTION public.close_period(bigint) TO authenticated;

-- Obtener estado del año escolar (para el motor de estados)
CREATE OR REPLACE FUNCTION public.get_school_year_status()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public AS $$
DECLARE
  v_year record;
  v_today date := CURRENT_DATE;
  v_result jsonb;
  v_enrollment_open boolean := false;
  v_reenrollment_open boolean := false;
  v_active_period jsonb;
  v_days_remaining integer;
BEGIN
  -- Obtener el año activo
  SELECT * INTO v_year
  FROM public.school_years
  WHERE status IN ('active', 'enrollment', 'reenrollment')
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'has_active_year', false,
      'status', 'none',
      'message', 'No hay año escolar activo'
    );
  END IF;

  -- Verificar ventanas de inscripción/reinscripción
  IF v_year.enrollment_start IS NOT NULL AND v_year.enrollment_end IS NOT NULL THEN
    v_enrollment_open := v_today BETWEEN v_year.enrollment_start AND v_year.enrollment_end;
  END IF;

  IF v_year.reenrollment_start IS NOT NULL AND v_year.reenrollment_end IS NOT NULL THEN
    v_reenrollment_open := v_today BETWEEN v_year.reenrollment_start AND v_year.reenrollment_end;
  END IF;

  -- Obtener período activo
  v_active_period := public.get_active_period();

  -- Días restantes del año
  v_days_remaining := GREATEST(0, (v_year.end_date - v_today)::int);

  -- Determinar estado calculado
  v_result := jsonb_build_object(
    'has_active_year', true,
    'school_year_id', v_year.id,
    'school_year_name', v_year.name,
    'status', v_year.status,
    'start_date', v_year.start_date,
    'end_date', v_year.end_date,
    'enrollment_open', v_enrollment_open,
    'enrollment_window', jsonb_build_object(
      'start', v_year.enrollment_start,
      'end', v_year.enrollment_end
    ),
    'reenrollment_open', v_reenrollment_open,
    'reenrollment_window', jsonb_build_object(
      'start', v_year.reenrollment_start,
      'end', v_year.reenrollment_end
    ),
    'active_period', v_active_period,
    'days_remaining', v_days_remaining,
    'is_school_time', v_year.status = 'active' AND v_today BETWEEN v_year.start_date AND v_year.end_date
  );

  RETURN v_result;
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_school_year_status() TO authenticated;

-- Avanzar estado del año escolar automáticamente
CREATE OR REPLACE FUNCTION public.advance_school_year_state()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_year record;
  v_today date := CURRENT_DATE;
  v_new_status text;
  v_changed boolean := false;
  v_role text;
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role NOT IN ('directora', 'admin') THEN
    RETURN jsonb_build_object('error', 'Acceso denegado');
  END IF;

  SELECT * INTO v_year
  FROM public.school_years
  WHERE status IN ('active', 'enrollment', 'reenrollment', 'draft')
  ORDER BY
    CASE status WHEN 'active' THEN 1 WHEN 'enrollment' THEN 2 WHEN 'reenrollment' THEN 3 ELSE 4 END
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'No hay año escolar para avanzar');
  END IF;

  v_new_status := v_year.status;

  -- Transiciones automáticas según fechas
  CASE v_year.status
    WHEN 'draft' THEN
      IF v_year.enrollment_start IS NOT NULL AND v_today >= v_year.enrollment_start THEN
        v_new_status := 'enrollment';
        v_changed := true;
      END IF;

    WHEN 'enrollment' THEN
      IF v_year.enrollment_end IS NOT NULL AND v_today > v_year.enrollment_end THEN
        IF v_year.reenrollment_start IS NOT NULL AND v_today >= v_year.reenrollment_start THEN
          v_new_status := 'reenrollment';
        ELSE
          v_new_status := 'active';
        END IF;
        v_changed := true;
      END IF;

    WHEN 'reenrollment' THEN
      IF v_year.reenrollment_end IS NOT NULL AND v_today > v_year.reenrollment_end THEN
        v_new_status := 'active';
        v_changed := true;
      END IF;

    WHEN 'active' THEN
      IF v_today > v_year.end_date THEN
        v_new_status := 'closed';
        v_changed := true;
      END IF;
  END CASE;

  IF v_changed THEN
    UPDATE public.school_years SET status = v_new_status WHERE id = v_year.id;
    RETURN jsonb_build_object(
      'success', true,
      'old_status', v_year.status,
      'new_status', v_new_status,
      'school_year_name', v_year.name
    );
  END IF;

  RETURN jsonb_build_object(
    'success', false,
    'current_status', v_year.status,
    'message', 'No hay cambio de estado necesario'
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.advance_school_year_state() TO authenticated;

-- Verificar si un estudiante puede ser inscrito
CREATE OR REPLACE FUNCTION public.can_enroll_student(p_student_id bigint, p_school_year_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public AS $$
DECLARE
  v_student record;
  v_year record;
  v_existing record;
BEGIN
  SELECT * INTO v_student FROM public.students WHERE id = p_student_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('can_enroll', false, 'error', 'Estudiante no encontrado');
  END IF;

  SELECT * INTO v_year FROM public.school_years WHERE id = p_school_year_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('can_enroll', false, 'error', 'Año escolar no encontrado');
  END IF;

  -- Verificar si ya está inscrito en este año
  SELECT * INTO v_existing
  FROM public.enrollments
  WHERE student_id = p_student_id AND school_year_id = p_school_year_id AND status != 'rejected';

  IF FOUND THEN
    RETURN jsonb_build_object(
      'can_enroll', false,
      'error', 'El estudiante ya está inscrito en este año escolar',
      'existing_status', v_existing.status
    );
  END IF;

  -- Verificar si ya tiene historial en este año
  IF EXISTS (
    SELECT 1 FROM public.student_history
    WHERE student_id = p_student_id AND school_year_id = p_school_year_id
  ) THEN
    RETURN jsonb_build_object('can_enroll', false, 'error', 'El estudiante ya tiene historial en este año');
  END IF;

  RETURN jsonb_build_object('can_enroll', true, 'student_name', v_student.name);
END;
$$;
GRANT EXECUTE ON FUNCTION public.can_enroll_student(bigint, bigint) TO authenticated;

-- Estadísticas de un período
CREATE OR REPLACE FUNCTION public.get_period_stats(p_period_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public AS $$
DECLARE
  v_result jsonb;
  v_attendance record;
  v_grades record;
  v_tasks record;
BEGIN
  -- Asistencia del período
  SELECT
    count(*) as total_records,
    count(*) FILTER (WHERE status = 'present') as present_count,
    count(*) FILTER (WHERE status = 'absent') as absent_count,
    count(*) FILTER (WHERE status = 'late') as late_count
  INTO v_attendance
  FROM public.attendance
  WHERE academic_period_id = p_period_id;

  -- Promedio de calificaciones del período
  SELECT
    count(*) as total_grades,
    COALESCE(avg(score), 0) as avg_score
  INTO v_grades
  FROM public.grades
  WHERE period_id = p_period_id;

  -- Tareas del período
  SELECT count(*) as total_tasks
  INTO v_tasks
  FROM public.tasks
  WHERE period_id = p_period_id;

  v_result := jsonb_build_object(
    'attendance', jsonb_build_object(
      'total', v_attendance.total_records,
      'present', v_attendance.present_count,
      'absent', v_attendance.absent_count,
      'late', v_attendance.late_count,
      'pct', CASE WHEN v_attendance.total_records > 0
        THEN round((v_attendance.present_count::numeric / v_attendance.total_records * 100), 1)
        ELSE 0 END
    ),
    'grades', jsonb_build_object(
      'total', v_grades.total_grades,
      'average', round(v_grades.avg_score, 1)
    ),
    'tasks', jsonb_build_object(
      'total', v_tasks.total_tasks
    )
  );

  RETURN v_result;
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_period_stats(bigint) TO authenticated;

-- Datos del año escolar para la maestra
CREATE OR REPLACE FUNCTION public.get_teacher_year_data(p_teacher_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public AS $$
DECLARE
  v_year jsonb;
  v_periods jsonb;
  v_classrooms jsonb;
BEGIN
  v_year := public.get_active_school_year();
  v_periods := public.get_periods_for_year((v_year->>'id')::bigint);

  -- Aulas asignadas a la maestra en el año activo
  SELECT jsonb_agg(jsonb_build_object(
    'id', c.id,
    'name', c.name,
    'level', c.level,
    'capacity', c.capacity
  )) INTO v_classrooms
  FROM public.classrooms c
  WHERE c.teacher_id = p_teacher_id;

  RETURN jsonb_build_object(
    'school_year', v_year,
    'periods', COALESCE(v_periods, '[]'::jsonb),
    'classrooms', COALESCE(v_classrooms, '[]'::jsonb)
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_teacher_year_data(uuid) TO authenticated;

-- Datos del año escolar para el padre
CREATE OR REPLACE FUNCTION public.get_parent_year_data(p_parent_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public AS $$
DECLARE
  v_year jsonb;
  v_periods jsonb;
  v_students jsonb;
  v_history jsonb;
BEGIN
  v_year := public.get_active_school_year();

  IF (v_year->>'id') IS NOT NULL THEN
    v_periods := public.get_periods_for_year((v_year->>'id')::bigint);
  ELSE
    v_periods := '[]'::jsonb;
  END IF;

  -- Estudiantes del padre en el año activo
  SELECT jsonb_agg(jsonb_build_object(
    'id', s.id,
    'name', s.name,
    'classroom_id', s.classroom_id,
    'classroom_name', c.name,
    'grade_level', c.level,
    'enrollment_type', s.enrollment_type
  )) INTO v_students
  FROM public.students s
  LEFT JOIN public.classrooms c ON c.id = s.classroom_id
  WHERE s.parent_id = p_parent_id AND s.deleted_at IS NULL;

  -- Historial del padre (todos los años)
  SELECT jsonb_agg(
    jsonb_build_object(
      'school_year_name', sy.name,
      'grade_level', sh.grade_level,
      'classroom_name', sh.classroom_name,
      'teacher_name', sh.teacher_name,
      'average_score', sh.average_score,
      'attendance_pct', sh.attendance_pct,
      'status', sh.status
    ) ORDER BY sy.start_date DESC
  ) INTO v_history
  FROM public.student_history sh
  JOIN public.school_years sy ON sy.id = sh.school_year_id
  WHERE sh.student_id IN (
    SELECT id FROM public.students WHERE parent_id = p_parent_id
  );

  RETURN jsonb_build_object(
    'school_year', v_year,
    'periods', COALESCE(v_periods, '[]'::jsonb),
    'students', COALESCE(v_students, '[]'::jsonb),
    'history', COALESCE(v_history, '[]'::jsonb)
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_parent_year_data(uuid) TO authenticated;

-- Cerrar año escolar y archivar
CREATE OR REPLACE FUNCTION public.close_school_year(p_school_year_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_year record;
  v_role text;
  v_closed_periods int;
  v_student record;
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role NOT IN ('directora', 'admin') THEN
    RETURN jsonb_build_object('error', 'Solo la directora puede cerrar años escolares');
  END IF;

  SELECT * INTO v_year FROM public.school_years WHERE id = p_school_year_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Año escolar no encontrado');
  END IF;

  -- Verificar que todos los períodos estén cerrados
  SELECT count(*) INTO v_closed_periods
  FROM public.academic_periods
  WHERE school_year_id = p_school_year_id AND status != 'closed';

  IF v_closed_periods > 0 THEN
    RETURN jsonb_build_object(
      'error', 'Todos los períodos deben estar cerrados antes de cerrar el año escolar',
      'pending_periods', v_closed_periods
    );
  END IF;

  -- Archivar estudiantes activos al historial
  FOR v_student IN
    SELECT s.*, c.name as classroom_name, c.level as grade_level,
      (SELECT name FROM public.profiles WHERE id = c.teacher_id) as teacher_name
    FROM public.students s
    LEFT JOIN public.classrooms c ON c.id = s.classroom_id
    WHERE s.school_year_id = p_school_year_id AND s.is_active = true AND s.deleted_at IS NULL
  LOOP
    INSERT INTO public.student_history (
      student_id, student_name, school_year_id, classroom_id,
      classroom_name, teacher_name, grade_level, status
    ) VALUES (
      v_student.id, v_student.name, p_school_year_id, v_student.classroom_id,
      v_student.classroom_name, v_student.teacher_name, v_student.grade_level, 'active'
    ) ON CONFLICT (student_id, school_year_id) DO NOTHING;
  END LOOP;

  -- Cambiar estado del año
  UPDATE public.school_years SET status = 'archived' WHERE id = p_school_year_id;

  -- Desactivar todos los períodos
  UPDATE public.academic_periods
  SET status = 'closed', is_active = false
  WHERE school_year_id = p_school_year_id;

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Año escolar cerrado y archivado correctamente',
    'school_year_name', v_year.name
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.close_school_year(bigint) TO authenticated;

-- Promover estudiantes al siguiente grado
CREATE OR REPLACE FUNCTION public.promote_students(p_school_year_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_role text;
  v_student record;
  v_promoted int := 0;
  v_retained int := 0;
  v_year record;
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role NOT IN ('directora', 'admin') THEN
    RETURN jsonb_build_object('error', 'Solo la directora puede promover estudiantes');
  END IF;

  SELECT * INTO v_year FROM public.school_years WHERE id = p_school_year_id;
  IF NOT FOUND OR v_year.status != 'archived' THEN
    RETURN jsonb_build_object('error', 'El año escolar debe estar archivado para promover');
  END IF;

  -- Promover cada estudiante en el historial
  FOR v_student IN
    SELECT sh.*, s.is_active
    FROM public.student_history sh
    JOIN public.students s ON s.id = sh.student_id
    WHERE sh.school_year_id = p_school_year_id AND sh.status = 'active'
  LOOP
    -- Verificar reglas de promoción (min average 70, min attendance 80)
    IF COALESCE(v_student.average_score, 100) >= 70
       AND COALESCE(v_student.attendance_pct, 100) >= 80 THEN
      UPDATE public.student_history SET status = 'promoted' WHERE id = v_student.id;
      v_promoted := v_promoted + 1;
    ELSE
      UPDATE public.student_history SET status = 'retained' WHERE id = v_student.id;
      v_retained := v_retained + 1;
    END IF;
  END LOOP;

  RETURN jsonb_build_object(
    'success', true,
    'promoted', v_promoted,
    'retained', v_retained,
    'message', v_promoted || ' estudiantes promovidos, ' || v_retained || ' requieren repetir'
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.promote_students(bigint) TO authenticated;

-- Obtener historial de un estudiante
CREATE OR REPLACE FUNCTION public.get_student_history(p_student_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public AS $$
DECLARE
  v_result jsonb;
BEGIN
  SELECT jsonb_agg(
    jsonb_build_object(
      'id', sh.id,
      'school_year_name', sy.name,
      'academic_period_name', ap.name,
      'grade_level', sh.grade_level,
      'classroom_name', sh.classroom_name,
      'teacher_name', sh.teacher_name,
      'average_score', sh.average_score,
      'attendance_pct', sh.attendance_pct,
      'total_days', sh.total_days,
      'absent_days', sh.absent_days,
      'late_days', sh.late_days,
      'status', sh.status,
      'notes', sh.notes
    ) ORDER BY sy.start_date DESC, ap.order_index
  ) INTO v_result
  FROM public.student_history sh
  JOIN public.school_years sy ON sy.id = sh.school_year_id
  LEFT JOIN public.academic_periods ap ON ap.id = sh.academic_period_id
  WHERE sh.student_id = p_student_id;

  RETURN COALESCE(v_result, '[]'::jsonb);
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_student_history(bigint) TO authenticated;

-- Trigger para updated_at en school_years
CREATE OR REPLACE FUNCTION public.update_school_year_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS tr_update_school_year_timestamp ON public.school_years;
CREATE TRIGGER tr_update_school_year_timestamp
  BEFORE UPDATE ON public.school_years
  FOR EACH ROW EXECUTE FUNCTION public.update_school_year_timestamp();

-- ── 6. GRANTS ─────────────────────────────────────────────────
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
