-- ============================================================
-- MIGRACIÓN: Security Hardening — Panel Maestra
-- Fecha: 2026-08-18
-- Descripción: Fix task_evidences RLS + audit_logs table
-- ============================================================

-- 1. FIX: task_evidences RLS — era demasiado permisiva (auth.uid() IS NOT NULL)
-- Solo staff con acceso al aula y padres de alumnos pueden ver/modificar evidencias

DROP POLICY IF EXISTS "evidences_all" ON public.task_evidences;
DROP POLICY IF EXISTS "evidences_staff" ON public.task_evidences;
DROP POLICY IF EXISTS "evidences_teacher" ON public.task_evidences;
DROP POLICY IF EXISTS "evidences_parent_insert" ON public.task_evidences;
DROP POLICY IF EXISTS "evidences_parent_select" ON public.task_evidences;

CREATE POLICY "evidences_staff" ON public.task_evidences FOR ALL
  USING (
    get_my_role() IN ('directora','asistente','maestra','admin')
    AND is_classroom_accessible(
      (SELECT t.classroom_id FROM public.tasks t WHERE t.id = task_evidences.task_id)
    )
  );

CREATE POLICY "evidences_parent_select" ON public.task_evidences FOR SELECT
  USING (
    auth.uid() IS NOT NULL
    AND (
      EXISTS (SELECT 1 FROM public.students s WHERE s.id = task_evidences.student_id AND s.parent_id = auth.uid())
      OR EXISTS (SELECT 1 FROM public.tasks t
                 JOIN public.students st ON st.classroom_id = t.classroom_id
                 WHERE t.id = task_evidences.task_id AND st.parent_id = auth.uid())
    )
  );

CREATE POLICY "evidences_parent_insert" ON public.task_evidences FOR INSERT
  WITH CHECK (
    auth.uid() IS NOT NULL
    AND EXISTS (SELECT 1 FROM public.students s WHERE s.id = task_evidences.student_id AND s.parent_id = auth.uid())
  );

-- 2. TABLA: audit_logs — Registro de cambios en rutina y asistencia
-- La tabla audit_logs puede existir ya con estructura vieja (id, user_id, action, payload, created_at).
-- Usamos ALTER TABLE para agregar las columnas faltantes de forma segura.
DO $$
BEGIN
  -- Crear solo si no existe (primera vez)
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'audit_logs') THEN
    CREATE TABLE public.audit_logs (
      id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id       uuid REFERENCES auth.users(id) ON DELETE SET NULL,
      action        text NOT NULL,
      table_name    text NOT NULL,
      record_id     bigint,
      classroom_id  bigint REFERENCES public.classrooms(id),
      old_value     jsonb,
      new_value     jsonb,
      metadata      jsonb DEFAULT '{}',
      created_at    timestamp with time zone DEFAULT now() NOT NULL
    );
  ELSE
    -- Agregar columnas faltantes a tabla existente
    ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS table_name text;
    ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS record_id bigint;
    ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS classroom_id bigint REFERENCES public.classrooms(id);
    ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS old_value jsonb;
    ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS new_value jsonb;
    ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}';
  END IF;
END $$;

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Solo staff del aula puede ver logs de auditoría de su aula
CREATE POLICY "audit_logs_staff" ON public.audit_logs FOR ALL
  USING (
    get_my_role() IN ('directora','asistente','admin')
    OR (
      get_my_role() = 'maestra'
      AND is_classroom_accessible(classroom_id)
    )
  );

CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON public.audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_table ON public.audit_logs (table_name, record_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_classroom ON public.audit_logs (classroom_id, created_at DESC);

-- 3. FUNCIÓN: Registrar cambio en auditoría
CREATE OR REPLACE FUNCTION public.log_audit_change(
  p_action text,
  p_table_name text,
  p_record_id bigint,
  p_classroom_id bigint,
  p_old_value jsonb DEFAULT NULL,
  p_new_value jsonb DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.audit_logs (user_id, action, table_name, record_id, classroom_id, old_value, new_value, metadata)
  VALUES (auth.uid(), p_action, p_table_name, p_record_id, p_classroom_id, p_old_value, p_new_value, p_metadata);
END;
$$;

-- 4. daily_logs pasados → solo lectura para maestras
-- (La directora/admin puede modificar registros de días anteriores)
DROP POLICY IF EXISTS "daily_logs_staff" ON public.daily_logs;
CREATE POLICY "daily_logs_staff" ON public.daily_logs FOR ALL
  USING (
    get_my_role() IN ('directora','asistente','admin')
    OR (
      get_my_role() = 'maestra'
      AND is_classroom_accessible(classroom_id)
      AND date >= CURRENT_DATE
    )
  );

-- 5. Asistencia: maestra no puede modificar asistencias de otras aulas
DROP POLICY IF EXISTS "attendance_staff" ON public.attendance;
CREATE POLICY "attendance_staff" ON public.attendance FOR ALL
  USING (
    get_my_role() IN ('directora','asistente','admin')
    OR (
      get_my_role() = 'maestra'
      AND is_classroom_accessible(classroom_id)
    )
  );
