-- ============================================================
-- 🔒 KARPUS KIDS — Guía de Backup y Seguridad
-- Ejecutar en Supabase SQL Editor
-- ============================================================

-- ── 1. BACKUP MANUAL (Exportar datos críticos) ────────────────
-- Ejecuta estas queries en Supabase SQL Editor → Download CSV

-- Estudiantes completos
-- SELECT * FROM public.students ORDER BY name;

-- Pagos del año actual
-- SELECT p.*, s.name as student_name FROM public.payments p
-- JOIN public.students s ON s.id = p.student_id
-- WHERE extract(year from created_at) = extract(year from now())
-- ORDER BY created_at DESC;

-- Asistencia del mes actual
-- SELECT a.*, s.name as student_name FROM public.attendance a
-- JOIN public.students s ON s.id = a.student_id
-- WHERE date >= date_trunc('month', now())
-- ORDER BY date DESC;

-- ── 2. FUNCIÓN DE BACKUP AUTOMÁTICO ──────────────────────────
-- Crea una tabla de snapshots para auditoría

create table if not exists public.data_snapshots (
  id         bigint generated by default as identity primary key,
  table_name text not null,
  row_count  integer,
  snapshot   jsonb,
  created_at timestamp with time zone default now()
);
alter table public.data_snapshots enable row level security;
drop policy if exists "solo_directora_snapshots" on public.data_snapshots;
create policy "solo_directora_snapshots" on public.data_snapshots
  for all using (get_my_role() = 'directora');

-- Función para crear snapshot de estudiantes
create or replace function public.create_students_snapshot()
returns void language plpgsql security definer as $$
begin
  insert into public.data_snapshots (table_name, row_count, snapshot)
  select
    'students',
    count(*)::integer,
    jsonb_agg(row_to_json(s))
  from public.students s;
end;
$$;
grant execute on function public.create_students_snapshot to authenticated;

-- Función para crear snapshot de pagos del mes
create or replace function public.create_payments_snapshot()
returns void language plpgsql security definer as $$
begin
  insert into public.data_snapshots (table_name, row_count, snapshot)
  select
    'payments_' || to_char(now(), 'YYYY_MM'),
    count(*)::integer,
    jsonb_agg(row_to_json(p))
  from public.payments p
  where extract(month from created_at) = extract(month from now())
    and extract(year  from created_at) = extract(year  from now());
end;
$$;
grant execute on function public.create_payments_snapshot to authenticated;

-- ── 3. SEGURIDAD ADICIONAL ────────────────────────────────────

-- Tabla de intentos de login fallidos (para auditoría)
create table if not exists public.login_attempts (
  id         bigint generated by default as identity primary key,
  email      text,
  ip_hash    text,  -- hash de IP para privacidad
  success    boolean default false,
  created_at timestamp with time zone default now()
);
alter table public.login_attempts enable row level security;
drop policy if exists "solo_directora_login_attempts" on public.login_attempts;
create policy "solo_directora_login_attempts" on public.login_attempts
  for all using (get_my_role() = 'directora');
-- Inserción pública (para registrar intentos)
drop policy if exists "insert_login_attempts" on public.login_attempts;
create policy "insert_login_attempts" on public.login_attempts
  for insert with check (true);

-- Limpiar intentos viejos (más de 30 días)
create or replace function public.cleanup_old_login_attempts()
returns void language sql security definer as $$
  delete from public.login_attempts
  where created_at < now() - interval '30 days';
$$;

-- ── 4. ÍNDICES DE SEGURIDAD ───────────────────────────────────
-- Evitar enumeración de usuarios por email
create index if not exists idx_profiles_email_lower
  on public.profiles(lower(email));

-- Índice para audit_logs (búsqueda rápida por acción)
create index if not exists idx_audit_logs_created
  on public.audit_logs(created_at desc);

-- ── 5. CONFIGURACIÓN RECOMENDADA EN SUPABASE DASHBOARD ───────
-- Authentication → Settings:
--   ✅ Enable email confirmations
--   ✅ Secure email change
--   ✅ Enable MFA (Multi-Factor Authentication)
--   ✅ Set minimum password length: 8
--   ✅ Password strength: Strong
--   ✅ Rate limiting: Enable (ya incluido en Supabase Auth)
--
-- Database → Extensions:
--   ✅ pg_cron (para backups automáticos)
--
-- Backups automáticos (requiere plan Pro):
--   Dashboard → Settings → Backups → Enable daily backups
--
-- ── 6. CRON DE BACKUP SEMANAL (requiere pg_cron) ─────────────
-- select cron.schedule(
--   'weekly-students-backup',
--   '0 2 * * 0',  -- Domingos a las 2am
--   'select public.create_students_snapshot()'
-- );
-- select cron.schedule(
--   'monthly-payments-backup',
--   '0 3 1 * *',  -- Día 1 de cada mes a las 3am
--   'select public.create_payments_snapshot()'
-- );

-- ── 7. NOTIFICAR SCHEMA CACHE (ejecutar después de cambios) ───
notify pgrst, 'reload schema';
