-- ==========================================================================
-- KARPUS KIDS / MIGRACION CONSOLIDADA 2/10 - ESQUEMA PAGOS: pagos, conceptos de cobro, cargos del estudiante
--
-- Generada por auditoria de los 36 archivos de migraciones/operativos/ y
-- los 8 de supabase/migrations/ (44 fuentes en total). Esta migracion y las 9
-- restantes son las unicas que se conservan: las 44 fuentes originales se
-- eliminaron del repositorio tras consolidar y corregir sus defectos.
--
-- IDEMPOTENTE: se puede aplicar sobre la base ya desplegada sin perder datos.
-- Ejecutar en orden 01 -> 10 (ver README de migraciones).
-- ==========================================================================


-- ---- payments ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payments (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id           bigint REFERENCES public.students(id) ON DELETE CASCADE,
  amount               numeric(10,2) NOT NULL,
  concept              text DEFAULT 'Mensualidad',
  status               text DEFAULT 'pending',
  month_paid           text,
  due_date             date,
  paid_date            timestamp with time zone,
  method               text,
  bank                 text,
  reference            text,
  proof_url            text,
  evidence_url         text,
  notes                text,
  validated_by         uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  last_reminder_sent   timestamp with time zone,
  deleted_at           timestamp with time zone,
  updated_at           timestamp with time zone DEFAULT now(),
  created_at           timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- payment_concepts ----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payment_concepts (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           text NOT NULL,
  type           text NOT NULL DEFAULT 'mensualidad'
                 CHECK (type IN ('inscripcion','mensualidad','prolongado','materiales','kit','servicio','otro')),
  default_amount numeric(10,2) DEFAULT 0,
  is_active      boolean DEFAULT true,
  sort_order     int DEFAULT 0,
  created_at     timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- student_charges -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_charges (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  concept_id   bigint REFERENCES public.payment_concepts(id) ON DELETE SET NULL,
  concept      text NOT NULL,
  type         text NOT NULL DEFAULT 'mensualidad'
               CHECK (type IN ('inscripcion','mensualidad','prolongado','materiales','kit','servicio','otro')),
  amount       numeric(10,2) NOT NULL DEFAULT 0,
  discount_pct numeric(5,2)  NOT NULL DEFAULT 0,
  amount_net   numeric(10,2) NOT NULL DEFAULT 0,
  month_paid   text,
  due_date     date,
  status       text NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','review','paid','waived')),
  method       text,
  reference    text,
  proof_url    text,
  paid_date    timestamp with time zone,
  notes        text,
  created_by   uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(student_id, concept, month_paid)
);


-- ---- ALTER TABLE de este bloque ------------------------------------------
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS last_reminder_sent TIMESTAMP WITH TIME ZONE;

ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS validated_by UUID REFERENCES public.profiles(id);

ALTER TABLE public.payment_concepts DROP CONSTRAINT IF EXISTS payment_concepts_type_check;

ALTER TABLE public.payment_concepts
  ADD CONSTRAINT payment_concepts_type_check
  CHECK (type IN ('inscripcion','mensualidad','prolongado','materiales','kit','servicio','reinscripcion','otro'));

ALTER TABLE public.student_charges DROP CONSTRAINT IF EXISTS student_charges_type_check;

ALTER TABLE public.student_charges
  ADD CONSTRAINT student_charges_type_check
  CHECK (type IN ('inscripcion','mensualidad','prolongado','materiales','kit','servicio','reinscripcion','otro'));

ALTER TABLE public.payments
  ADD COLUMN IF NOT EXISTS original_amount numeric(10,2),
  ADD COLUMN IF NOT EXISTS discount_pct    numeric(5,2)  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_amount numeric(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_reason text;


-- ---- Seeds idempotentes --------------------------------------------------
INSERT INTO public.payment_concepts (name, type, default_amount, sort_order) VALUES
  ('Inscripción',          'inscripcion',   2000,  1),
  ('Mensualidad',          'mensualidad',   4500,  2),
  ('Día Prolongado',       'prolongado',    1500,  3),
  ('Kit de Libros',        'kit',           1500,  4),
  ('Uniformes',            'servicio',       800,  5),
  ('Cuota Única Anual',    'mensualidad',   45000, 6),
  ('Semestre I',           'mensualidad',   22500, 7),
  ('Semestre II',          'mensualidad',   22500, 8)
ON CONFLICT DO NOTHING;

INSERT INTO public.payment_concepts (name, type, default_amount, sort_order)
SELECT 'Reinscripción', 'reinscripcion', 2000, 1
WHERE NOT EXISTS (SELECT 1 FROM public.payment_concepts WHERE name = 'Reinscripción');


-- ---- Backfills historicos EXCLUIDOS a proposito --------------------------
-- Un INSERT en payments con mes fijo (p. ej. 2026-05) queda fuera de la
-- consolidacion: volver a aplicarlo generaria cobros de meses ya cerrados.
-- El unico generador de cobros es run_payment_cycle() / generate_student_charges().
-- (venia de migraciones/operativos/11_limpieza_pagos_incorrectos.sql)

