-- ==========================================================================
-- KARPUS KIDS / MIGRACION CONSOLIDADA 3/10 - ESQUEMA ACADEMICO: asignaturas, actividades, calificaciones, boletines
--
-- Generada por auditoria de los 36 archivos de migraciones/operativos/ y
-- los 8 de supabase/migrations/ (44 fuentes en total). Esta migracion y las 9
-- restantes son las unicas que se conservan: las 44 fuentes originales se
-- eliminaron del repositorio tras consolidar y corregir sus defectos.
--
-- IDEMPOTENTE: se puede aplicar sobre la base ya desplegada sin perder datos.
-- Ejecutar en orden 01 -> 10 (ver README de migraciones).
-- ==========================================================================


-- ---- subjects ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.subjects (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            text NOT NULL UNIQUE,
  education_level text,
  description     text,
  is_active       boolean DEFAULT true,
  created_at      timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- period_config -------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.period_config (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id       bigint REFERENCES public.periods(id) ON DELETE CASCADE NOT NULL,
  subject_id      bigint REFERENCES public.subjects(id) ON DELETE CASCADE NOT NULL,
  activity_count  int NOT NULL CHECK (activity_count >= 5 AND activity_count <= 8),
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(period_id, subject_id)
);


-- ---- activities ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.activities (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_id       bigint REFERENCES public.period_config(id) ON DELETE CASCADE NOT NULL,
  title           text NOT NULL,
  description     text,
  max_score       numeric(5,2) DEFAULT 100,
  activity_number int NOT NULL,
  is_mandatory    boolean DEFAULT true,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(config_id, activity_number)
);


-- ---- grades --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.grades (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id    bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id  bigint REFERENCES public.classrooms(id),
  period_id     bigint REFERENCES public.periods(id),
  school_year_id bigint REFERENCES public.school_years(id),
  activity_id   bigint,
  subject       text,
  score         numeric(4,2),
  score_v2      numeric(5,2) CHECK (score_v2 >= 0 AND score_v2 <= 100),
  period        text,
  teacher_id    uuid REFERENCES public.profiles(id),
  notes         text,
  created_at    timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- subject_averages ----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.subject_averages (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE NOT NULL,
  period_id    bigint REFERENCES public.periods(id) ON DELETE CASCADE NOT NULL,
  subject_id   bigint REFERENCES public.subjects(id) ON DELETE CASCADE NOT NULL,
  average      numeric(5,2) NOT NULL,
  graded_count int NOT NULL DEFAULT 0,
  method       text DEFAULT 'best_5' CHECK (method IN ('best_5','all')),
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(student_id, period_id, subject_id)
);


-- ---- report_cards --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.report_cards (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id     bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id   bigint REFERENCES public.classrooms(id),
  period_id      bigint REFERENCES public.periods(id),
  school_year_id bigint REFERENCES public.school_years(id),
  task_avg       numeric(4,2),
  formal_avg     numeric(4,2),
  final_score    numeric(4,2),
  level          text,
  teacher_comment text,
  generated_at   timestamp with time zone DEFAULT now(),
  UNIQUE(student_id, period_id)
);


-- ---- ALTER TABLE de este bloque ------------------------------------------
ALTER TABLE public.grades ADD COLUMN IF NOT EXISTS score_v2 numeric(5,2) CHECK (score_v2 >= 0 AND score_v2 <= 100);

ALTER TABLE public.grades DROP CONSTRAINT IF EXISTS fk_grades_activity;

ALTER TABLE public.grades ADD CONSTRAINT fk_grades_activity
  FOREIGN KEY (activity_id) REFERENCES public.activities(id) ON DELETE CASCADE
  NOT VALID;

ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE;

ALTER TABLE public.period_config ADD COLUMN IF NOT EXISTS classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE;

ALTER TABLE public.report_cards ADD COLUMN IF NOT EXISTS fortalezas        text[] DEFAULT '{}';

ALTER TABLE public.report_cards ADD COLUMN IF NOT EXISTS debilidades       text[] DEFAULT '{}';

ALTER TABLE public.report_cards ADD COLUMN IF NOT EXISTS directora_comment text;

ALTER TABLE public.report_cards ADD COLUMN IF NOT EXISTS conducta          text;

ALTER TABLE public.report_cards ADD COLUMN IF NOT EXISTS qr_code           text;

ALTER TABLE public.report_cards ADD COLUMN IF NOT EXISTS pdf_url           text;

ALTER TABLE public.subjects
    DROP CONSTRAINT IF EXISTS subjects_education_level_check;

ALTER TABLE public.subjects
    ALTER COLUMN education_level DROP NOT NULL;


-- ---- Seeds idempotentes --------------------------------------------------
INSERT INTO public.subjects (name, description)
SELECT v.name, v.description
FROM (VALUES
  ('Desarrollo Socioemocional', 'Habilidades socioemocionales'),
  ('Psicomotricidad',           'Desarrollo motor grueso y fino'),
  ('Lenguaje',                  'Expresión y comprensión verbal'),
  ('Descubrimiento del Entorno','Exploración del mundo'),
  ('Arte y Creatividad',        'Expresión artística'),
  ('Inglés',                    'Introducción al inglés'),
  ('Lenguaje y Comunicación',   'Lectura, escritura y comprensión'),
  ('Pensamiento Matemático',    'Números y lógica'),
  ('Exploración y Conocimiento','Ciencias naturales y sociales'),
  ('Arte y Expresión',          'Arte, música y dramatización'),
  ('Formación Cívica y Ética',  'Valores y ciudadanía'),
  ('Educación Física',          'Actividad física y salud'),
  ('Español',                   'Lengua y literatura'),
  ('Matemáticas',               'Aritmética, álgebra y geometría'),
  ('Ciencias Naturales',        'Biología, química y física básica'),
  ('Ciencias Sociales',         'Historia, geografía y sociedad'),
  ('Arte',                      'Artes visuales, música y teatro'),
  ('Tecnología',                'Herramientas digitales')
) AS v(name, description)
WHERE NOT EXISTS (SELECT 1 FROM public.subjects s WHERE s.name = v.name);


-- ---- Backfills historicos EXCLUIDOS a proposito --------------------------
-- Un INSERT en payments con mes fijo (p. ej. 2026-05) queda fuera de la
-- consolidacion: volver a aplicarlo generaria cobros de meses ya cerrados.
-- El unico generador de cobros es run_payment_cycle() / generate_student_charges().
-- (venia de migraciones/operativos/11_limpieza_pagos_incorrectos.sql)

