-- ==========================================================================
-- KARPUS KIDS / MIGRACION CONSOLIDADA 1/10 - ESQUEMA NUCLEO: perfiles, aulas, anios escolares, periodos, estudiantes, asistencia, tareas
--
-- Generada por auditoria de los 36 archivos de migraciones/operativos/ y
-- los 8 de supabase/migrations/ (44 fuentes en total). Esta migracion y las 9
-- restantes son las unicas que se conservan: las 44 fuentes originales se
-- eliminaron del repositorio tras consolidar y corregir sus defectos.
--
-- IDEMPOTENTE: se puede aplicar sobre la base ya desplegada sin perder datos.
-- Ejecutar en orden 01 -> 10 (ver README de migraciones).
-- ==========================================================================


-- ---- profiles ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id                  uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email               text UNIQUE,
  name                text,
  matricula           text UNIQUE,
  role                text CHECK (role IN ('directora','maestra','padre','asistente','admin')),
  avatar_url          text,
  phone               text,
  bio                 text,
  notes               text,
  access_code         text UNIQUE,
  qr_code             text,
  onesignal_player_id text,
  deleted_at          timestamp with time zone,
  is_active           boolean DEFAULT true,
  accepted_terms      boolean DEFAULT false,
  accepted_terms_at   timestamp with time zone,
  last_sign_in_at     timestamp with time zone,
  search_vector       tsvector GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(name,'') || ' ' || coalesce(email,'') || ' ' || coalesce(phone,''))
  ) STORED,
  created_at          timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- classrooms ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.classrooms (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  level      text,
  capacity   integer DEFAULT 20,
  teacher_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  is_live    boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- school_years --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.school_years (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                text NOT NULL,
  start_date          date NOT NULL,
  end_date            date NOT NULL,
  enrollment_start    date,
  enrollment_end      date,
  reenrollment_start  date,
  reenrollment_end    date,
  status              text DEFAULT 'draft'
                      CHECK (status IN ('draft','enrollment','reenrollment','active','closed','archived')),
  created_by          uuid REFERENCES public.profiles(id),
  created_at          timestamp with time zone DEFAULT now() NOT NULL,
  updated_at          timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT valid_dates CHECK (end_date > start_date),
  CONSTRAINT valid_enrollment CHECK (
    enrollment_start IS NULL OR enrollment_end IS NULL OR enrollment_end >= enrollment_start),
  CONSTRAINT valid_reenrollment CHECK (
    reenrollment_start IS NULL OR reenrollment_end IS NULL OR reenrollment_end >= reenrollment_start)
);


-- ---- academic_periods ----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.academic_periods (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_year_id  bigint NOT NULL REFERENCES public.school_years(id) ON DELETE CASCADE,
  name            text NOT NULL,
  start_date      date NOT NULL,
  end_date        date NOT NULL,
  order_index     integer NOT NULL DEFAULT 1,
  status          text DEFAULT 'pending' CHECK (status IN ('pending','open','closed')),
  is_active       boolean DEFAULT false,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT valid_period_dates CHECK (end_date > start_date),
  CONSTRAINT unique_period_order UNIQUE (school_year_id, order_index)
);


-- ---- periods -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.periods (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  start_date   date NOT NULL,
  end_date     date NOT NULL,
  status       text DEFAULT 'open' CHECK (status IN ('open','closed')),
  is_active    boolean DEFAULT false,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- students ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.students (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                    text NOT NULL,
  classroom_id            bigint REFERENCES public.classrooms(id) ON DELETE SET NULL,
  parent_id               uuid REFERENCES public.profiles(id),
  school_year_id          bigint REFERENCES public.school_years(id),
  academic_period_id      bigint REFERENCES public.academic_periods(id),
  is_active               boolean DEFAULT true,
  avatar_url              text,
  matricula               text,
  age                     integer,
  age_type                text DEFAULT 'años' CHECK (age_type IN ('años','meses')),
  schedule                text,
  start_date              date,
  blood_type              text,
  allergies               text,
  authorized_pickup       text,
  authorized_pickup_phone text,
  p1_name                 text, p1_phone text, p1_email text,
  p1_job                  text, p1_address text, p1_emergency_contact text,
  p2_name                 text, p2_phone text, p2_email text,
  p2_job                  text, p2_address text, p2_emergency_contact text,
  monthly_fee             numeric DEFAULT 0,
  prolongado_fee          numeric DEFAULT 0,
  due_day                 integer DEFAULT 5,
  qr_code                 text,
  enrollment_type         text DEFAULT 'new' CHECK (enrollment_type IN ('new','reenrollment')),
  enrolled_at             timestamp with time zone,
  deleted_at              timestamp with time zone,
  search_vector           tsvector GENERATED ALWAYS AS (
    to_tsvector('simple',
      coalesce(name,'') || ' ' || coalesce(matricula,'') || ' ' ||
      coalesce(p1_name,'') || ' ' || coalesce(p1_phone,''))
  ) STORED,
  created_at              timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- attendance ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id          bigint NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id        bigint NOT NULL REFERENCES public.classrooms(id),
  date                date DEFAULT current_date,
  status              text CHECK (status IN ('present','absent','late','retirado')),
  check_in            timestamp with time zone,
  check_out           timestamp with time zone,
  school_year_id      bigint REFERENCES public.school_years(id),
  academic_period_id  bigint REFERENCES public.academic_periods(id),
  created_at          timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(student_id, date)
);


-- ---- attendance_requests -------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance_requests (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint REFERENCES public.students(id) ON DELETE CASCADE,
  date       date NOT NULL,
  reason     text NOT NULL,
  note       text,
  status     text DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- tasks ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tasks (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id    bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  teacher_id      uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  period_id       bigint REFERENCES public.periods(id) ON DELETE SET NULL,
  school_year_id  bigint REFERENCES public.school_years(id),
  title           text NOT NULL,
  description     text,
  due_date        timestamp with time zone,
  file_url        text,
  grading_system  text DEFAULT 'letter_stars',
  created_at      timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- task_evidences ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.task_evidences (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id      bigint REFERENCES public.tasks(id) ON DELETE CASCADE,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
  parent_id    uuid REFERENCES public.profiles(id),
  file_url     text,
  comment      text,
  status       text DEFAULT 'submitted',
  grade_letter text CHECK (grade_letter IN ('A','B','C','D')),
  stars        integer CHECK (stars >= 1 AND stars <= 5),
  score_v2     numeric(5,2) CHECK (score_v2 >= 0 AND score_v2 <= 100),
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(task_id, student_id)
);


-- ---- ALTER TABLE de este bloque ------------------------------------------
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;

ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check
  CHECK (role IN ('directora','maestra','padre','asistente','admin'));

ALTER TABLE public.task_evidences ADD COLUMN IF NOT EXISTS score_v2 numeric(5,2) CHECK (score_v2 >= 0 AND score_v2 <= 100);

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS payment_plan text
  CHECK (payment_plan IN ('unico','doble','mensual'));

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS discount_pct numeric(5,2) DEFAULT 0;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS last_name text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS birth_date date;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS gender text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS nationality text DEFAULT 'Dominicana';

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS birthplace text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS province text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS municipality text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS sector text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS insurance text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS pediatrician text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS pediatrician_phone text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS medical_conditions text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS medications text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS food_restrictions text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS disabilities text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS vaccinations_complete boolean DEFAULT false;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emergency_protocol text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS authorized_people jsonb DEFAULT '[]';

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS documents jsonb DEFAULT '{}';

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS inscription_fee numeric(10,2) DEFAULT 0;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS school_year_requested text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS level_requested text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS estimated_entry_date date;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS has_siblings boolean DEFAULT false;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS sibling_name text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS login_email text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p1_relationship text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p1_cedula text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p1_whatsapp text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p1_occupation text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p1_workplace text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p2_relationship text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p2_cedula text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p2_whatsapp text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p2_occupation text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS p2_workplace text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emg_name text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emg_relationship text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emg_cedula text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emg_phone text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS medical_notes text;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS consents jsonb DEFAULT '{}';

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS signature_data text;

ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS config_id bigint REFERENCES public.period_config(id) ON DELETE SET NULL;

ALTER TABLE public.students
    ADD COLUMN IF NOT EXISTS entry_time time,
    ADD COLUMN IF NOT EXISTS exit_time  time;

ALTER TABLE public.students
  ADD COLUMN IF NOT EXISTS sibling_id BIGINT
    REFERENCES public.students(id) ON DELETE SET NULL;

ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS absence_reason text;


-- ---- Seeds idempotentes --------------------------------------------------
INSERT INTO public.profiles (id, email, name, role, accepted_terms, created_at)
VALUES ('c1e72617-ab8f-44c0-b1eb-cdd92eda62e7', 'impulsodigital@gmail.com', 'Administrador', 'admin', true, now())
ON CONFLICT (id) DO UPDATE SET role = 'admin', accepted_terms = true;

INSERT INTO public.profiles (id, email, name, role, accepted_terms, created_at)
  VALUES (
    'c1e72617-ab8f-44c0-b1eb-cdd92eda62e7',
    'impulsodigital@gmail.com',
    'Administrador',
    'admin',
    true,
    now()
  )
  ON CONFLICT (id) DO UPDATE SET
    role           = 'admin',
    email          = 'impulsodigital@gmail.com',
    accepted_terms = true;


-- ---- Backfills historicos EXCLUIDOS a proposito --------------------------
-- Un INSERT en payments con mes fijo (p. ej. 2026-05) queda fuera de la
-- consolidacion: volver a aplicarlo generaria cobros de meses ya cerrados.
-- El unico generador de cobros es run_payment_cycle() / generate_student_charges().
-- (venia de migraciones/operativos/11_limpieza_pagos_incorrectos.sql)

