-- ═══════════════════════════════════════════════════════════════════════════
-- 15 · MÓDULO DE DONACIONES Y RECAUDACIÓN DE FONDOS
-- Karpus Kids · Sistema de Filantropía
-- ═══════════════════════════════════════════════════════════════════════════
-- Objetivo:
--   1. Campañas de recaudación (donation_campaigns) visibles al público.
--   2. Registro de donaciones (donations) con código único de seguimiento.
--   3. RPC público register_donation (valida y genera ref DON-YYYY-XXXXXX).
--   4. RPC de staff: approve_donation (suma al recaudado de la campaña),
--      reject_donation y certify_donation (certificado deducible fiscal).
--   5. Row Level Security: anon solo ve campañas activas; directora/asistente/
--      admin gestionan todo; el registro público pasa por RPC SECURITY DEFINER.
-- ═══════════════════════════════════════════════════════════════════════════
-- Es idempotente: CREATE IF NOT EXISTS / CREATE OR REPLACE / DROP POLICY IF EXISTS.
-- Puede ejecutarse en Supabase → SQL Editor sin daño.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- 15.1 · TABLA: CAMPAÑAS DE DONACIÓN
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.donation_campaigns (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title           TEXT NOT NULL,
  description     TEXT,
  target_amount   NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (target_amount >= 0),
  raised_amount   NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (raised_amount >= 0),
  cover_image_url TEXT,
  images          TEXT[] NOT NULL DEFAULT '{}',   -- Galería de fotos de la campaña
  start_date      DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date        DATE,
  is_active       BOOLEAN NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 15.2 · TABLA: REGISTRO DE DONACIONES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.donations (
  id             UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  tracking_ref   TEXT UNIQUE NOT NULL,            -- Ej: DON-2026-X89F
  campaign_id    BIGINT REFERENCES public.donation_campaigns(id) ON DELETE SET NULL,
  donor_name     TEXT NOT NULL,
  donor_email    TEXT NOT NULL,
  donor_phone    TEXT,
  donor_tax_id   TEXT,                            -- Cédula o RNC
  is_company     BOOLEAN DEFAULT false,
  is_anonymous   BOOLEAN DEFAULT false,
  amount         NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  currency       TEXT NOT NULL DEFAULT 'DOP',
  payment_method TEXT NOT NULL CHECK (payment_method IN ('transfer','card','cash')),
  bank_name      TEXT,
  receipt_url    TEXT,                            -- Volante/justificante subido
  status         TEXT NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','approved','rejected','certified')),
  notes          TEXT,
  approved_by    UUID REFERENCES public.profiles(id),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 15.3 · ÍNDICES DE RENDIMIENTO
-- ─────────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_donation_campaigns_active
  ON public.donation_campaigns (is_active);
CREATE INDEX IF NOT EXISTS idx_donations_campaign
  ON public.donations (campaign_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_donations_status
  ON public.donations (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_donations_email
  ON public.donations (donor_email);
CREATE INDEX IF NOT EXISTS idx_donations_created
  ON public.donations (created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- 15.4 · ROW LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.donation_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations          ENABLE ROW LEVEL SECURITY;

-- Público (anon): solo campañas activas (página comercial index.html)
DROP POLICY IF EXISTS "donation_campaigns_anon_select" ON public.donation_campaigns;
CREATE POLICY "donation_campaigns_anon_select" ON public.donation_campaigns
  FOR SELECT TO anon
  USING (is_active = true);

-- Staff (directora/asistente/admin): ve y gestiona TAMBIÉN campañas inactivas
DROP POLICY IF EXISTS "donation_campaigns_staff" ON public.donation_campaigns;
CREATE POLICY "donation_campaigns_staff" ON public.donation_campaigns FOR ALL
  TO authenticated USING (get_my_role() IN ('directora','asistente','admin'))
  WITH CHECK (get_my_role() IN ('directora','asistente','admin'));

-- Staff gestiona todos los registros de donación (ver, aprobar, rechazar, certificar)
DROP POLICY IF EXISTS "donations_staff" ON public.donations;
CREATE POLICY "donations_staff" ON public.donations FOR ALL
  TO authenticated USING (get_my_role() IN ('directora','asistente','admin'))
  WITH CHECK (get_my_role() IN ('directora','asistente','admin'));

-- ─────────────────────────────────────────────────────────────────────────────
-- 15.5 · RPC PÚBLICO: REGISTRAR DONACIÓN CON REFERENCIA ÚNICA
-- SECURITY DEFINER: el anon no toca la tabla directamente; este procedimiento
-- valida todos los datos y devuelve jsonb con el código de seguimiento.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.register_donation(
  p_campaign_id     BIGINT DEFAULT NULL,
  p_donor_name      TEXT   DEFAULT NULL,
  p_donor_email     TEXT   DEFAULT NULL,
  p_donor_phone     TEXT   DEFAULT NULL,
  p_donor_tax_id    TEXT   DEFAULT NULL,
  p_is_company      BOOLEAN DEFAULT false,
  p_is_anonymous    BOOLEAN DEFAULT false,
  p_amount          NUMERIC DEFAULT 0,
  p_payment_method  TEXT   DEFAULT 'transfer',
  p_bank_name       TEXT   DEFAULT NULL,
  p_receipt_url     TEXT   DEFAULT NULL
) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_ref          TEXT;
  v_donation_id  UUID;
  v_name         TEXT;
  v_email        TEXT;
  v_method       TEXT;
BEGIN
  -- Validaciones de entrada
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'Monto de donación inválido';
  END IF;
  IF p_amount > 1000000 THEN
    RAISE EXCEPTION 'Monto excede el límite permitido';
  END IF;

  v_name := nullif(trim(p_donor_name), '');
  IF v_name IS NULL OR length(v_name) < 2 THEN
    RAISE EXCEPTION 'Nombre del donante requerido';
  END IF;

  v_email := lower(nullif(trim(p_donor_email), ''));
  IF v_email IS NULL OR v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' THEN
    RAISE EXCEPTION 'Correo electrónico inválido';
  END IF;

  v_method := nullif(trim(p_payment_method), '');
  IF v_method IS NULL OR v_method NOT IN ('transfer','card','cash') THEN
    RAISE EXCEPTION 'Método de pago inválido';
  END IF;

  IF p_campaign_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.donation_campaigns c
    WHERE c.id = p_campaign_id AND c.is_active = true
  ) THEN
    RAISE EXCEPTION 'Campaña no válida o inactiva';
  END IF;

  -- Referencia única de seguimiento: DON-YYYY-XXXXXX
  LOOP
    v_ref := 'DON-' || to_char(now(), 'YYYY') || '-'
             || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));
    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.donations WHERE tracking_ref = v_ref);
  END LOOP;

  INSERT INTO public.donations (
    tracking_ref, campaign_id, donor_name, donor_email, donor_phone,
    donor_tax_id, is_company, is_anonymous, amount, payment_method,
    bank_name, receipt_url, status
  ) VALUES (
    v_ref, p_campaign_id, v_name, v_email, nullif(trim(p_donor_phone), ''),
    nullif(trim(p_donor_tax_id), ''), coalesce(p_is_company, false),
    coalesce(p_is_anonymous, false), p_amount, v_method,
    nullif(trim(p_bank_name), ''), nullif(trim(p_receipt_url), ''), 'pending'
  ) RETURNING id INTO v_donation_id;

  RETURN jsonb_build_object(
    'success',       true,
    'donation_id',   v_donation_id,
    'tracking_ref',  v_ref,
    'amount',        p_amount,
    'currency',      'DOP',
    'message',       'Donación registrada correctamente'
  );
END;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 15.6 · RPC STAFF: APROBAR DONACIÓN (SUMA AL RECAUDADO DE LA CAMPAÑA)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.approve_donation(
  p_donation_id UUID
) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_amount       NUMERIC(12,2);
  v_campaign_id  BIGINT;
BEGIN
  IF get_my_role() NOT IN ('directora','asistente','admin') THEN
    RAISE EXCEPTION 'Acceso denegado: no autorizado';
  END IF;

  UPDATE public.donations
  SET status = 'approved', approved_by = auth.uid()
  WHERE id = p_donation_id AND status = 'pending'
  RETURNING amount, campaign_id INTO v_amount, v_campaign_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'message', 'Donación no encontrada o ya procesada');
  END IF;

  IF v_campaign_id IS NOT NULL THEN
    -- Bloqueo de fila para evitar pérdida de incrementos (lost update) en
    -- recaudaciones concurrentes sobre la misma campaña.
    PERFORM 1 FROM public.donation_campaigns
      WHERE id = v_campaign_id
      FOR UPDATE;

    UPDATE public.donation_campaigns
    SET raised_amount = raised_amount + v_amount
    WHERE id = v_campaign_id;
  END IF;

  RETURN jsonb_build_object('success', true, 'message', 'Donación aprobada exitosamente');
END;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 15.7 · RPC STAFF: RECHAZAR DONACIÓN
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.reject_donation(
  p_donation_id UUID,
  p_notes       TEXT DEFAULT NULL
) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF get_my_role() NOT IN ('directora','asistente','admin') THEN
    RAISE EXCEPTION 'Acceso denegado: no autorizado';
  END IF;

  UPDATE public.donations
  SET status = 'rejected', notes = coalesce(nullif(trim(p_notes), ''), notes), approved_by = auth.uid()
  WHERE id = p_donation_id AND status IN ('pending','approved');

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'message', 'Donación no encontrada o ya procesada');
  END IF;

  RETURN jsonb_build_object('success', true, 'message', 'Donación rechazada');
END;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 15.8 · RPC STAFF: CERTIFICAR DONACIÓN (CERTIFICADO DEDUCIBLE FISCAL)
-- Solo sobre donaciones ya aprobadas.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.certify_donation(
  p_donation_id UUID
) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF get_my_role() NOT IN ('directora','asistente','admin') THEN
    RAISE EXCEPTION 'Acceso denegado: no autorizado';
  END IF;

  UPDATE public.donations
  SET status = 'certified'
  WHERE id = p_donation_id AND status = 'approved';

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'message', 'Solo se puede certificar una donación aprobada');
  END IF;

  RETURN jsonb_build_object('success', true, 'message', 'Certificado emitido para la donación');
END;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 15.9 · CAMPAÑAS INICIALES (SEED)
-- Editable/pausable desde el panel de directora.
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO public.donation_campaigns
  (title, description, target_amount, cover_image_url, start_date, end_date, is_active)
VALUES
  ('Fondo de Becas Karpus 2026',
   'Ayuda a que niños de escasos recursos accedan a una educación de calidad con una beca completa.',
   250000.00, NULL, CURRENT_DATE, NULL, true),
  ('Remodelación del Patio de Juegos',
   'Renovemos juntos el área de recreación con equipos seguros, modernos y accesibles para todos.',
   120000.00, NULL, CURRENT_DATE, NULL, true),
  ('Programa de Nutrición Infantil',
   'Suministro de alimentación balanceada y seguimiento nutricional para los pequeños.',
   80000.00, NULL, CURRENT_DATE, NULL, true)
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────
-- VERIFICACIÓN
-- ─────────────────────────────────────────────────────────────────────────────
SELECT '15_donaciones' AS migracion,
       (SELECT count(*) FROM public.donation_campaigns) AS campañas,
       (SELECT count(*) FROM public.donations)          AS donaciones;

-- ═══════════════════════════════════════════════════════════════════════════
-- FIN DE LA MIGRACIÓN 15
-- ═══════════════════════════════════════════════════════════════════════════