-- ══════════════════════════════════════════════════════════════════════════════
-- KARPUS KIDS / MIGRACION 13 - SISTEMA MENSUAL DE EVALUACION DE CALIDAD
-- ══════════════════════════════════════════════════════════════════════════════
-- Implementa propuesta.md (Sistema Mensual de Evaluacion de Calidad).
--
-- Modulos (propuesta.md seccion 20):
--   1. quality_periods        Periodos de evaluacion (mes evaluado, apertura, cierre)
--   2. quality_questions      Catalogo de preguntas (Bloque A docente, Bloque B institucion)
--   3. quality_responses      Respuestas (una por periodo y estudiante)
--      quality_answers        Puntaje por pregunta
--      quality_actions        Acciones de mejora (seccion 15)
--      quality_alerts         Alertas de descenso / problema recurrente (seccion 12)
--      quality_reminders      Registro de recordatorios 1/7/15/25 (seccion 18)
--
-- Indicadores (seccion 9): vistas v_quality_* calculan IGSM, indice docente,
-- indice institucional y tasa de participacion.
--
-- Automatizacion (seccion 21): TODO en SQL con pg_cron. Una sola funcion
-- quality_daily() corre a diario y decide: abrir periodo si es dia 1, cerrar
-- periodos vencidos, calcular alertas y registrar recordatorios. No depende de
-- pg_net ni de Edge Functions.
--
-- Principios que se respetan del enunciado:
--   - Sin puntos, cupones, descuentos ni recompensas (seccion 17).
--   - Una sola evaluacion por periodo y estudiante (seccion 3).
--   - Una puntuacion baja NO es una deficiencia: genera "Alerta de revision"
--     y la Direccion decide (seccion 11).
--   - Los indicadores generales se muestran agregados, nunca por familia
--     (seccion 16). Comentarios pueden marcar envio anonyme.
-- ══════════════════════════════════════════════════════════════════════════════

BEGIN;

-- ──────────────────────────────────────────────────────────────────────────────
-- Modulo 1 - Periodos de evaluacion
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.quality_periods (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Primer dia del mes evaluado. Ej: 2026-09-01 evalua septiembre.
  period_month    date NOT NULL UNIQUE,
  -- Dia 1 del mes siguiente: se abre y se notifica.
  opens_at        timestamp with time zone NOT NULL,
  -- Ultimo instante en que se aceptan respuestas.
  closes_at       timestamp with time zone NOT NULL,
  status          text NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open','closed')),
  -- Contador desnormalizado; lo mantiene el trigger sync_quality_response_count.
  response_count  integer NOT NULL DEFAULT 0,
  created_at      timestamp with time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.quality_periods IS
  'Periodos de evaluacion mensual. period_month es el mes evaluado (dia 1); el periodo se abre el dia 1 del mes siguiente (seccion 3).';
COMMENT ON COLUMN public.quality_periods.period_month IS
  'Primer dia del mes evaluado. Ej: 2026-09-01 corresponde a la evaluacion de septiembre.';
COMMENT ON COLUMN public.quality_periods.status IS
  'open = acepta respuestas; closed = periodo finalizado, solo lectura.';

-- ──────────────────────────────────────────────────────────────────────────────
-- Modulo 2 - Catalogo de preguntas
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.quality_questions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- docente = Bloque A (seccion 6); institucion = Bloque B (seccion 7).
  block         text NOT NULL CHECK (block IN ('docente','institucion')),
  -- Clave estable: el codigo JS la usa, no el id, para no depender del seed.
  question_key  text NOT NULL UNIQUE,
  prompt        text NOT NULL,
  sort_order    integer NOT NULL DEFAULT 0,
  is_active     boolean NOT NULL DEFAULT true
);

COMMENT ON TABLE public.quality_questions IS
  'Catalogo de preguntas de la evaluacion mensual. Se siembra desde esta migracion; question_key es la clave estable usada por el cliente.';

-- ──────────────────────────────────────────────────────────────────────────────
-- Modulo 3 - Respuestas
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.quality_responses (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id     bigint NOT NULL REFERENCES public.quality_periods(id) ON DELETE CASCADE,
  student_id    bigint NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  parent_id     uuid  NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- Docente evaluada, resuelta al enviar (classrooms.teacher_id del alumno).
  -- Se congela aqui a proposito: si el alumno cambia de aula, la evaluacion
  -- historica debe seguir atribuyendose a quien lo atendio ese mes.
  teacher_id    uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  -- IGSM: Indicador General de Satisfaccion Mensual (seccion 8).
  overall_score smallint CHECK (overall_score BETWEEN 1 AND 5),
  teacher_comment  text,
  general_comment  text,
  -- "Deseo enviar este comentario de forma anonima" (seccion 16).
  comment_anonymous boolean NOT NULL DEFAULT false,
  created_at    timestamp with time zone NOT NULL DEFAULT now(),
  -- Seccion 3: el padre responde una sola vez por periodo.
  CONSTRAINT quality_responses_period_student_uniq UNIQUE (period_id, student_id)
);

COMMENT ON TABLE public.quality_responses IS
  'Respuesta de una familia a un periodo. El UNIQUE (period_id, student_id) impide responder dos veces el mismo mes (seccion 3).';
COMMENT ON COLUMN public.quality_responses.overall_score IS
  'IGSM: pregunta global de satisfaccion, escala 1-5 (seccion 8).';
COMMENT ON COLUMN public.quality_responses.comment_anonymous IS
  'true = el comentario se usa para analisis institucional sin mostrar la identidad del padre (seccion 16).';

CREATE TABLE IF NOT EXISTS public.quality_answers (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  response_id  bigint NOT NULL REFERENCES public.quality_responses(id) ON DELETE CASCADE,
  question_id  bigint NOT NULL REFERENCES public.quality_questions(id) ON DELETE RESTRICT,
  score        smallint NOT NULL CHECK (score BETWEEN 1 AND 5),
  created_at   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT quality_answers_response_question_uniq UNIQUE (response_id, question_id)
);

COMMENT ON TABLE public.quality_answers IS
  'Puntaje 1-5 de una pregunta concreta dentro de una respuesta.';

-- ──────────────────────────────────────────────────────────────────────────────
-- Modulo 4b - Acciones de mejora (seccion 15)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.quality_actions (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id    bigint REFERENCES public.quality_periods(id) ON DELETE SET NULL,
  title        text NOT NULL,
  description  text,
  responsible  text,
  status       text NOT NULL DEFAULT 'pendiente'
                 CHECK (status IN ('pendiente','revision','proceso','solucionado')),
  due_date     date,
  created_at   timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at  timestamp with time zone
);

COMMENT ON TABLE public.quality_actions IS
  'Acciones de mejora creadas por la Direccion a partir de un hallazgo. Cerrar la accion NO borra la evaluacion: solo se comprueba su efecto en el mes siguiente (seccion 15).';

-- ──────────────────────────────────────────────────────────────────────────────
-- Modulo 4c - Alertas (seccion 12)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.quality_alerts (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id     bigint NOT NULL REFERENCES public.quality_periods(id) ON DELETE CASCADE,
  kind          text NOT NULL CHECK (kind IN ('descenso','recurrente')),
  scope         text NOT NULL CHECK (scope IN ('docente','institucion')),
  teacher_id    uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- question_key de la dimension, o 'general' para el IGSM.
  dimension_key text,
  message       text NOT NULL,
  status        text NOT NULL DEFAULT 'pendiente'
                  CHECK (status IN ('pendiente','revision','proceso','solucionado')),
  created_at    timestamp with time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.quality_alerts IS
  'Alertas de seguimiento. kind=descenso (caida frente al periodo anterior); kind=recurrente (mismo tema reportado por varias familias). No son sanciones: disparan revision (seccion 11/12).';

-- ──────────────────────────────────────────────────────────────────────────────
-- Modulo 6 - Registro de recordatorios (seccion 18)
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.quality_reminders (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id   bigint NOT NULL REFERENCES public.quality_periods(id) ON DELETE CASCADE,
  parent_id   uuid  NOT NULL,
  student_id  bigint NOT NULL,
  -- Dia del ciclo: 1 apertura, 7 / 15 / 25 recordatorios.
  step        smallint NOT NULL CHECK (step IN (1,7,15,25)),
  created_at  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT quality_reminders_uniq UNIQUE (period_id, student_id, step)
);

COMMENT ON TABLE public.quality_reminders IS
  'Bitacora de recordatorios. El UNIQUE evita repetir el mismo paso, y solo se registra para familias que aun no respondieron (seccion 18).';


-- ──────────────────────────────────────────────────────────────────────────────
-- Indices
-- ──────────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_quality_periods_month    ON public.quality_periods (period_month DESC);
CREATE INDEX IF NOT EXISTS idx_quality_periods_status  ON public.quality_periods (status, closes_at);
CREATE INDEX IF NOT EXISTS idx_quality_responses_period ON public.quality_responses (period_id);
CREATE INDEX IF NOT EXISTS idx_quality_responses_parent ON public.quality_responses (parent_id, period_id);
CREATE INDEX IF NOT EXISTS idx_quality_responses_teacher ON public.quality_responses (teacher_id, period_id);
CREATE INDEX IF NOT EXISTS idx_quality_answers_response ON public.quality_answers (response_id);
CREATE INDEX IF NOT EXISTS idx_quality_questions_block  ON public.quality_questions (block, sort_order);
-- Idempotencia de las alertas. Un UNIQUE de columna NO sirve aqui: las alertas
-- institucionales tienen teacher_id NULL y Postgres considera los NULL distintos
-- entre si, asi que el cron volveria a insertar la misma alerta cada dia. El
-- indice sobre COALESCE si deduplica, y no depende de NULLS NOT DISTINCT (PG15+).
CREATE UNIQUE INDEX IF NOT EXISTS uq_quality_alerts_dim
  ON public.quality_alerts (period_id, kind, scope, dimension_key,
                            COALESCE(teacher_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX IF NOT EXISTS idx_quality_alerts_period    ON public.quality_alerts (period_id, status);
CREATE INDEX IF NOT EXISTS idx_quality_actions_period   ON public.quality_actions (period_id, status);
CREATE INDEX IF NOT EXISTS idx_quality_reminders_period ON public.quality_reminders (period_id, step);


-- ──────────────────────────────────────────────────────────────────────────────
-- Triggers
-- ──────────────────────────────────────────────────────────────────────────────

-- Mantiene quality_periods.response_count al día. El panel de Direccion lo lee
-- para pintar el conteo sin tener que agregar la tabla de respuestas.
CREATE OR REPLACE FUNCTION public.sync_quality_response_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_period bigint := COALESCE(NEW.period_id, OLD.period_id);
BEGIN
  UPDATE public.quality_periods
     SET response_count = (
           SELECT count(*)::int FROM public.quality_responses r WHERE r.period_id = v_period
         )
   WHERE id = v_period;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_quality_response_count ON public.quality_responses;
CREATE TRIGGER trg_sync_quality_response_count
AFTER INSERT OR UPDATE OR DELETE ON public.quality_responses
FOR EACH ROW EXECUTE FUNCTION public.sync_quality_response_count();

COMMENT ON FUNCTION public.sync_quality_response_count() IS
  'Recalcula quality_periods.response_count tras cada cambio en respuestas.';


-- ──────────────────────────────────────────────────────────────────────────────
-- Funciones de calculo (modulo 4 - Analitica)
-- ──────────────────────────────────────────────────────────────────────────────

-- Familias habilitadas para un periodo: alumnos activos con tutor asignado.
-- Es el denominador de la tasa de participacion (seccion 9.4).
-- No depende de que el periodo este abierto: los periodos cerrados tambien
-- necesitan su denominador para que el historico muestre la participacion real.
CREATE OR REPLACE FUNCTION public.quality_eligible_students(p_period_id bigint)
RETURNS bigint[]
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(array_agg(s.id), '{}')
  FROM public.students s
  WHERE COALESCE(s.is_active, true)
    AND s.deleted_at IS NULL
    AND s.parent_id IS NOT NULL;
$$;

COMMENT ON FUNCTION public.quality_eligible_students(bigint) IS
  'IDs de alumnos activos con tutor, el denominador de la tasa de participacion (seccion 9.4). No depende del estado del periodo, para que el historico cerrado tambien calcule.';


-- Periodo abierto actual (el que la encuesta del Panel de Padres debe mostrar).
CREATE OR REPLACE FUNCTION public.quality_open_period()
RETURNS public.quality_periods
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT * FROM public.quality_periods
  WHERE status = 'open'
    AND now() BETWEEN opens_at AND closes_at
  ORDER BY period_month DESC
  LIMIT 1;
$$;

COMMENT ON FUNCTION public.quality_open_period() IS
  'Periodo de evaluacion vigente para el Panel de Padres. NULL si no hay ninguno abierto.';


-- ──────────────────────────────────────────────────────────────────────────────
-- Vistas de analitica (seccion 9)
-- ──────────────────────────────────────────────────────────────────────────────

-- Promedio por dimension (pregunta) y por bloque, para un periodo.
CREATE OR REPLACE VIEW public.v_quality_dimension_scores AS
SELECT r.period_id,
       p.period_month,
       q.block,
       q.question_key,
       q.prompt,
       q.sort_order,
       count(*)::int                                    AS answers,
       round(avg(a.score)::numeric, 2)                   AS avg_score
  FROM public.quality_answers a
  JOIN public.quality_responses r ON r.id = a.response_id
  JOIN public.quality_questions q ON q.id = a.question_id
  JOIN public.quality_periods   p ON p.id = r.period_id
 GROUP BY r.period_id, p.period_month, q.block, q.question_key, q.prompt, q.sort_order;

COMMENT ON VIEW public.v_quality_dimension_scores IS
  'Promedio 1-5 por pregunta y periodo. Base de los indices docente/institucional y de las alertas de descenso (secciones 9 y 12).';


-- Indicadores por periodo: IGSM, indice docente, indice institucional, participacion.
CREATE OR REPLACE VIEW public.v_quality_period_summary AS
WITH resp AS (
  SELECT r.period_id, r.overall_score
    FROM public.quality_responses r
),
dim AS (
  SELECT period_id, block, avg(avg_score) AS block_avg
    FROM public.v_quality_dimension_scores
   GROUP BY period_id, block
)
SELECT p.id                                   AS period_id,
       p.period_month,
       p.status,
       p.opens_at,
       p.closes_at,
       (SELECT count(*) FROM resp x WHERE x.period_id = p.id)::int AS response_count,
       (SELECT count(*) FROM public.quality_eligible_students(p.id))::int AS eligible_count,
       -- Seccion 9.4: completadas / habilitadas. 0 elegibles -> NULL, no 0%
       CASE
         WHEN (SELECT count(*) FROM public.quality_eligible_students(p.id)) > 0
         THEN round(
                100.0 * (SELECT count(*) FROM resp x WHERE x.period_id = p.id)
                / (SELECT count(*) FROM public.quality_eligible_students(p.id)), 1)
         ELSE NULL
       END                                    AS participation_pct,
       -- Seccion 9.1 IGSM
       (SELECT round(avg(overall_score)::numeric, 2) FROM resp x WHERE x.period_id = p.id) AS igsm,
       -- Seccion 9.2 indice docente
       (SELECT round(block_avg::numeric, 2) FROM dim d WHERE d.period_id = p.id AND d.block = 'docente') AS teacher_index,
       -- Seccion 9.3 indice institucional
       (SELECT round(block_avg::numeric, 2) FROM dim d WHERE d.period_id = p.id AND d.block = 'institucion') AS institution_index
  FROM public.quality_periods p;

COMMENT ON VIEW public.v_quality_period_summary IS
  'Resumen ejecutivo por periodo: IGSM, indice docente, indice institucional y tasa de participacion (seccion 9).';


-- Matriz de docentes (seccion 11). No es un ranking: es una matriz por dimension.
-- El indice docente se calcula por respuesta y despues se promedia, para que el
-- IGSM no quede ponderado por cuantas respuestas trae cada docente.
CREATE OR REPLACE VIEW public.v_quality_teacher_matrix AS
WITH per_response AS (
  SELECT r.id,
         r.period_id,
         r.teacher_id,
         r.overall_score,
         avg(a.score) FILTER (WHERE q.block = 'docente') AS docente_score
    FROM public.quality_responses r
    JOIN public.quality_answers   a ON a.response_id = r.id
    JOIN public.quality_questions q ON q.id = a.question_id
   WHERE r.teacher_id IS NOT NULL
   GROUP BY r.id, r.period_id, r.teacher_id, r.overall_score
)
SELECT pr_.period_id,
       p.period_month,
       pr_.teacher_id,
       prof.name                        AS teacher_name,
       count(*)::int                    AS responses,
       round(avg(pr_.overall_score)::numeric, 2) AS igsm,
       round(avg(pr_.docente_score)::numeric, 2) AS teacher_index
  FROM per_response pr_
  JOIN public.quality_periods p ON p.id = pr_.period_id
  LEFT JOIN public.profiles prof ON prof.id = pr_.teacher_id
 GROUP BY pr_.period_id, p.period_month, pr_.teacher_id, prof.name;

COMMENT ON VIEW public.v_quality_teacher_matrix IS
  'Matriz de desempeño docente por periodo. responses permite a la Direccion ponderar por cantidad antes de interpretar (seccion 11).';


-- Detalle por docente x dimension, para pintar la matriz completa en el panel.
CREATE OR REPLACE VIEW public.v_quality_teacher_dimensions AS
SELECT r.period_id,
       p.period_month,
       r.teacher_id,
       pr.name         AS teacher_name,
       q.question_key,
       q.prompt,
       q.sort_order,
       count(*)::int                     AS answers,
       round(avg(a.score)::numeric, 2)   AS avg_score
  FROM public.quality_answers a
  JOIN public.quality_responses r  ON r.id = a.response_id
  JOIN public.quality_periods p    ON p.id = r.period_id
  JOIN public.quality_questions q  ON q.id = a.question_id
  JOIN public.profiles pr          ON pr.id = r.teacher_id
 GROUP BY r.period_id, p.period_month, r.teacher_id, pr.name,
          q.question_key, q.prompt, q.sort_order;

COMMENT ON VIEW public.v_quality_teacher_dimensions IS
  'Puntaje por docente y por dimension, base de la matriz de la seccion 11.';


-- Tendencias (seccion 14): una fila por periodo con los tres indices.
-- Es basically v_quality_period_summary ordenada; existe con nombre propio para
-- que el cliente no dependa del orden de la vista de resumen.
CREATE OR REPLACE VIEW public.v_quality_trends AS
SELECT period_month, status, response_count, participation_pct,
       igsm, teacher_index, institution_index
  FROM public.v_quality_period_summary
 ORDER BY period_month;

COMMENT ON VIEW public.v_quality_trends IS
  'Serie historica para graficas de tendencia (seccion 14).';


-- Familias que aun no responden el periodo abierto (para recordatorios).
CREATE OR REPLACE VIEW public.v_quality_pending AS
SELECT p.id AS period_id,
       p.period_month,
       s.id AS student_id,
       s.name AS student_name,
       s.parent_id,
       s.classroom_id,
       c.teacher_id
  FROM public.quality_periods p
  JOIN public.students s
    ON COALESCE(s.is_active, true) AND s.deleted_at IS NULL AND s.parent_id IS NOT NULL
  LEFT JOIN public.quality_responses r
    ON r.period_id = p.id AND r.student_id = s.id
  LEFT JOIN public.classrooms c ON c.id = s.classroom_id
 WHERE p.status = 'open'
   AND r.id IS NULL;

COMMENT ON VIEW public.v_quality_pending IS
  'Familias habilitadas que aun no respondieron el periodo abierto (seccion 18).';


-- Categorias de comentarios (seccion 13). Clasificacion por palabra clave;
-- 'Otros' cuando no matchea ninguna. Es una heuristica, no un clasificador.
CREATE OR REPLACE FUNCTION public.quality_classify_comment(p_text text)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  t text := lower(coalesce(p_text, ''));
BEGIN
  IF t = '' THEN RETURN 'Otros'; END IF;
  IF t ~ '(comuni|inform|aviso|notific|llamada|mensaje)'                    THEN RETURN 'Comunicación'; END IF;
  IF t ~ '(comida|aliment|menu|almuerzo|desayuno|comida|snack|dieta)'       THEN RETURN 'Alimentación'; END IF;
  IF t ~ '(seguridad|segur|peligro|accidente|caida|herida)'                THEN RETURN 'Seguridad'; END IF;
  IF t ~ '(limpi|higien|baño|aseo|suci|olor)'                               THEN RETURN 'Limpieza'; END IF;
  IF t ~ '(docente|maestr|profesor|maestra|trato|atencion de la maestra)'  THEN RETURN 'Docentes'; END IF;
  IF t ~ '(activ|juego|jugar|recreo|parque)'                                THEN RETURN 'Actividades'; END IF;
  IF t ~ '(instalaci|sala|baño|taller|cocina|techo|edificio|espacio)'      THEN RETURN 'Instalaciones'; END IF;
  IF t ~ '(horario|entrada|salida|tarde|retraso|puntual)'                   THEN RETURN 'Horarios'; END IF;
  IF t ~ '(entrega|recogida|recoger|autoriza|familiar)'                     THEN RETURN 'Entrega y salida'; END IF;
  IF t ~ '(administrac|oficina|recepci|direcci|secretar|trámite|tramite)'   THEN RETURN 'Atención administrativa'; END IF;
  RETURN 'Otros';
END;
$$;

COMMENT ON FUNCTION public.quality_classify_comment(text) IS
  'Categoriza un comentario de texto por palabra clave (seccion 13). Heuristica simple y explicita: lo no reconocido cae en Otros.';


-- Frecuencia de categorias de comentarios en un periodo (seccion 13).
CREATE OR REPLACE VIEW public.v_quality_comment_topics AS
SELECT r.period_id,
       p.period_month,
       public.quality_classify_comment(coalesce(r.general_comment, r.teacher_comment)) AS category,
       count(*)::int AS mentions
  FROM public.quality_responses r
  JOIN public.quality_periods p ON p.id = r.period_id
 WHERE coalesce(r.general_comment, r.teacher_comment) IS NOT NULL
   AND btrim(coalesce(r.general_comment, r.teacher_comment)) <> ''
 GROUP BY r.period_id, p.period_month, category;

COMMENT ON VIEW public.v_quality_comment_topics IS
  'Temas mas mencionados en los comentarios del periodo, para saber donde concentrar esfuerzos (seccion 13).';


-- ──────────────────────────────────────────────────────────────────────────────
-- Las vistas se ejecutan con los permisos de quien consulta (security_invoker).
-- Sin esto, al haber sido creadas por el dueno de la migracion, correrian con
-- permisos de superusuario, saltandose el RLS de las tablas subyacentes: cualquier
-- padre autenticado podria leer la matriz completa de docentes y los comentarios
-- de otras familias. Con security_invoker, las RLS de arriba sí aplican.
-- ──────────────────────────────────────────────────────────────────────────────
DO $$
DECLARE
  v_view text;
BEGIN
  FOREACH v_view IN ARRAY ARRAY[
    'v_quality_dimension_scores',
    'v_quality_period_summary',
    'v_quality_teacher_matrix',
    'v_quality_teacher_dimensions',
    'v_quality_trends',
    'v_quality_pending',
    'v_quality_comment_topics'
  ] LOOP
    EXECUTE format('ALTER VIEW public.%I SET (security_invoker = true)', v_view);
  END LOOP;
END;
$$;

REVOKE ALL ON public.v_quality_dimension_scores, public.v_quality_period_summary,
                 public.v_quality_teacher_matrix,   public.v_quality_teacher_dimensions,
                 public.v_quality_trends,           public.v_quality_pending,
                 public.v_quality_comment_topics FROM anon;
GRANT SELECT ON public.v_quality_dimension_scores, public.v_quality_period_summary,
                    public.v_quality_teacher_matrix,   public.v_quality_teacher_dimensions,
                    public.v_quality_trends,           public.v_quality_pending,
                    public.v_quality_comment_topics TO authenticated;


-- ──────────────────────────────────────────────────────────────────────────────
-- Automatizacion mensual (secciones 3, 12 y 21) - todo en SQL
-- ──────────────────────────────────────────────────────────────────────────────

-- Abre el periodo del mes anterior. Idempotente: si ya existe, no hace nada.
-- El dia 1 de octubre se crea el periodo de septiembre.
CREATE OR REPLACE FUNCTION public.quality_activate_previous_month()
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_month  date;
  v_id     bigint;
BEGIN
  -- Primer dia del mes anterior. El 1 de octubre se evalua septiembre.
  v_month := date_trunc('month', now() - interval '1 month')::date;

  INSERT INTO public.quality_periods (period_month, opens_at, closes_at, status)
  VALUES (
    v_month,
    date_trunc('month', now()),
    date_trunc('month', now()) + interval '1 month',
    'open'
  )
  ON CONFLICT (period_month) DO NOTHING
  RETURNING id INTO v_id;

  -- Ya existía: devolvemos el id para que la llamada sea inocua.
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM public.quality_periods WHERE period_month = v_month;
  END IF;

  RETURN v_id;
END;
$$;

COMMENT ON FUNCTION public.quality_activate_previous_month() IS
  'Crea y abre el periodo correspondiente al mes anterior. Idempotente. Se invoca el dia 1 (secciones 3 y 21).';


-- Cierra los periodos cuya fecha de cierre ya paso (seccion 3).
CREATE OR REPLACE FUNCTION public.quality_close_expired()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_n integer;
BEGIN
  UPDATE public.quality_periods
     SET status = 'closed'
   WHERE status = 'open'
     AND now() > closes_at;
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$$;

COMMENT ON FUNCTION public.quality_close_expired() IS
  'Cierra los periodos vencidos. Los resultados se conservan como historial (seccion 3).';


-- Registra el recordatorio del dia correspondiente (1, 7, 15 o 25) para las
-- familias que aun no respondieron. Idempotente por el UNIQUE de la bitacora.
CREATE OR REPLACE FUNCTION public.quality_register_reminders(p_step smallint)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_n integer;
BEGIN
  IF p_step NOT IN (1,7,15,25) THEN RETURN 0; END IF;

  INSERT INTO public.quality_reminders (period_id, parent_id, student_id, step)
  SELECT pend.period_id, pend.parent_id, pend.student_id, p_step
    FROM public.v_quality_pending pend
  ON CONFLICT (period_id, student_id, step) DO NOTHING;
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$$;

COMMENT ON FUNCTION public.quality_register_reminders(smallint) IS
  'Anota el paso de recordatorio (1/7/15/25) para las familias pendientes del periodo abierto. Las que ya respondieron no se anotan (seccion 18).';


-- Alerta de descenso: dimension que cae >= 0.5 puntos frente al periodo
-- anterior, con al menos 3 respuestas para que la muestra signifique algo.
CREATE OR REPLACE FUNCTION public.quality_generate_alerts(p_period_id bigint)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_institutional integer := 0;
  v_teacher       integer := 0;
  v_min_answers CONSTANT integer := 3;
  v_drop       CONSTANT numeric := 0.5;
BEGIN
  -- Descenso institucional (Bloque B) e IGSM
  INSERT INTO public.quality_alerts (period_id, kind, scope, dimension_key, message)
  SELECT cur.period_id,
         'descenso',
         'institucion',
         cur.question_key,
         format(
           'La puntuación de "%s" disminuyó de %s a %s respecto al período anterior (%s respuestas). Se recomienda revisar los comentarios antes de tomar cualquier decisión.',
           cur.prompt, prev.avg_score, cur.avg_score, cur.answers
         )
    FROM public.v_quality_dimension_scores cur
    JOIN public.v_quality_dimension_scores prev
      ON prev.question_key = cur.question_key
     AND prev.period_month = (
           SELECT max(p2.period_month) FROM public.v_quality_dimension_scores p2
           WHERE p2.period_month < cur.period_month AND p2.question_key = cur.question_key
         )
   WHERE cur.period_id = p_period_id
     AND cur.block = 'institucion'
     AND cur.answers >= v_min_answers
     AND prev.avg_score IS NOT NULL
     AND (prev.avg_score - cur.avg_score) >= v_drop
  ON CONFLICT (period_id, kind, scope, dimension_key,
               (COALESCE(teacher_id, '00000000-0000-0000-0000-000000000000'::uuid)))
  DO NOTHING;

  GET DIAGNOSTICS v_institutional = ROW_COUNT;

  -- Descenso por docente (Bloque A), sobre la matriz de dimensiones
  INSERT INTO public.quality_alerts (period_id, kind, scope, teacher_id, dimension_key, message)
  SELECT cur.period_id,
         'descenso',
         'docente',
         cur.teacher_id,
         cur.question_key,
         format(
           'La puntuación de "%s" de %s disminuyó de %s a %s respecto al período anterior (%s respuestas). Se recomienda revisar los comentarios asociados.',
           cur.prompt, coalesce(cur.teacher_name, 'la docente'), prev.avg_score, cur.avg_score, cur.answers
         )
    FROM public.v_quality_teacher_dimensions cur
    JOIN public.v_quality_teacher_dimensions prev
      ON prev.teacher_id = cur.teacher_id
     AND prev.question_key = cur.question_key
     AND prev.period_month = (
           SELECT max(p2.period_month) FROM public.v_quality_teacher_dimensions p2
           WHERE p2.period_month < cur.period_month
             AND p2.teacher_id = cur.teacher_id
             AND p2.question_key = cur.question_key
         )
   WHERE cur.period_id = p_period_id
     AND cur.answers >= v_min_answers
     AND prev.avg_score IS NOT NULL
     AND (prev.avg_score - cur.avg_score) >= v_drop
  ON CONFLICT (period_id, kind, scope, dimension_key,
               (COALESCE(teacher_id, '00000000-0000-0000-0000-000000000000'::uuid)))
  DO NOTHING;

  GET DIAGNOSTICS v_teacher = ROW_COUNT;

  RETURN v_institutional + v_teacher;
END;
$$;

COMMENT ON FUNCTION public.quality_generate_alerts(bigint) IS
  'Genera alertas de descenso comparando el periodo contra el anterior. Exige 3+ respuestas por dimension para no alertar por ruido de muestra (seccion 12). Devuelve cuantas alertas NUEVAS creo; reejecutarla no duplica.';


-- Punto de entrada unico del cron. Corre a diario y decide que hacer.
CREATE OR REPLACE FUNCTION public.quality_daily()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_day        integer := EXTRACT(DAY FROM now())::integer;
  v_opened     bigint;
  v_last_closed bigint;
  v_alerts     integer := 0;
  v_reminder   integer := 0;
BEGIN
  -- 1) Cerrar lo vencido y, de paso, calcular sus alertas de descenso.
  --    OJO: un periodo siempre vence el dia 1, asi que este paso y el de apertura
  --    ocurren el mismo dia. Por eso NO se corta despues de abrir.
  FOR v_last_closed IN
    SELECT id FROM public.quality_periods
     WHERE status = 'open' AND now() > closes_at
  LOOP
    v_alerts := v_alerts + public.quality_generate_alerts(v_last_closed);
  END LOOP;

  PERFORM public.quality_close_expired();

  -- 2) Dia 1: abrir el periodo del mes anterior
  IF v_day = 1 THEN
    v_opened := public.quality_activate_previous_month();
    v_reminder := public.quality_register_reminders(1);
  END IF;

  -- 3) Dias 7 / 15 / 25: recordatorio a las familias pendientes
  IF v_day IN (7,15,25) THEN
    v_reminder := public.quality_register_reminders(v_day::smallint);
  END IF;

  RETURN jsonb_build_object(
    'day',       v_day,
    'opened',    v_opened,
    'closed',    v_last_closed,
    'reminders', v_reminder,
    'alerts',    v_alerts
  );
END;
$$;

COMMENT ON FUNCTION public.quality_daily() IS
  'Entrada unica del cron diario: abre periodos el dia 1, cierra vencidos, registra recordatorios 7/15/25 y calcula alertas al cerrar (seccion 21). Todo en SQL, sin pg_net.';


-- ══════════════════════════════════════════════════════════════════════════════
-- Row Level Security
-- ══════════════════════════════════════════════════════════════════════════════
ALTER TABLE public.quality_periods       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quality_questions     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quality_responses     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quality_answers       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quality_actions       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quality_alerts        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quality_reminders     ENABLE ROW LEVEL SECURITY;

-- El anon no ve nada: todo pasa por authenticated.
REVOKE ALL ON public.quality_periods, public.quality_questions, public.quality_responses,
             public.quality_answers, public.quality_actions, public.quality_alerts,
             public.quality_reminders FROM anon;

-- ---- quality_periods: lectura para todos los autenticados (el padre necesita
--      ver que hay periodo abierto); escritura solo via funciones SECURITY DEFINER.
DROP POLICY IF EXISTS "quality_periods_read" ON public.quality_periods;
CREATE POLICY "quality_periods_read" ON public.quality_periods
  FOR SELECT TO authenticated
  USING (status = 'open' OR public.get_my_role() IN ('directora','admin'));

-- ---- quality_questions: catalogo de lectura, escritura solo Direccion
DROP POLICY IF EXISTS "quality_questions_read" ON public.quality_questions;
CREATE POLICY "quality_questions_read" ON public.quality_questions
  FOR SELECT TO authenticated
  USING (is_active OR public.get_my_role() IN ('directora','admin'));

DROP POLICY IF EXISTS "quality_questions_staff" ON public.quality_questions;
CREATE POLICY "quality_questions_staff" ON public.quality_questions
  FOR ALL TO authenticated
  USING      (public.get_my_role() IN ('directora','admin'))
  WITH CHECK (public.get_my_role() IN ('directora','admin'));

-- ---- quality_responses: el padre solo ve y escribe la suya
DROP POLICY IF EXISTS "quality_responses_parent_read" ON public.quality_responses;
CREATE POLICY "quality_responses_parent_read" ON public.quality_responses
  FOR SELECT TO authenticated
  USING (
    parent_id = auth.uid()
    OR public.get_my_role() IN ('directora','admin')
  );

DROP POLICY IF EXISTS "quality_responses_parent_insert" ON public.quality_responses;
CREATE POLICY "quality_responses_parent_insert" ON public.quality_responses
  FOR INSERT TO authenticated
  WITH CHECK (
    parent_id = auth.uid()
    AND public.is_parent_of_student(student_id)
    -- Solo se acepta en un periodo abierto y dentro de su ventana.
    AND EXISTS (
      SELECT 1 FROM public.quality_periods p
       WHERE p.id = period_id
         AND p.status = 'open'
         AND now() BETWEEN p.opens_at AND p.closes_at
    )
  );

-- Sin UPDATE ni DELETE para padres: una vez enviada, la respuesta es historica.
DROP POLICY IF EXISTS "quality_responses_staff_write" ON public.quality_responses;
CREATE POLICY "quality_responses_staff_write" ON public.quality_responses
  FOR ALL TO authenticated
  USING      (public.get_my_role() IN ('directora','admin'))
  WITH CHECK (public.get_my_role() IN ('directora','admin'));

-- ---- quality_answers: se cuelgan de la respuesta, misma regla
DROP POLICY IF EXISTS "quality_answers_read" ON public.quality_answers;
CREATE POLICY "quality_answers_read" ON public.quality_answers
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.quality_responses r
       WHERE r.id = response_id
         AND (r.parent_id = auth.uid() OR public.get_my_role() IN ('directora','admin'))
    )
  );

DROP POLICY IF EXISTS "quality_answers_parent_insert" ON public.quality_answers;
CREATE POLICY "quality_answers_parent_insert" ON public.quality_answers
  FOR INSERT TO authenticated
  WITH CHECK (
    -- Solo el propio padre de la respuesta, y solo si la respuesta sigue
    -- en un periodo abierto.
    EXISTS (
      SELECT 1
        FROM public.quality_responses r
        JOIN public.quality_periods  p ON p.id = r.period_id
       WHERE r.id = response_id
         AND r.parent_id = auth.uid()
         AND p.status = 'open'
         AND now() BETWEEN p.opens_at AND p.closes_at
    )
  );

DROP POLICY IF EXISTS "quality_answers_staff_write" ON public.quality_answers;
CREATE POLICY "quality_answers_staff_write" ON public.quality_answers
  FOR ALL TO authenticated
  USING      (public.get_my_role() IN ('directora','admin'))
  WITH CHECK (public.get_my_role() IN ('directora','admin'));

-- ---- quality_actions / quality_alerts: gestion interna de Direccion
DROP POLICY IF EXISTS "quality_actions_staff" ON public.quality_actions;
CREATE POLICY "quality_actions_staff" ON public.quality_actions
  FOR ALL TO authenticated
  USING      (public.get_my_role() IN ('directora','admin'))
  WITH CHECK (public.get_my_role() IN ('directora','admin'));

DROP POLICY IF EXISTS "quality_alerts_staff" ON public.quality_alerts;
CREATE POLICY "quality_alerts_staff" ON public.quality_alerts
  FOR ALL TO authenticated
  USING      (public.get_my_role() IN ('directora','admin'))
  WITH CHECK (public.get_my_role() IN ('directora','admin'));

-- ---- quality_reminders: solo lectura para la Direccion. La escritura la hace
--      el cron; se usa SECURITY DEFINER asi que no necesita policy de INSERT.
DROP POLICY IF EXISTS "quality_reminders_read" ON public.quality_reminders;
CREATE POLICY "quality_reminders_read" ON public.quality_reminders
  FOR SELECT TO authenticated
  USING (public.get_my_role() IN ('directora','admin'));

GRANT SELECT, INSERT, UPDATE         ON public.quality_periods   TO authenticated;
GRANT SELECT                         ON public.quality_questions TO authenticated;
GRANT SELECT, INSERT                 ON public.quality_responses TO authenticated;
GRANT SELECT, INSERT                 ON public.quality_answers   TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.quality_actions   TO authenticated;
GRANT SELECT, INSERT, UPDATE         ON public.quality_alerts    TO authenticated;
GRANT SELECT                         ON public.quality_reminders TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- ══════════════════════════════════════════════════════════════════════════════
-- Envio atomico de la encuesta
-- ══════════════════════════════════════════════════════════════════════════════
-- El cliente NO inserta respuesta y respuestas por separado: si el segundo
-- INSERT fallara (validacion, red) dejaria una respuesta sin respuestas, y el
-- UNIQUE (period_id, student_id) impediria al padre reintentar. Esta funcion lo
-- resuelve en una sola transaccion.
--
-- Es SECURITY DEFINER, asi que ignora las RLS de arriba: por eso vuelve a
-- validar TODAS las condiciones a mano. Es la unica puerta de escritura de
-- los padres y no acepta p_parent_id: la identidad sale de auth.uid().
CREATE OR REPLACE FUNCTION public.quality_submit_survey(
  p_period_id          bigint,
  p_student_id         bigint,
  p_overall_score      smallint,
  p_teacher_comment    text DEFAULT NULL,
  p_general_comment    text DEFAULT NULL,
  p_comment_anonymous  boolean DEFAULT false,
  p_answers            jsonb DEFAULT '[]'::jsonb
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid        uuid := auth.uid();
  v_teacher_id uuid;
  v_response_id bigint;
  v_item       jsonb;
  v_question_id bigint;
  v_score      smallint;
  v_matched    integer;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'No autenticado' USING ERRCODE = '42501';
  END IF;

  -- 1) El alumno debe ser hijo de quien responde y estar activo.
  SELECT s.classroom_id INTO v_teacher_id
    FROM public.students s
   WHERE s.id = p_student_id
     AND s.parent_id = v_uid
     AND COALESCE(s.is_active, true)
     AND s.deleted_at IS NULL;

  IF v_teacher_id IS NULL THEN
    RAISE EXCEPTION 'El alumno no corresponde a tu familia' USING ERRCODE = '42501';
  END IF;

  -- 2) El periodo debe estar abierto y dentro de su ventana.
  IF NOT EXISTS (
    SELECT 1 FROM public.quality_periods p
     WHERE p.id = p_period_id
       AND p.status = 'open'
       AND now() BETWEEN p.opens_at AND p.closes_at
  ) THEN
    RAISE EXCEPTION 'El periodo de evaluacion no esta abierto' USING ERRCODE = '22023';
  END IF;

  -- 3) El IGSM es obligatorio y va de 1 a 5.
  IF p_overall_score IS NULL OR p_overall_score NOT BETWEEN 1 AND 5 THEN
    RAISE EXCEPTION 'Debes calificar tu satisfaccion general' USING ERRCODE = '22023';
  END IF;

  -- 4) La docente evaluada se congela al momento del envio.
  SELECT c.teacher_id INTO v_teacher_id
    FROM public.students s
    LEFT JOIN public.classrooms c ON c.id = s.classroom_id
   WHERE s.id = p_student_id;

  INSERT INTO public.quality_responses (
    period_id, student_id, parent_id, teacher_id, overall_score,
    teacher_comment, general_comment, comment_anonymous
  )
  VALUES (
    p_period_id, p_student_id, v_uid, v_teacher_id, p_overall_score,
    nullif(btrim(coalesce(p_teacher_comment, '')), ''),
    nullif(btrim(coalesce(p_general_comment, '')), ''),
    coalesce(p_comment_anonymous, false)
  )
  RETURNING id INTO v_response_id;

  -- 5) Puntajes. question_key y no id: el cliente no depende del seed.
  FOR v_item IN SELECT * FROM jsonb_array_elements(coalesce(p_answers, '[]'::jsonb))
  LOOP
    v_score := (v_item ->> 'score')::smallint;
    IF v_score IS NULL OR v_score NOT BETWEEN 1 AND 5 THEN
      RAISE EXCEPTION 'Puntaje invalido en la encuesta' USING ERRCODE = '22023';
    END IF;

    SELECT q.id INTO v_question_id
      FROM public.quality_questions q
     WHERE q.question_key = (v_item ->> 'question_key')
       AND q.is_active;

    IF v_question_id IS NULL THEN
      RAISE EXCEPTION 'Pregunta no valida: %', (v_item ->> 'question_key')
        USING ERRCODE = '22023';
    END IF;

    INSERT INTO public.quality_answers (response_id, question_id, score)
    VALUES (v_response_id, v_question_id, v_score);
  END LOOP;

  -- 6) Se exigio responder TODAS las preguntas activas del catalogo.
  SELECT count(*) INTO v_matched
    FROM public.quality_answers a
    JOIN public.quality_questions q ON q.id = a.question_id
   WHERE a.response_id = v_response_id
     AND q.is_active;

  IF v_matched < (SELECT count(*) FROM public.quality_questions WHERE is_active) THEN
    RAISE EXCEPTION 'Faltan preguntas por responder' USING ERRCODE = '22023';
  END IF;

  RETURN v_response_id;
END;
$$;

COMMENT ON FUNCTION public.quality_submit_survey(bigint, bigint, smallint, text, text, boolean, jsonb) IS
  'Envia la encuesta completa en una transaccion. Valida identidad, ventana del periodo, escala 1-5 y que esten todas las preguntas activas. Idempotente por el UNIQUE del periodo: reintentar da error de duplicado.';


-- Postgres otorga EXECUTE a PUBLIC por defecto. Las funciones de automatizacion
-- son SECURITY DEFINER y abren/cierran periodos, asi que si quedaran ejecutables
-- por cualquiera, cualquier usuario autenticado (o anon) podria disparar el
-- ciclo a su arbitrio. Se revoca a PUBLIC y se concede solo a service_role.
REVOKE EXECUTE ON FUNCTION public.quality_daily()                       FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.quality_activate_previous_month()     FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.quality_close_expired()               FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.quality_register_reminders(smallint)  FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.quality_generate_alerts(bigint)       FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_quality_response_count()         FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.quality_daily()                        TO service_role;
GRANT EXECUTE ON FUNCTION public.quality_activate_previous_month()      TO service_role;
GRANT EXECUTE ON FUNCTION public.quality_close_expired()                TO service_role;
GRANT EXECUTE ON FUNCTION public.quality_register_reminders(smallint)   TO service_role;
GRANT EXECUTE ON FUNCTION public.quality_generate_alerts(bigint)        TO service_role;
GRANT EXECUTE ON FUNCTION public.quality_open_period()                  TO authenticated;
GRANT EXECUTE ON FUNCTION public.quality_eligible_students(bigint)      TO authenticated;
GRANT EXECUTE ON FUNCTION public.quality_submit_survey(bigint, bigint, smallint, text, text, boolean, jsonb) TO authenticated;


-- ══════════════════════════════════════════════════════════════════════════════
-- Seed - Catalogo de preguntas (secciones 6, 7 y 8)
-- ══════════════════════════════════════════════════════════════════════════════

-- BLOQUE A - Evaluacion de la docente (4 preguntas, seccion 6)
INSERT INTO public.quality_questions (block, question_key, prompt, sort_order) VALUES
  ('docente','doc_atencion',
   '¿Cómo valoras el trato y la atención brindada a tu hijo/a?', 1),
  ('docente','doc_comunicacion',
   '¿Cómo valoras la comunicación de la docente con los padres o tutores?', 2),
  ('docente','doc_seguimiento',
   '¿Cómo valoras el seguimiento realizado sobre las necesidades y actividades de tu hijo/a?', 3),
  ('docente','doc_organizacion',
   '¿Cómo valoras la organización y responsabilidad observadas durante el mes?', 4)
ON CONFLICT (question_key) DO UPDATE
  SET prompt = EXCLUDED.prompt, sort_order = EXCLUDED.sort_order, block = EXCLUDED.block;

-- BLOQUE B - Evaluacion general de Karpus Kids (6 preguntas, seccion 7)
INSERT INTO public.quality_questions (block, question_key, prompt, sort_order) VALUES
  ('institucion','ins_limpieza',
   '¿Cómo valoras la limpieza de las instalaciones?', 10),
  ('institucion','ins_seguridad',
   '¿Cómo valoras las medidas de seguridad y control de salida de los estudiantes?', 11),
  ('institucion','ins_alimentacion',
   '¿Cómo valoras la calidad y variedad de los alimentos ofrecidos?', 12),
  ('institucion','ins_administracion',
   '¿Cómo valoras la atención recibida por parte de la administración?', 13),
  ('institucion','ins_comunicacion',
   '¿Cómo valoras la comunicación general de Karpus Kids con las familias?', 14),
  ('institucion','ins_instalaciones',
   '¿Cómo valoras las condiciones generales de las instalaciones?', 15)
ON CONFLICT (question_key) DO UPDATE
  SET prompt = EXCLUDED.prompt, sort_order = EXCLUDED.sort_order, block = EXCLUDED.block;

-- Backfill por si las preguntas ya existian con otro is_active
UPDATE public.quality_questions SET is_active = true WHERE is_active = false;


-- ══════════════════════════════════════════════════════════════════════════════
-- Seed - Periodo inicial
-- ══════════════════════════════════════════════════════════════════════════════
-- Se crea el periodo del mes anterior para que la funcionalidad sea usable desde
-- el primer dia. Es idempotente: si ya existe el mes, no lo duplica.
DO $$
DECLARE
  v_month date := date_trunc('month', now() - interval '1 month')::date;
BEGIN
  PERFORM public.quality_activate_previous_month();
  -- Si ya habia periodos cerrados de meses previos, no se tocan.
  RAISE NOTICE 'Sistema de evaluacion de calidad instalado. Periodo activo: %', v_month;
END;
$$;


-- ══════════════════════════════════════════════════════════════════════════════
-- pg_cron - Automatizacion diaria (seccion 21)
-- ══════════════════════════════════════════════════════════════════════════════
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    RAISE NOTICE 'pg_cron no esta instalado: se omite la automatizacion. La evaluacion se abre a mano con SELECT public.quality_activate_previous_month().';
    RETURN;
  END IF;

  -- Un solo trabajo. quality_daily() ya es idempotente en todas sus ramas.
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'quality-daily') THEN
    PERFORM cron.unschedule('quality-daily');
  END IF;

  -- 07:10 hora local del servidor: corre cuando el panel no esta en uso pico,
  -- y suficientemente despues del cierre de periodo del dia 1.
  PERFORM cron.schedule('quality-daily', '10 7 * * *', 'SELECT public.quality_daily()');
EXCEPTION
  WHEN insufficient_privilege THEN
    RAISE NOTICE 'Sin permisos para agendar cron: se omite la automatizacion.';
  WHEN OTHERS THEN
    RAISE NOTICE 'No se pudo agendar el cron de evaluacion: %', SQLERRM;
END;
$$;

COMMIT;
