-- ==========================================================================
-- KARPUS KIDS / MIGRACION CONSOLIDADA 6/10 - ESQUEMA COMERCIO Y SOCIAL: tienda, donaciones, referidos, preinscripcion, respaldo
--
-- Generada por auditoria de los 36 archivos de migraciones/operativos/ y
-- los 8 de supabase/migrations/ (44 fuentes en total). Esta migracion y las 9
-- restantes son las unicas que se conservan: las 44 fuentes originales se
-- eliminaron del repositorio tras consolidar y corregir sus defectos.
--
-- IDEMPOTENTE: se puede aplicar sobre la base ya desplegada sin perder datos.
-- Ejecutar en orden 01 -> 10 (ver README de migraciones).
-- ==========================================================================


-- ---- store_categories ----------------------------------------------------
CREATE TABLE IF NOT EXISTS store_categories (
    id          SERIAL  PRIMARY KEY,
    name        TEXT    NOT NULL,
    icon        TEXT    DEFAULT '📦',
    sort_order  INT     DEFAULT 0,
    is_active   BOOLEAN DEFAULT TRUE,
    created_at  TIMESTAMPTZ DEFAULT NOW()
  );


-- ---- store_products ------------------------------------------------------
CREATE TABLE IF NOT EXISTS store_products (
    id           UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id  INT     REFERENCES store_categories(id) ON DELETE SET NULL,
    name         TEXT    NOT NULL,
    description  TEXT,
    price        NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    image_url    TEXT,
    stock        INT     NOT NULL DEFAULT 0 CHECK (stock >= 0),
    unit         TEXT    DEFAULT 'unidad',
    is_active    BOOLEAN DEFAULT TRUE,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
  );


-- ---- store_product_sizes -------------------------------------------------
CREATE TABLE IF NOT EXISTS store_product_sizes (
    id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id  UUID    NOT NULL REFERENCES store_products(id) ON DELETE CASCADE,
    size_label  TEXT    NOT NULL,
    stock       INT     NOT NULL DEFAULT 0 CHECK (stock >= 0),
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, size_label)
  );


-- ---- store_orders --------------------------------------------------------
CREATE TABLE IF NOT EXISTS store_orders (
    id           UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    parent_id    UUID    NOT NULL REFERENCES profiles(id)  ON DELETE CASCADE,
    student_id   BIGINT  REFERENCES students(id)           ON DELETE SET NULL,
    status       TEXT    NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','confirmed','ready','delivered','cancelled')),
    total        NUMERIC(10,2) NOT NULL DEFAULT 0,
    notes        TEXT,
    confirmed_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
  );


-- ---- store_order_items ---------------------------------------------------
CREATE TABLE IF NOT EXISTS store_order_items (
    id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id    UUID    NOT NULL REFERENCES store_orders(id)   ON DELETE CASCADE,
    product_id  UUID    NOT NULL REFERENCES store_products(id) ON DELETE RESTRICT,
    quantity    INT     NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price  NUMERIC(10,2) NOT NULL,
    subtotal    NUMERIC(10,2) GENERATED ALWAYS AS (quantity * unit_price) STORED
  );


-- ---- store_inventory -----------------------------------------------------
CREATE TABLE IF NOT EXISTS store_inventory (
    id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id  UUID    NOT NULL REFERENCES store_products(id) ON DELETE CASCADE,
    type        TEXT    NOT NULL CHECK (type IN ('entry','exit','adjustment')),
    quantity    INT     NOT NULL,
    reason      TEXT,
    actor_id    UUID    REFERENCES profiles(id) ON DELETE SET NULL,
    order_id    UUID    REFERENCES store_orders(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ DEFAULT NOW()
  );


-- ---- donation_campaigns --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.donation_campaigns (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title           TEXT NOT NULL,
  description     TEXT,
  target_amount   NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (target_amount >= 0),
  raised_amount   NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (raised_amount >= 0),
  cover_image_url TEXT,
  images          TEXT[] NOT NULL DEFAULT '{}',
  start_date      DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date        DATE,
  is_active       BOOLEAN NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ---- donations -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.donations (
  id             UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  tracking_ref   TEXT UNIQUE NOT NULL,
  campaign_id    BIGINT REFERENCES public.donation_campaigns(id) ON DELETE SET NULL,
  donor_name     TEXT NOT NULL,
  donor_email    TEXT NOT NULL,
  donor_phone    TEXT,
  donor_tax_id   TEXT,
  is_company     BOOLEAN DEFAULT false,
  is_anonymous   BOOLEAN DEFAULT false,
  amount         NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  currency       TEXT NOT NULL DEFAULT 'DOP',
  payment_method TEXT NOT NULL CHECK (payment_method IN ('transfer','card','cash')),
  bank_name      TEXT,
  receipt_url    TEXT,
  status         TEXT NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','approved','rejected','certified')),
  notes          TEXT,
  approved_by    UUID REFERENCES public.profiles(id),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ---- donation_settings ---------------------------------------------------
CREATE TABLE IF NOT EXISTS public.donation_settings (
  id                      int PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  bank_accounts           jsonb NOT NULL DEFAULT '[]'::jsonb,

  transfer_instructions   text,
  updated_at              timestamptz NOT NULL DEFAULT now()
);


-- ---- referral_codes ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.referral_codes (
  id                    uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  parent_id             uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  code                  text NOT NULL UNIQUE,
  qr_url                text,
  total_invites_sent    integer DEFAULT 0,
  successful_conversions integer DEFAULT 0,
  created_at            timestamptz DEFAULT now()
);


-- ---- referrals -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.referrals (
  id                   uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  referrer_parent_id   uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  referred_family_name text NOT NULL,
  referred_email       text,
  referred_phone       text,
  status               text NOT NULL DEFAULT 'invited'
                       CHECK (status IN ('invited','registered','visited','enrolled','rejected')),
  reward_status        text NOT NULL DEFAULT 'pending'
                       CHECK (reward_status IN ('pending','approved','applied','expired')),
  discount_amount      numeric(10,2) DEFAULT 0.00,
  prereg_id            bigint REFERENCES public.student_preregistrations(id) ON DELETE SET NULL,
  enrolled_student_id  bigint REFERENCES public.students(id) ON DELETE SET NULL,
  enrolled_at          timestamptz,
  created_at           timestamptz DEFAULT now()
);


-- ---- referral_rewards ----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.referral_rewards (
  id                   uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  parent_id            uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  referral_id          uuid REFERENCES public.referrals(id) ON DELETE CASCADE,
  reward_type          text NOT NULL DEFAULT 'monthly_discount'
                       CHECK (reward_type IN ('monthly_discount','free_month','cashback')),
  amount               numeric(10,2) NOT NULL DEFAULT 0,
  description          text,
  is_used              boolean DEFAULT false,
  applied_to_payment_id bigint REFERENCES public.payments(id) ON DELETE SET NULL,
  used_at              timestamptz,
  expires_at           timestamptz,
  created_at           timestamptz DEFAULT now()
);


-- ---- student_preregistrations --------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_preregistrations (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status                text NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','reviewing','admitted','converted','rejected','expired')),
  student_name          text NOT NULL,
  student_last_name     text,
  birth_date            date,
  gender                text CHECK (gender IN ('Masculino','Femenino')),
  nationality           text DEFAULT 'Dominicana',
  school_year_requested text,
  level_requested       text,
  schedule              text,
  estimated_entry_date  date,
  has_siblings          boolean DEFAULT false,
  sibling_name          text,
  parent_1              jsonb DEFAULT '{}',
  parent_2              jsonb DEFAULT '{}',
  emergency_contact     jsonb DEFAULT '{}',
  authorized_people     jsonb DEFAULT '[]',
  medical               jsonb DEFAULT '{}',
  documents             jsonb DEFAULT '{}',
  consents              jsonb DEFAULT '{}',
  signature_data        text,
  contact_email         text,
  contact_phone         text,
  review_notes          text,
  reviewed_by           uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at           timestamp with time zone,
  converted_student_id  bigint REFERENCES public.students(id) ON DELETE SET NULL,
  ip_address            text,
  user_agent            text,
  created_at            timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- recovery_requests ---------------------------------------------------
CREATE TABLE IF NOT EXISTS public.recovery_requests (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email       text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);


-- ---- kiosk_config --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.kiosk_config (
  id                 int PRIMARY KEY,
  function_secret    text NOT NULL DEFAULT '',
  base_url           text NOT NULL DEFAULT 'https://wwnfonkvemimwiqjpkij.supabase.co/functions/v1',
  function_name      text NOT NULL DEFAULT 'kiosk-notify',
  paused             boolean NOT NULL DEFAULT false
);


-- ---- ALTER TABLE de este bloque ------------------------------------------
ALTER TABLE store_products
    ADD COLUMN IF NOT EXISTS images      TEXT[]   DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS has_sizes   BOOLEAN  DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS unit        TEXT     DEFAULT 'unidad';

ALTER TABLE store_order_items
    ADD COLUMN IF NOT EXISTS size_label TEXT DEFAULT NULL;

ALTER TABLE store_inventory ADD COLUMN IF NOT EXISTS size_label TEXT;

ALTER TABLE public.student_preregistrations
    ADD COLUMN IF NOT EXISTS entry_time time,
    ADD COLUMN IF NOT EXISTS exit_time  time;

ALTER TABLE public.student_preregistrations ALTER COLUMN student_name DROP NOT NULL;

ALTER TABLE public.student_preregistrations
  ADD COLUMN IF NOT EXISTS referral_code text;

ALTER TABLE public.student_preregistrations
  ADD COLUMN IF NOT EXISTS referral_parent_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.donations
  ADD COLUMN IF NOT EXISTS frequency TEXT NOT NULL DEFAULT 'one_time'
  CHECK (frequency IN ('one_time','monthly'));

ALTER TABLE public.donation_campaigns
  ADD COLUMN IF NOT EXISTS title           TEXT NOT NULL DEFAULT 'Campaña',
  ADD COLUMN IF NOT EXISTS description     TEXT,
  ADD COLUMN IF NOT EXISTS target_amount   NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS raised_amount   NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS cover_image_url TEXT,
  ADD COLUMN IF NOT EXISTS images          TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS start_date      DATE    NOT NULL DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS end_date        DATE,
  ADD COLUMN IF NOT EXISTS is_active       BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE public.donation_campaigns
  ADD COLUMN IF NOT EXISTS images TEXT[] NOT NULL DEFAULT '{}';

ALTER TABLE public.donation_campaigns
  ADD COLUMN IF NOT EXISTS cover_image_url TEXT;


-- ---- Seeds idempotentes --------------------------------------------------
INSERT INTO store_categories (name, icon, sort_order) VALUES
    ('Uniformes',       '👕', 1),
    ('Útiles',          '✏️', 2),
    ('Refrigerios',     '🍱', 3),
    ('Libros',          '📚', 4),
    ('Actividades',     '🎨', 5)
  ON CONFLICT DO NOTHING;

INSERT INTO public.donation_campaigns
  (title, description, target_amount, cover_image_url, start_date, end_date, is_active)
VALUES
  ('Fondo de Becas Karpus 2026',
   'Ayuda a que niños de escasos recursos accedan a una educación de calidad con una beca completa.',
   250000.00, NULL, CURRENT_DATE, NULL, true),
  ('Remodelación del Patio de Juegos',
   'Renovemos juntos el área de recreación con equipos seguros, modernos y accesibles para todos.',
   120000.00, NULL, CURRENT_DATE, NULL, true),
  ('Programa de Nutrición Infantil',
   'Suministro de alimentación balanceada y seguimiento nutricional para los pequeños.',
   80000.00, NULL, CURRENT_DATE, NULL, true)
ON CONFLICT DO NOTHING;

INSERT INTO public.kiosk_config (id, function_secret, base_url, function_name, paused)
VALUES (1, '', 'https://wwnfonkvemimwiqjpkij.supabase.co/functions/v1', 'kiosk-notify', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.donation_settings (id, bank_accounts, transfer_instructions)
VALUES (1, '[
  {"bank":"Banco BHD",        "account":"96034190000", "type":"Corriente", "owner":"Karpus Kids SRL"},
  {"bank":"Banco Popular",    "account":"75225189412", "type":"Ahorro",    "owner":"Karpus Kids SRL"},
  {"bank":"Banreservas",      "account":"116543987001", "type":"Corriente", "owner":"Karpus Kids SRL"}
]'::jsonb,
'Solicita al personal de Karpus Kids el comprobante de tu transferencia por WhatsApp o responde al correo de confirmación con el volante bancario.'
)
ON CONFLICT (id) DO NOTHING;


-- ---- Backfills historicos EXCLUIDOS a proposito --------------------------
-- Un INSERT en payments con mes fijo (p. ej. 2026-05) queda fuera de la
-- consolidacion: volver a aplicarlo generaria cobros de meses ya cerrados.
-- El unico generador de cobros es run_payment_cycle() / generate_student_charges().
-- (venia de migraciones/operativos/11_limpieza_pagos_incorrectos.sql)

