-- ==========================================================================
-- KARPUS KIDS / MIGRACION CONSOLIDADA 5/10 - ESQUEMA MURO Y COMUNICACION: posts, comentarios, reacciones, chat, notificaciones
--
-- Generada por auditoria de los 36 archivos de migraciones/operativos/ y
-- los 8 de supabase/migrations/ (44 fuentes en total). Esta migracion y las 9
-- restantes son las unicas que se conservan: las 44 fuentes originales se
-- eliminaron del repositorio tras consolidar y corregir sus defectos.
--
-- IDEMPOTENTE: se puede aplicar sobre la base ya desplegada sin perder datos.
-- Ejecutar en orden 01 -> 10 (ver README de migraciones).
-- ==========================================================================


-- ---- posts ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.posts (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id    bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  teacher_id      uuid REFERENCES public.profiles(id),
  period_id       bigint REFERENCES public.periods(id) ON DELETE SET NULL,
  school_year_id  bigint REFERENCES public.school_years(id),
  content         text,
  media_url       text,
  media_type      text,
  image_url       text,
  images          text[] DEFAULT '{}',
  title           text,
  teacher_name    text,
  teacher_avatar  text,
  likes_count     integer DEFAULT 0,
  comments_count  integer DEFAULT 0,
  is_pinned       boolean DEFAULT false,
  comments_enabled boolean DEFAULT true,
  expire_days     integer,
  scheduled_at    timestamptz,
  status          text DEFAULT 'published',
  views_count     integer DEFAULT 0,
  tagged_students jsonb DEFAULT '[]'::jsonb,
  thumbnail_url   text,
  author_role     text,
  updated_at      timestamp with time zone DEFAULT now(),
  created_at      timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- comments ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.comments (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id    bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id    uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  user_name  text,
  content    text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- likes ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.likes (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id       bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id       uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  reaction_type text DEFAULT 'like',
  created_at    timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(post_id, user_id)
);


-- ---- conversations -------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.conversations (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type         text DEFAULT 'direct_message'
               CHECK (type IN ('direct_message','private','classroom','group')),
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE SET NULL,
  updated_at   timestamp with time zone DEFAULT now(),
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- conversation_participants -------------------------------------------
CREATE TABLE IF NOT EXISTS public.conversation_participants (
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE,
  user_id         uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY(conversation_id, user_id)
);


-- ---- messages ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.messages (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  sender_id       uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  receiver_id     uuid REFERENCES public.profiles(id),
  sender_name     text,
  sender_avatar   text,
  content         text NOT NULL,
  is_read         boolean DEFAULT false,
  read_at         timestamp with time zone,
  created_at      timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- notifications -------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notifications (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title      text NOT NULL,
  message    text NOT NULL,
  type       text DEFAULT 'info',
  link       text,
  is_read    boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- wall_notifications --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.wall_notifications (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  actor_id   uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_name text,
  type       text NOT NULL DEFAULT 'comment',
  post_id    bigint REFERENCES public.posts(id) ON DELETE CASCADE,
  comment_id bigint REFERENCES public.comments(id) ON DELETE SET NULL,
  message    text,
  is_read    boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- ALTER TABLE de este bloque ------------------------------------------
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS is_pinned boolean DEFAULT false;

ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS comments_enabled boolean DEFAULT true;

ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS expire_days integer;

ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS scheduled_at timestamptz;

ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS status text DEFAULT 'published';

ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS views_count integer DEFAULT 0;

ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS tagged_students jsonb DEFAULT '[]'::jsonb;

ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS thumbnail_url text;

ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS author_role text;

ALTER TABLE public.likes ADD COLUMN IF NOT EXISTS reaction_type text DEFAULT 'like';

ALTER TABLE public.messages
    ADD COLUMN IF NOT EXISTS reactions jsonb DEFAULT '{}'::jsonb;

ALTER TABLE public.messages
    ADD COLUMN IF NOT EXISTS reply_to bigint REFERENCES public.messages(id) ON DELETE SET NULL;

ALTER TABLE public.messages
    ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone;

ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS actor_id   uuid REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS actor_name text;

ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS type       text NOT NULL DEFAULT 'comment';

ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS post_id    bigint REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS comment_id bigint REFERENCES public.comments(id) ON DELETE SET NULL;

ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS message    text;

ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS is_read    boolean DEFAULT false;

ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

ALTER TABLE posts ADD COLUMN IF NOT EXISTS thumbnail_urls text[] DEFAULT '{}';

ALTER TABLE posts ADD COLUMN IF NOT EXISTS duration real DEFAULT NULL;


-- ---- Backfills historicos EXCLUIDOS a proposito --------------------------
-- Un INSERT en payments con mes fijo (p. ej. 2026-05) queda fuera de la
-- consolidacion: volver a aplicarlo generaria cobros de meses ya cerrados.
-- El unico generador de cobros es run_payment_cycle() / generate_student_charges().
-- (venia de migraciones/operativos/11_limpieza_pagos_incorrectos.sql)

