-- ==========================================================================
-- KARPUS KIDS / MIGRACION CONSOLIDADA 4/10 - ESQUEMA OPERACION: incidentes, rutina, accesos, agenda, reuniones, reportes, matricula
--
-- Generada por auditoria de los 36 archivos de migraciones/operativos/ y
-- los 8 de supabase/migrations/ (44 fuentes en total). Esta migracion y las 9
-- restantes son las unicas que se conservan: las 44 fuentes originales se
-- eliminaron del repositorio tras consolidar y corregir sus defectos.
--
-- IDEMPOTENTE: se puede aplicar sobre la base ya desplegada sin perder datos.
-- Ejecutar en orden 01 -> 10 (ver README de migraciones).
-- ==========================================================================


-- ---- incidents -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.incidents (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  teacher_id   uuid REFERENCES public.profiles(id),
  severity     text CHECK (severity IN ('leve','media','alta')),
  status       text DEFAULT 'received'
               CHECK (status IN ('received','review','resolved','archived')),
  description  text,
  reported_at  timestamp with time zone DEFAULT now() NOT NULL,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- daily_logs ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.daily_logs (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id          bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id        bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  date                date DEFAULT current_date,
  mood                text, food text, nap text, eating text, sleeping text,
  activities          text, notes text,
  infant_data         jsonb DEFAULT '[]'::jsonb,
  events              jsonb DEFAULT '[]'::jsonb,
  status              text DEFAULT 'published' CHECK (status IN ('draft','published')),
  school_year_id      bigint REFERENCES public.school_years(id),
  academic_period_id  bigint REFERENCES public.academic_periods(id),
  created_at          timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(student_id, date)
);


-- ---- door_punches --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.door_punches (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
    staff_id     uuid   REFERENCES public.profiles(id) ON DELETE CASCADE,
    punch_type   text   NOT NULL CHECK (punch_type IN ('check_in','check_out')),
    punched_at   timestamp with time zone DEFAULT now() NOT NULL,
    date         date   DEFAULT current_date NOT NULL,
    parent_notified boolean DEFAULT false,
    created_at   timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT door_punches_student_type_date UNIQUE (student_id, punch_type, date),
    CONSTRAINT door_punches_staff_type_date   UNIQUE (staff_id,   punch_type, date),
    CONSTRAINT door_punches_one_subject CHECK (
      (student_id IS NOT NULL AND staff_id IS NULL) OR
      (student_id IS NULL     AND staff_id IS NOT NULL)
    )
  );


-- ---- classroom_gallery ---------------------------------------------------
CREATE TABLE IF NOT EXISTS public.classroom_gallery (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  image_url    text NOT NULL,
  caption      text,
  date         date DEFAULT current_date,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- classroom_chat ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.classroom_chat (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  user_id      uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  message      text NOT NULL,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- classroom_event_schedule --------------------------------------------
CREATE TABLE IF NOT EXISTS public.classroom_event_schedule (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id     bigint REFERENCES public.classrooms(id) ON DELETE CASCADE NOT NULL,
  event_type       text NOT NULL,
  event_label      text NOT NULL,
  event_icon       text DEFAULT '⏰',
  category         text DEFAULT 'personalizados',
  scheduled_hour   smallint NOT NULL CHECK (scheduled_hour >= 0 AND scheduled_hour <= 23),
  scheduled_minute smallint NOT NULL DEFAULT 0 CHECK (scheduled_minute >= 0 AND scheduled_minute <= 59),
  duration_minutes smallint DEFAULT 30 CHECK (duration_minutes > 0 AND duration_minutes <= 480),
  is_active        boolean DEFAULT true,
  auto_register    boolean DEFAULT false,
  applies_to       text DEFAULT 'all' CHECK (applies_to IN ('all','infant','standard')),
  sort_order       smallint DEFAULT 0,
  created_at       timestamp with time zone DEFAULT now() NOT NULL,
  updated_at       timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(classroom_id, event_type)
);


-- ---- timeline_event_log --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.timeline_event_log (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id     bigint REFERENCES public.classrooms(id) ON DELETE CASCADE NOT NULL,
  event_type       text NOT NULL,
  registered_by    uuid REFERENCES public.profiles(id),
  target_students  bigint[] DEFAULT '{}',
  student_count    smallint DEFAULT 0,
  scheduled_time   time,
  actual_time      time DEFAULT CURRENT_TIME,
  duration_minutes smallint,
  metadata         jsonb DEFAULT '{}'::jsonb,
  created_at       timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- meetings ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.meetings (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       text NOT NULL,
  description text,
  room_name   text NOT NULL,
  start_time  timestamp with time zone,
  type        text DEFAULT 'classroom',
  target_id   bigint,
  host_id     uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  status      text DEFAULT 'scheduled' CHECK (status IN ('scheduled','live','ended','cancelled')),
  created_at  timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- meeting_attendance --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.meeting_attendance (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id  bigint REFERENCES public.meetings(id) ON DELETE CASCADE,
  user_id     uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  joined_at   timestamp with time zone DEFAULT now(),
  left_at     timestamp with time zone,
  UNIQUE(meeting_id, user_id)
);


-- ---- inquiries -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.inquiries (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id     uuid REFERENCES public.profiles(id) NOT NULL,
  student_id    bigint REFERENCES public.students(id),
  subject       text, message text NOT NULL, response text,
  status        text DEFAULT 'pending', priority text DEFAULT 'medium',
  folio         text, attachment_url text,
  updated_at    timestamp with time zone,
  responded_at  timestamp with time zone,
  created_at    timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- school_settings -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.school_settings (
  id              int PRIMARY KEY DEFAULT 1,
  phone           text DEFAULT '(829) 803-8424',
  business_hours  text DEFAULT 'Lun-Vie: 7am - 6pm',
  generation_day  int DEFAULT 25,
  due_day         int DEFAULT 5,
  check_in_start  time DEFAULT '07:30:00',
  check_in_end    time DEFAULT '08:30:00',
  check_out_start time DEFAULT '16:00:00',
  check_out_end   time DEFAULT '17:30:00',
  open_time       time DEFAULT '07:00:00',
  close_time      time DEFAULT '18:00:00',
  work_days       text DEFAULT '["Lun","Mar","Mié","Jue","Vie"]',
  updated_at      timestamp with time zone DEFAULT now()
);


-- ---- system_events -------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.system_events (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type         text NOT NULL, payload jsonb,
  status       text DEFAULT 'pending' CHECK (status IN ('pending','processing','completed','failed')),
  processed_at timestamp with time zone,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- terms_acceptance ----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.terms_acceptance (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  accepted_at   timestamp with time zone DEFAULT now() NOT NULL,
  terms_version text DEFAULT '1.0' NOT NULL,
  UNIQUE(user_id, terms_version)
);


-- ---- audit_logs ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  action     text NOT NULL,
  payload    jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- data_snapshots ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.data_snapshots (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type       text NOT NULL,
  data       jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- login_attempts ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.login_attempts (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      text, ip_hash text, success boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);


-- ---- system_errors -------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.system_errors (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  panel      text,
  context    text,
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  message    text NOT NULL,
  stack      text,
  url        text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- staff_permits -------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.staff_permits (
  id           uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  staff_id     uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  type         permit_type DEFAULT 'permission',
  reason       text NOT NULL,
  start_date   date NOT NULL,
  end_date     date NOT NULL,
  status       permit_status DEFAULT 'pending',
  approved_by  uuid REFERENCES public.profiles(id),
  comments     text,
  evidence_url text,
  created_at   timestamp with time zone DEFAULT now(),
  updated_at   timestamp with time zone DEFAULT now()
);


-- ---- reports -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reports (
  id               uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_number    text UNIQUE NOT NULL,
  reporter_id      uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  reporter_role    text NOT NULL,
  target_type      text NOT NULL CHECK (target_type IN ('teacher','parent')),
  target_id        uuid NOT NULL REFERENCES public.profiles(id),
  category         text NOT NULL CHECK (category IN ('conduct','academic','attendance','communication','other')),
  severity         text NOT NULL CHECK (severity IN ('low','medium','high','critical')),
  title            text NOT NULL,
  description      text NOT NULL,
  status           text NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending','in_progress','resolved','escalated','closed')),
  required_actions text[],
  follow_up_date   timestamp with time zone,
  resolution_notes text,
  resolved_at      timestamp with time zone,
  resolved_by      uuid REFERENCES public.profiles(id),
  is_confidential  boolean DEFAULT false,
  priority         integer DEFAULT 1 CHECK (priority BETWEEN 1 AND 5),
  tags             text[],
  deleted_at       timestamp with time zone,
  created_at       timestamp with time zone DEFAULT now() NOT NULL,
  updated_at       timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- report_history ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.report_history (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_id   uuid NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  action      text NOT NULL,
  changed_by  uuid NOT NULL REFERENCES public.profiles(id),
  old_values  jsonb,
  new_values  jsonb,
  comment     text,
  created_at  timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- report_attachments --------------------------------------------------
CREATE TABLE IF NOT EXISTS public.report_attachments (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_id   uuid NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  file_name   text NOT NULL,
  file_path   text NOT NULL,
  file_type   text NOT NULL,
  file_size   integer NOT NULL,
  uploaded_by uuid NOT NULL REFERENCES public.profiles(id),
  description text,
  created_at  timestamp with time zone DEFAULT now() NOT NULL,
  deleted_at  timestamp with time zone
);


-- ---- report_actions ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.report_actions (
  id           uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_id    uuid NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  action_type  text NOT NULL,
  description  text NOT NULL,
  assigned_to  uuid REFERENCES public.profiles(id),
  completed_by uuid REFERENCES public.profiles(id),
  status       text NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','in_progress','completed','cancelled')),
  due_date     timestamp with time zone,
  completed_at timestamp with time zone,
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  updated_at   timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- student_history -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_history (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id          bigint NOT NULL,
  student_name        text NOT NULL,
  school_year_id      bigint NOT NULL REFERENCES public.school_years(id),
  academic_period_id  bigint REFERENCES public.academic_periods(id),
  classroom_id        bigint REFERENCES public.classrooms(id),
  classroom_name      text,
  teacher_name        text,
  grade_level         text,
  average_score       numeric(5,2),
  attendance_pct      numeric(5,2),
  total_days          integer DEFAULT 0,
  absent_days         integer DEFAULT 0,
  late_days           integer DEFAULT 0,
  status              text DEFAULT 'active'
                      CHECK (status IN ('active','promoted','retained','withdrawn','graduated')),
  notes               text,
  created_at          timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT unique_student_year UNIQUE (student_id, school_year_id)
);


-- ---- enrollments ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.enrollments (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id     bigint REFERENCES public.students(id) ON DELETE SET NULL,
  school_year_id bigint NOT NULL REFERENCES public.school_years(id),
  type           text NOT NULL CHECK (type IN ('new','reenrollment')),
  classroom_id   bigint REFERENCES public.classrooms(id),
  parent_id      uuid REFERENCES public.profiles(id),
  student_name   text,
  status         text DEFAULT 'pending'
                 CHECK (status IN ('pending','approved','rejected')),
  enrolled_at    timestamp with time zone,
  approved_by    uuid REFERENCES public.profiles(id),
  notes          text,
  created_at     timestamp with time zone DEFAULT now() NOT NULL
);


-- ---- promotion_rules -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.promotion_rules (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_year_id  bigint NOT NULL REFERENCES public.school_years(id) ON DELETE CASCADE,
  from_grade      text NOT NULL,
  to_grade        text NOT NULL,
  min_average     numeric(5,2) DEFAULT 70.00,
  min_attendance  numeric(5,2) DEFAULT 80.00,
  auto_promote    boolean DEFAULT true,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT unique_promotion_rule UNIQUE (school_year_id, from_grade)
);


-- ---- ALTER TABLE de este bloque ------------------------------------------
ALTER TABLE public.door_punches ADD COLUMN IF NOT EXISTS classroom_id bigint REFERENCES public.classrooms(id);

ALTER TABLE public.enrollments ADD COLUMN IF NOT EXISTS payment_id bigint REFERENCES public.payments(id) ON DELETE SET NULL;

alter table public.school_settings
    add column if not exists feature_flags jsonb not null default '{}'::jsonb;

ALTER TABLE public.school_settings
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active','suspended'));

ALTER TABLE public.school_settings
  ADD COLUMN IF NOT EXISTS suspended_at timestamp with time zone;

ALTER TABLE public.school_settings
  ADD COLUMN IF NOT EXISTS suspension_reason text;


-- ---- Seeds idempotentes --------------------------------------------------
INSERT INTO public.school_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;


-- ---- Backfills historicos EXCLUIDOS a proposito --------------------------
-- Un INSERT en payments con mes fijo (p. ej. 2026-05) queda fuera de la
-- consolidacion: volver a aplicarlo generaria cobros de meses ya cerrados.
-- El unico generador de cobros es run_payment_cycle() / generate_student_charges().
-- (venia de migraciones/operativos/11_limpieza_pagos_incorrectos.sql)

