-- ═══════════════════════════════════════════════════════════════════════════
-- KARPUS KIDS · SQL OPERATIVO 02/10 — TABLAS PAGOS · ACADÉMICO · OPERACIÓN
-- ═══════════════════════════════════════════════════════════════════════════
-- Continuación del esquema maestro (karpus_schema_completo.sql).
-- Contenido: SECCIÓN 4.15–4.36 tablas: payments, audit log, plans, grades, subjects, period_config, averages, report_cards, incidents, daily_logs, door_punches, galería, event_schedule, meetings, inquiries, settings, system, permits, reports, history, enrollments · SECCIÓN 5 seeds
-- Origen: líneas 454–991 del archivo original.
--
-- ⚠ EJECUTAR EN ORDEN: 01 → 10 (Supabase Dashboard → SQL Editor)
--   Cada archivo continúa el esquema del anterior; no saltarse ninguno
--   en una base nueva. En la base existente son idempotentes.
-- ═══════════════════════════════════════════════════════════════════════════

-- 4.15 PAYMENTS
CREATE TABLE IF NOT EXISTS public.payments (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id           bigint REFERENCES public.students(id) ON DELETE CASCADE,
  amount               numeric(10,2) NOT NULL,
  concept              text DEFAULT 'Mensualidad',
  status               text DEFAULT 'pending',
  month_paid           text,
  due_date             date,
  paid_date            timestamp with time zone,
  method               text,
  bank                 text,
  reference            text,
  transfer_date        date,
  proof_url            text,
  evidence_url         text,
  notes                text,
  validated_by         uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  recorded_by          uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  last_reminder_sent   timestamp with time zone,
  deleted_at           timestamp with time zone,
  updated_at           timestamp with time zone DEFAULT now(),
  created_at           timestamp with time zone DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_unique_student_month
  ON public.payments(student_id, month_paid)
  WHERE month_paid IS NOT NULL AND deleted_at IS NULL;

-- 4.16 PAYMENT AUDIT LOG
CREATE TABLE IF NOT EXISTS public.payment_audit_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id  bigint NOT NULL,
  action      text NOT NULL,
  old_status  text,
  new_status  text,
  changed_by  uuid REFERENCES public.profiles(id),
  actor_name  text,
  actor_role  text,
  details     jsonb DEFAULT '{}',
  changed_at  timestamp with time zone DEFAULT now() NOT NULL
);

-- 4.17 PAYMENT PLANS & INSTALLMENTS
CREATE TABLE IF NOT EXISTS public.payment_plans (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id      bigint REFERENCES public.students(id) ON DELETE CASCADE,
  year            int NOT NULL,
  total_amount    numeric(10,2),
  monthly_amount  numeric(10,2),
  months_total    int DEFAULT 12,
  discount        numeric DEFAULT 0,
  paid_percentage numeric DEFAULT 0,
  status          text DEFAULT 'active' CHECK (status IN ('active','completed','cancelled')),
  created_at      timestamp with time zone DEFAULT now(),
  UNIQUE(student_id, year)
);

CREATE TABLE IF NOT EXISTS public.payment_installments (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id      bigint REFERENCES public.payment_plans(id) ON DELETE CASCADE,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
  month_paid   text,
  amount       numeric(10,2),
  due_date     date,
  status       text DEFAULT 'pending',
  paid_date    timestamp with time zone,
  method       text,
  bank         text,
  evidence_url text,
  created_at   timestamp with time zone DEFAULT now(),
  UNIQUE(student_id, month_paid)
);

-- 4.18 GRADES
CREATE TABLE IF NOT EXISTS public.grades (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id    bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id  bigint REFERENCES public.classrooms(id),
  period_id     bigint REFERENCES public.periods(id),
  school_year_id bigint REFERENCES public.school_years(id),
  activity_id   bigint,  -- FK a activities se agrega después
  subject       text,
  score         numeric(4,2),
  score_v2      numeric(5,2) CHECK (score_v2 >= 0 AND score_v2 <= 100),
  period        text,
  teacher_id    uuid REFERENCES public.profiles(id),
  notes         text,
  created_at    timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.grades ADD COLUMN IF NOT EXISTS score_v2 numeric(5,2) CHECK (score_v2 >= 0 AND score_v2 <= 100);

-- 4.19 SUBJECTS
CREATE TABLE IF NOT EXISTS public.subjects (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            text NOT NULL UNIQUE,
  education_level text,  -- categoría libre, sin valores fijos
  description     text,
  is_active       boolean DEFAULT true,
  created_at      timestamp with time zone DEFAULT now() NOT NULL
);

-- 4.20 PERIOD CONFIG & ACTIVITIES
CREATE TABLE IF NOT EXISTS public.period_config (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id       bigint REFERENCES public.periods(id) ON DELETE CASCADE NOT NULL,
  subject_id      bigint REFERENCES public.subjects(id) ON DELETE CASCADE NOT NULL,
  activity_count  int NOT NULL CHECK (activity_count >= 5 AND activity_count <= 8),
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(period_id, subject_id)
);

CREATE TABLE IF NOT EXISTS public.activities (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_id       bigint REFERENCES public.period_config(id) ON DELETE CASCADE NOT NULL,
  title           text NOT NULL,
  description     text,
  max_score       numeric(5,2) DEFAULT 100,
  activity_number int NOT NULL,
  is_mandatory    boolean DEFAULT true,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(config_id, activity_number)
);
-- Añadir FK activity_id a grades ahora que activities existe
ALTER TABLE public.grades DROP CONSTRAINT IF EXISTS fk_grades_activity;
ALTER TABLE public.grades ADD CONSTRAINT fk_grades_activity
  FOREIGN KEY (activity_id) REFERENCES public.activities(id) ON DELETE CASCADE
  NOT VALID;

-- 4.21 SUBJECT AVERAGES
CREATE TABLE IF NOT EXISTS public.subject_averages (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE NOT NULL,
  period_id    bigint REFERENCES public.periods(id) ON DELETE CASCADE NOT NULL,
  subject_id   bigint REFERENCES public.subjects(id) ON DELETE CASCADE NOT NULL,
  average      numeric(5,2) NOT NULL,
  graded_count int NOT NULL DEFAULT 0,
  method       text DEFAULT 'best_5' CHECK (method IN ('best_5','all')),
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(student_id, period_id, subject_id)
);

-- 4.22 REPORT CARDS
CREATE TABLE IF NOT EXISTS public.report_cards (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id     bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id   bigint REFERENCES public.classrooms(id),
  period_id      bigint REFERENCES public.periods(id),
  school_year_id bigint REFERENCES public.school_years(id),
  task_avg       numeric(4,2),
  formal_avg     numeric(4,2),
  final_score    numeric(4,2),
  level          text,
  teacher_comment text,
  generated_at   timestamp with time zone DEFAULT now(),
  UNIQUE(student_id, period_id)
);

-- 4.23 INCIDENTS
CREATE TABLE IF NOT EXISTS public.incidents (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  teacher_id   uuid REFERENCES public.profiles(id),
  severity     text CHECK (severity IN ('leve','media','alta')),
  status       text DEFAULT 'received'
               CHECK (status IN ('received','review','resolved','archived')),
  description  text,
  reported_at  timestamp with time zone DEFAULT now() NOT NULL,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

-- 4.24 DAILY LOGS (Rutina diaria / bitácora)
CREATE TABLE IF NOT EXISTS public.daily_logs (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id          bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id        bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  date                date DEFAULT current_date,
  mood                text, food text, nap text, eating text, sleeping text,
  activities          text, notes text,
  infant_data         jsonb DEFAULT '[]'::jsonb,
  events              jsonb DEFAULT '[]'::jsonb,
  status              text DEFAULT 'published' CHECK (status IN ('draft','published')),
  school_year_id      bigint REFERENCES public.school_years(id),
  academic_period_id  bigint REFERENCES public.academic_periods(id),
  created_at          timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(student_id, date)
);

-- 4.25 DOOR PUNCHES (Asistencia por QR)
CREATE TABLE IF NOT EXISTS public.door_punches (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id      bigint REFERENCES public.students(id) ON DELETE CASCADE,
  staff_id        uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  punch_type      text NOT NULL CHECK (punch_type IN ('check_in','check_out')),
  punched_at      timestamp with time zone DEFAULT now() NOT NULL,
  date            date DEFAULT current_date NOT NULL,
  parent_notified boolean DEFAULT false,
  classroom_id    bigint REFERENCES public.classrooms(id),
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT door_punches_student_type_date UNIQUE (student_id, punch_type, date),
  CONSTRAINT door_punches_staff_type_date   UNIQUE (staff_id, punch_type, date),
  CONSTRAINT door_punches_one_subject CHECK (
    (student_id IS NOT NULL AND staff_id IS NULL) OR
    (student_id IS NULL AND staff_id IS NOT NULL)
  )
);

-- Ensure classroom_id exists even if door_punches was created by older migrations
ALTER TABLE public.door_punches ADD COLUMN IF NOT EXISTS classroom_id bigint REFERENCES public.classrooms(id);

-- 4.26 GALLERY & CLASSROOM CHAT
CREATE TABLE IF NOT EXISTS public.classroom_gallery (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  image_url    text NOT NULL,
  caption      text,
  date         date DEFAULT current_date,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.classroom_chat (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  user_id      uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  message      text NOT NULL,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

-- 4.27 CLASSROOM EVENT SCHEDULE (Timeline de rutina)
CREATE TABLE IF NOT EXISTS public.classroom_event_schedule (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id     bigint REFERENCES public.classrooms(id) ON DELETE CASCADE NOT NULL,
  event_type       text NOT NULL,
  event_label      text NOT NULL,
  event_icon       text DEFAULT '⏰',
  category         text DEFAULT 'personalizados',
  scheduled_hour   smallint NOT NULL CHECK (scheduled_hour >= 0 AND scheduled_hour <= 23),
  scheduled_minute smallint NOT NULL DEFAULT 0 CHECK (scheduled_minute >= 0 AND scheduled_minute <= 59),
  duration_minutes smallint DEFAULT 30 CHECK (duration_minutes > 0 AND duration_minutes <= 480),
  is_active        boolean DEFAULT true,
  auto_register    boolean DEFAULT false,
  applies_to       text DEFAULT 'all' CHECK (applies_to IN ('all','infant','standard')),
  sort_order       smallint DEFAULT 0,
  created_at       timestamp with time zone DEFAULT now() NOT NULL,
  updated_at       timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(classroom_id, event_type)
);

CREATE TABLE IF NOT EXISTS public.timeline_event_log (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id     bigint REFERENCES public.classrooms(id) ON DELETE CASCADE NOT NULL,
  event_type       text NOT NULL,
  registered_by    uuid REFERENCES public.profiles(id),
  target_students  bigint[] DEFAULT '{}',
  student_count    smallint DEFAULT 0,
  scheduled_time   time,
  actual_time      time DEFAULT CURRENT_TIME,
  duration_minutes smallint,
  metadata         jsonb DEFAULT '{}'::jsonb,
  created_at       timestamp with time zone DEFAULT now() NOT NULL
);

-- 4.28 MEETINGS
CREATE TABLE IF NOT EXISTS public.meetings (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       text NOT NULL,
  description text,
  room_name   text NOT NULL,
  start_time  timestamp with time zone,
  type        text DEFAULT 'classroom',
  target_id   bigint,
  host_id     uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  status      text DEFAULT 'scheduled' CHECK (status IN ('scheduled','live','ended','cancelled')),
  created_at  timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.meeting_attendance (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id  bigint REFERENCES public.meetings(id) ON DELETE CASCADE,
  user_id     uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  joined_at   timestamp with time zone DEFAULT now(),
  left_at     timestamp with time zone,
  UNIQUE(meeting_id, user_id)
);

-- 4.29 INQUIRIES
CREATE TABLE IF NOT EXISTS public.inquiries (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id     uuid REFERENCES public.profiles(id) NOT NULL,
  student_id    bigint REFERENCES public.students(id),
  subject       text, message text NOT NULL, response text,
  status        text DEFAULT 'pending', priority text DEFAULT 'medium',
  folio         text, attachment_url text,
  updated_at    timestamp with time zone,
  responded_at  timestamp with time zone,
  created_at    timestamp with time zone DEFAULT now() NOT NULL
);

-- 4.30 SCHOOL SETTINGS
CREATE TABLE IF NOT EXISTS public.school_settings (
  id              int PRIMARY KEY DEFAULT 1,
  phone           text DEFAULT '(829) 803-8424',
  business_hours  text DEFAULT 'Lun-Vie: 7am - 6pm',
  generation_day  int DEFAULT 25,
  due_day         int DEFAULT 5,
  check_in_start  time DEFAULT '07:30:00',
  check_in_end    time DEFAULT '08:30:00',
  check_out_start time DEFAULT '16:00:00',
  check_out_end   time DEFAULT '17:30:00',
  open_time       time DEFAULT '07:00:00',
  close_time      time DEFAULT '18:00:00',
  work_days       text DEFAULT '["Lun","Mar","Mié","Jue","Vie"]',
  updated_at      timestamp with time zone DEFAULT now()
);
INSERT INTO public.school_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- 4.31 SYSTEM TABLES
CREATE TABLE IF NOT EXISTS public.system_events (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type         text NOT NULL, payload jsonb,
  status       text DEFAULT 'pending' CHECK (status IN ('pending','processing','completed','failed')),
  processed_at timestamp with time zone,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.terms_acceptance (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  accepted_at   timestamp with time zone DEFAULT now() NOT NULL,
  terms_version text DEFAULT '1.0' NOT NULL,
  UNIQUE(user_id, terms_version)
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  action     text NOT NULL,
  payload    jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.data_snapshots (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type       text NOT NULL,
  data       jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.login_attempts (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      text, ip_hash text, success boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.system_errors (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  panel      text,
  context    text,
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  message    text NOT NULL,
  stack      text,
  url        text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 4.32 STAFF PERMITS
CREATE TABLE IF NOT EXISTS public.staff_permits (
  id           uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  staff_id     uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  type         permit_type DEFAULT 'permission',
  reason       text NOT NULL,
  start_date   date NOT NULL,
  end_date     date NOT NULL,
  status       permit_status DEFAULT 'pending',
  approved_by  uuid REFERENCES public.profiles(id),
  comments     text,
  evidence_url text,
  created_at   timestamp with time zone DEFAULT now(),
  updated_at   timestamp with time zone DEFAULT now()
);

-- 4.33 REPORTS SYSTEM
CREATE TABLE IF NOT EXISTS public.reports (
  id               uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_number    text UNIQUE NOT NULL,
  reporter_id      uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  reporter_role    text NOT NULL,
  target_type      text NOT NULL CHECK (target_type IN ('teacher','parent')),
  target_id        uuid NOT NULL REFERENCES public.profiles(id),
  category         text NOT NULL CHECK (category IN ('conduct','academic','attendance','communication','other')),
  severity         text NOT NULL CHECK (severity IN ('low','medium','high','critical')),
  title            text NOT NULL,
  description      text NOT NULL,
  status           text NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending','in_progress','resolved','escalated','closed')),
  required_actions text[],
  follow_up_date   timestamp with time zone,
  resolution_notes text,
  resolved_at      timestamp with time zone,
  resolved_by      uuid REFERENCES public.profiles(id),
  is_confidential  boolean DEFAULT false,
  priority         integer DEFAULT 1 CHECK (priority BETWEEN 1 AND 5),
  tags             text[],
  deleted_at       timestamp with time zone,
  created_at       timestamp with time zone DEFAULT now() NOT NULL,
  updated_at       timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.report_history (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_id   uuid NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  action      text NOT NULL,
  changed_by  uuid NOT NULL REFERENCES public.profiles(id),
  old_values  jsonb,
  new_values  jsonb,
  comment     text,
  created_at  timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.report_attachments (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_id   uuid NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  file_name   text NOT NULL,
  file_path   text NOT NULL,
  file_type   text NOT NULL,
  file_size   integer NOT NULL,
  uploaded_by uuid NOT NULL REFERENCES public.profiles(id),
  description text,
  created_at  timestamp with time zone DEFAULT now() NOT NULL,
  deleted_at  timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.report_actions (
  id           uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_id    uuid NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  action_type  text NOT NULL,
  description  text NOT NULL,
  assigned_to  uuid REFERENCES public.profiles(id),
  completed_by uuid REFERENCES public.profiles(id),
  status       text NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','in_progress','completed','cancelled')),
  due_date     timestamp with time zone,
  completed_at timestamp with time zone,
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  updated_at   timestamp with time zone DEFAULT now() NOT NULL
);

-- 4.34 STUDENT HISTORY (nunca se borra)
CREATE TABLE IF NOT EXISTS public.student_history (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id          bigint NOT NULL,
  student_name        text NOT NULL,
  school_year_id      bigint NOT NULL REFERENCES public.school_years(id),
  academic_period_id  bigint REFERENCES public.academic_periods(id),
  classroom_id        bigint REFERENCES public.classrooms(id),
  classroom_name      text,
  teacher_name        text,
  grade_level         text,
  average_score       numeric(5,2),
  attendance_pct      numeric(5,2),
  total_days          integer DEFAULT 0,
  absent_days         integer DEFAULT 0,
  late_days           integer DEFAULT 0,
  status              text DEFAULT 'active'
                      CHECK (status IN ('active','promoted','retained','withdrawn','graduated')),
  notes               text,
  created_at          timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT unique_student_year UNIQUE (student_id, school_year_id)
);

-- 4.35 ENROLLMENTS
CREATE TABLE IF NOT EXISTS public.enrollments (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id     bigint REFERENCES public.students(id) ON DELETE SET NULL,
  school_year_id bigint NOT NULL REFERENCES public.school_years(id),
  type           text NOT NULL CHECK (type IN ('new','reenrollment')),
  classroom_id   bigint REFERENCES public.classrooms(id),
  parent_id      uuid REFERENCES public.profiles(id),
  student_name   text,
  status         text DEFAULT 'pending'
                 CHECK (status IN ('pending','approved','rejected')),
  enrolled_at    timestamp with time zone,
  approved_by    uuid REFERENCES public.profiles(id),
  notes          text,
  created_at     timestamp with time zone DEFAULT now() NOT NULL
);

-- 4.36 PROMOTION RULES
CREATE TABLE IF NOT EXISTS public.promotion_rules (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_year_id  bigint NOT NULL REFERENCES public.school_years(id) ON DELETE CASCADE,
  from_grade      text NOT NULL,
  to_grade        text NOT NULL,
  min_average     numeric(5,2) DEFAULT 70.00,
  min_attendance  numeric(5,2) DEFAULT 80.00,
  auto_promote    boolean DEFAULT true,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT unique_promotion_rule UNIQUE (school_year_id, from_grade)
);

-- ══════════════════════════════════════════════════════════════
-- SECCIÓN 5: DATOS INICIALES DE MATERIAS
-- ══════════════════════════════════════════════════════════════
-- Siembra de materias base (sin depender de un UNIQUE sobre name, para
-- funcionar tanto en base limpia como en una que ya perdió sus constraints).
-- education_level ya no se usa como categoría fija: queda NULL.
INSERT INTO public.subjects (name, description)
SELECT v.name, v.description
FROM (VALUES
  ('Desarrollo Socioemocional', 'Habilidades socioemocionales'),
  ('Psicomotricidad',           'Desarrollo motor grueso y fino'),
  ('Lenguaje',                  'Expresión y comprensión verbal'),
  ('Descubrimiento del Entorno','Exploración del mundo'),
  ('Arte y Creatividad',        'Expresión artística'),
  ('Inglés',                    'Introducción al inglés'),
  ('Lenguaje y Comunicación',   'Lectura, escritura y comprensión'),
  ('Pensamiento Matemático',    'Números y lógica'),
  ('Exploración y Conocimiento','Ciencias naturales y sociales'),
  ('Arte y Expresión',          'Arte, música y dramatización'),
  ('Formación Cívica y Ética',  'Valores y ciudadanía'),
  ('Educación Física',          'Actividad física y salud'),
  ('Español',                   'Lengua y literatura'),
  ('Matemáticas',               'Aritmética, álgebra y geometría'),
  ('Ciencias Naturales',        'Biología, química y física básica'),
  ('Ciencias Sociales',         'Historia, geografía y sociedad'),
  ('Arte',                      'Artes visuales, música y teatro'),
  ('Tecnología',                'Herramientas digitales')
) AS v(name, description)
WHERE NOT EXISTS (SELECT 1 FROM public.subjects s WHERE s.name = v.name);

-- Admin inicial
INSERT INTO public.profiles (id, email, name, role, accepted_terms, created_at)
VALUES ('c1e72617-ab8f-44c0-b1eb-cdd92eda62e7', 'impulsodigital@gmail.com', 'Administrador', 'admin', true, now())
ON CONFLICT (id) DO UPDATE SET role = 'admin', accepted_terms = true;

-- ══════════════════════════════════════════════════════════════
