-- ============================================================================
-- Karpus Kids — Migración 11: wall_notifications + Realtime para el banner
--
-- La tabla wall_notifications ya era escrita por js/shared/wall.js
-- (_notifyPostAuthor / _notifyCommentAuthor) pero:
--   1. No tenía definición en migraciones (creada ad-hoc en el dashboard).
--   2. Nadie la leía ni estaba suscrita al canal realtime → los comentarios
--      y reacciones en publicaciones NUNCA informaban al autor.
--
-- Esta migración:
--   A. Crea/normaliza la tabla con las columnas que usa wall.js.
--   B. Habilita RLS (cada usuario ve solo SUS notificaciones de muro).
--   C. Agrega la tabla (y las demás que escucha EventBanner) a la publicación
--      supabase_realtime si aún no estaban.
--
-- Idempotente: segura de ejecutar más de una vez.
-- ============================================================================

-- ── A. Tabla ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.wall_notifications (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  actor_id   uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_name text,
  type       text NOT NULL DEFAULT 'comment', -- 'comment' | 'reaction'
  post_id    bigint REFERENCES public.posts(id) ON DELETE CASCADE,
  comment_id bigint REFERENCES public.comments(id) ON DELETE SET NULL,
  message    text,
  is_read    boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Normalización: columnas que pudieran faltar si la tabla fue creada ad-hoc
ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS actor_id   uuid REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS actor_name text;
ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS type       text NOT NULL DEFAULT 'comment';
ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS post_id    bigint REFERENCES public.posts(id) ON DELETE CASCADE;
ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS comment_id bigint REFERENCES public.comments(id) ON DELETE SET NULL;
ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS message    text;
ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS is_read    boolean DEFAULT false;
ALTER TABLE public.wall_notifications ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_wall_notifications_user_date
  ON public.wall_notifications (user_id, created_at DESC);

-- ── B. RLS ──────────────────────────────────────────────────────────────────
ALTER TABLE public.wall_notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "wall_notifications_own" ON public.wall_notifications;
CREATE POLICY "wall_notifications_own" ON public.wall_notifications
  FOR SELECT USING (user_id = auth.uid());

DROP POLICY IF EXISTS "wall_notifications_insert_auth" ON public.wall_notifications;
CREATE POLICY "wall_notifications_insert_auth" ON public.wall_notifications
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- ── C. Publicación realtime ────────────────────────────────────────────────
-- EventBanner (js/shared/event-banner.js) escucha estas tablas vía
-- postgres_changes; sin estar en la publicación los eventos nunca llegan.
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'wall_notifications',
    'notifications',
    'messages',
    'posts',
    'tasks',
    'task_evidences',
    'payments',
    'staff_permits',
    'inquiries'
  ]
  LOOP
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t)
       AND NOT EXISTS (
         SELECT 1 FROM pg_publication_tables
         WHERE pubname = 'supabase_realtime'
           AND schemaname = 'public'
           AND tablename = t
       )
    THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
      RAISE NOTICE 'Added % to supabase_realtime', t;
    END IF;
  END LOOP;
END $$;
